- docs/adr/README.md
- docs/adr/adr-template.md
This PR initialises an ADR directory for ADRs specific to the `Celestia-Node` implementation.
> docs/adr: initialise ADR directory

- .golangci.yml
This PR increases the golint timeout to 2m due to this timeout failure on my other PR: 
https://github.com/celestiaorg/celestia-node/pull/48/checks?check_run_id=3508270276
> ci: increase golint timeout

- docs/adr/adr-002-predevnet-core-to-full-communication.md
This PR documents an architecture decision made regarding the communication pattern between Celestia Core nodes and Celestia Full nodes for devnet.
> docs/adr: ADR for devnet Celestia Core <> Celestia Full node communication

- .golangci.yml
This PR increases the ci run timeout to 5m as per @tzdybal 's suggestion. 
Copying the implementation here: https://github.com/celestiaorg/optimint/blob/main/.golangci.yml
> ci: increase run timeout to 5m

- core/client_test.go
- core/mock_test.go
This PR adds test for remote core node. 
#51 depends on this PR.
> core: add tests for remote node

- core/client_test.go
This PR stores the `QueryForEvent` required for both `Subscribe` and `Unsubscribe` methods on the `core.Client` in a variable for cleanliness in tests.
> core: store new block event query in variable in the test file

- node/full_test.go
This PR adds a unit test to test Full nodes' ability to communicate via libp2p streams. This tests that Hosts are properly started on the node and are able to connect to other nodes directly.
Old PR for reference: #61
> node: add full node p2p stream test

- core/client_test.go
- core/fetcher.go
- core/fetcher_test.go
- node/core/core.go
- node/full.go
- node/full_test.go
- node/node.go
- service/block/interface.go
- service/block/service.go
- service/block/types.go
This PR introduces a block `Fetcher` interface that will encompass the behaviour necessary for the `BlockService` to get new blocks either directly from a Core node or from the Celestia network.
It also adds an implementation of `Fetcher` for the Core `Client`
TODO 
Related to #25 and #26
> block: create `Fetcher` interface

- go.mod
- go.sum
- libs/keystore/fs_keystore.go
- libs/keystore/fs_keystore_test.go
- libs/keystore/keystore.go
- libs/keystore/map_keystore.go
- libs/keystore/map_keystore_test.go
Libp2p does not provide storage for private keys(Peerstore might be a solution but is on-disk version is flawed), so we need to store them somewhere. The Keystore comes to solve this and allows storing different keys for multiple purposes, including storing p2p keys. Further, we can delegate consensus keys to Keystore as it will evolve through time and get more features/implementations.
* Defines interface
* Implements Fs version
* Implements in-memory version
Closes https://github.com/celestiaorg/celestia-node/issues/65
> libs/keystore: introduce Keystore a crypto key manager

- core/client_test.go
- node/full_test.go
- node/light_test.go
This PR changes tests in `node` and `client` pkg to use `require` instead of `assert` for consistency.
> node, client: use `require` instead of `assert` for consistency.

- libs/fslock/lock_unix.go
- libs/fslock/locker.go
- libs/fslock/locker_test.go
Over the weekend in my spare time, I was playing around syscalls and wanted to implement something. The idea fell to do something useful to our current tasks and so I decided to make a locking library, as we need to lock our [Repo](https://github.com/celestiaorg/celestia-node/issues/30) from simultaneous usage. I am aware there are existing libraries solving that, but this one is especially minimal.
* Implemented and tested on Linux/MacOS
* Windows support? Maybe...
> libs/fslock: a simple utility to lock directories

- core/config.go
- core/init.go
- core/init_test.go
- core/mock_test.go
- core/repo.go
- core/repo_mem.go
- libs/utils/fs.go
The penultimate piece for #30. It introduces initialization flow for the embedded Core node along with repository to access Core' stored data. Basically, it implements some of the important functionality for future `init` command.
* Implements custom serialization for `core.Config`(rationale is in the code)
* Starts own collection of utilities
* Provides FS, InMem and Mock repositories
Depends on #71 and #74
Moves towards done #30
> core: initialization and Repository

- core/config.go
- core/repo.go
- core/testing.go
- node/config.go
- node/config_test.go
- node/core/core.go
- node/full.go
- node/full_test.go
- node/init_test.go
- node/light.go
- node/light_test.go
- node/node.go
- node/p2p/p2p.go
- node/repo_mem.go
- node/repo_test.go
- node/testing.go
This is the last TODO of #86.
* MockRepository for Node
* Group mocks in `node` and `core` packages into testing.go
* Split DefaultConfig into default for Light and Full. We don't have a difference right now that will change soon.
* Actually use Repository on the node and tests update
> node: use Repository on the Node and slightly improve testing utilites

- core/fetcher.go
- service/block/erasure.go
- service/block/event.go
- service/block/event_test.go
- service/block/fraud.go
- service/block/interface.go
- service/block/types.go
- service/header/types.go
Implements the types defined [here](https://github.com/celestiaorg/celestia-specs/issues/204).
Resolves #87
> service/header, service/block: Implements spec'd out types for block and header

- core/config.go
- core/init.go
- core/repo.go
- core/testing.go
- go.mod
- go.sum
- node/config.go
- node/config_test.go
- node/core/core.go
- node/full.go
- node/full_test.go
- node/init.go
- node/init_test.go
- node/light.go
- node/light_test.go
- node/p2p/p2p.go
- node/repo.go
- node/repo_mem.go
- node/repo_test.go
- node/testing.go
The final piece for #30. Although, there are some other non-priority things left that can be done later on.
> It took me a while to land this, even the feature is more or less simple. The main complexity comes from the fact that we have multiple Node Types/Mode and Core Repository, that are not used in some types and used in others. Also, we discussed dynamic mode switchability. All this required a flexible Repository to meet such requirements and originally I went towards an over-engineered approach that was not reasonable, so here we are. The current approach has one downside - shared initialization logic. That is, the LightNode and FullNode with remote Core will also initialize Repo for the Core, but won't use it. We can fix that by attaching custom initialization logic to each …
> node: initialization and Repository

- service/block/event.go
- service/block/event_test.go
- service/block/fraud.go
- service/block/fraud_test.go
This PR relies on #87 being merged first.
Resolves #92.
> service/block: add basic encoding validation in `BlockService`

- Makefile
* make format -> make fmt
* Make it Golang idiomatic following `go fmt`. I am a bit tired of misspelling it.
* invisible execution for format with `@`
* There is no gain in seeing `find . -name '*.go' -type f -not -path "*.git*" -not -name '*.pb.go' -not -name '*pb_test.go' | xargs gofmt -w -s` everytime you do formatting.
* extend formatting with go mod tidy
* so we don't need to do it in a separate command eash time
> Makefile: a few updates

- node/config.go
- node/config_test.go
- node/full.go
- node/full_test.go
- node/light.go
- node/light_test.go
- node/node.go
In #86 we moved `Open/Init/IsInit` functions over the unified pattern where they receive Node Type as param. Now, it makes total sense to introduce a `New` Node constructor to would instantiate a Node for a given type. For now, old constructors(NewFull/NewLight) are preserved, same as with `DefaultLight(Full)Config` but we can make them private and/or remove them if we find a reason for that in future
> feat(node): unified node constructor

- libs/fslock/lock_unix.go
> libs/fslock: change build directive to be compatible w/ earlier Go versions

- Makefile
- cmd/celestia/main.go
- cmd/celestia/version.go
The goal for this PR is to add the `version` subcommand of `celestia` command to get more information about the build binary. The new subcommand closes [#155](https://github.com/celestiaorg/celestia-node/issues/155).
- On Linux environment (Zorin OS 16)
> Add version command

- node/full.go
- node/node.go
- node/services/service.go
I have added both OnStart and OnStop hooks from block service and now it could not start/stop manually.
Closes #134
> node: start and stop block service by notification from lifecycle

- service/header/header.go
- service/header/interface.go
- service/header/service.go
This PR implements header `Service` as well as adds two interfaces: `Exchange` and `Store` that cover the behaviours necessary for a node to retrieve/provide `ExtendedHeader`s from/to the network, as well as store/retrieve those `ExtendedHeader`s from the node's local storage.
Related to #24
> service/header: Implement basic header `Service` structure and interfaces

- core/fetcher.go
- core/fetcher_test.go
- service/block/event.go
- service/block/event_test.go
- service/block/interface.go
- service/block/types.go
This PR adds the Commit from the current block in the `ExtendedHeader` by extending the `Fetcher` interface to implement another method `CommitAtHeight` to fetch the Commit at the given block height. This is done so that light nodes do not need to request the subsequent header to have the Commit information from the block height of the given `ExtendedHeader`. 
Resolves #161.
> service/block: add Commit from current block in ExtendedHeader

- service/header/service.go
- service/header/subscription.go
- service/header/subscription_test.go
This PR implements a structure for HeaderSub, exposing an interface for any service / component that needs access to new `ExtendedHeader`s to be able to subscribe to new `ExtendedHeader` events.
Resolves #164. 
Related to #24.
> service/header: implement HeaderSub

- das/daser.go
- das/daser_test.go
- ipld/write.go
- node/light.go
- node/node.go
- node/services/service.go
* Initial DASer implementation which just listens for headers and DASes them
* Adds DASer and Header Service to the node.
Based on #171
Closes #166
> das: implement DASer

- node/p2p/routing.go
Basically, this just ensures nodes (both light and full) are connected to bootstrap peers and their DHT table is refreshed, I was imagining something more complex, but this should be fine.
Close #201
> fix(node/p2p): ensure  DHT bootrapps itself on Start

- node/full_test.go
- service/header/exchange.go
- service/header/local_exchange.go
- service/header/service.go
- service/header/subscription.go
- service/header/subscription_test.go
- service/header/sync.go
- service/header/sync_test.go
* Improved logging
* LocalExchange helper
* Syncer
> Didn't found respective issue syncing
> There is so much to improve and multiple ways to implement header synchronization. I was pulling my head apart with implementation to cover all the edge cases and to be bandwidth cheap, but realized that I need more time which we don't have, so I made a simplest possible syncing for now which should just work for most cases.
> service/header: implement basic syncer

- das/daser_test.go
- node/services/service.go
- service/block/event.go
- service/block/event_test.go
- service/block/service.go
- service/block/store_test.go
- service/header/interface.go
- service/header/service.go
- service/header/subscription_test.go
- service/header/testing.go
`block.Service` now receives a `Broadcaster` from the `header.Service` so that it can `Broadcast()` new `ExtendedHeader`s to the network as they are created during the block handling process.
> service/block, service/header: `BlockService` broadcasts generated `ExtendedHeader`s to network

- libs/keystore/fs_keystore.go
- libs/keystore/map_keystore.go
- node/p2p/identity.go
identity.go previously created a new key on every run of `celestia full init` resulting in new PeerIDs each time. Persisting the keys allows us to have persistent PeerIDs.
> Persist generated key to keystore and reuse existing key if present

- core/fetcher.go
- core/header_fetcher.go
- ipld/read_test.go
- service/header/core_exchange.go
- service/header/core_exchange_test.go
- service/header/dah.go
This PR will allow header service to sync headers from the core node in order to sync up to the chain. This is necessary for bootstrap peers.
> service/header: Header Exchange implemented over Core Node

- cmd/start.go
Closes #210.
Btw, you can also set logging level through ENV
> feat(cmd): allow setting log level for start comamnd

- service/header/core_exchange.go
- service/header/core_exchange_test.go
- service/header/p2p_exchange.go
- service/header/p2p_exchange_test.go
> service/header: Verify hash matches header retrieved in `RequestByHash()`

- go.mod
- node/p2p/pubsub.go
> node/p2p: Deduplicate PubSub msgs

- cmd/flags.go
- cmd/init.go
- cmd/start.go
- node/options.go
- node/services/config.go
- node/services/service.go
- service/header/sync.go
- service/header/sync_test.go
This PR:
* renames `genesis` to `trustedHash` in the codebase to avoid confusion
* extracts flags to common variable for re-use between commands `start` and `init`
> cmd, service/header: rename `genesis` to `trustedHash` to avoid confusion, extract flags to common var for re-use

- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/celestia/main.go
- cmd/init.go
- cmd/start.go
Fixes bug introduced in #229, without the fix `start` does not work.
> fix(cmd): fix repository path handling for Init and Start commands

- Makefile
This last bit is required before the release, otherwise binary wouldn't properly show the version number.
Closes: https://github.com/celestiaorg/celestia-node/issues/163
> feat(Makefile): add tag parsing to inject version from git

- CHANGELOG-PENDING.md
- service/header/p2p_exchange.go
The existing implementation of `P2PExchange.handleRequestByHash` doesn't include the actual `err` value in the `ErrorW` logging call.
> Include the error in P2PExchange.handleRequestByHash error logging

- CHANGELOG-PENDING.md
- cmd/init.go
- cmd/start.go
- node/init.go
- node/init_test.go
This PR removes redundant `node.InitWith` as we have a separate option to pass a Config, so to have similar functionality, one should use `node.Init(node.WithConfig())`.
> node: remove InitWith

- CHANGELOG-PENDING.md
- node/p2p/addrs.go
- service/block/event_test.go
PR supposed to:
- fix https://github.com/celestiaorg/celestia-node/issues/286;
- fix https://github.com/celestiaorg/celestia-node/issues/283;
- and maybe fix https://github.com/celestiaorg/celestia-node/issues/232
> service/block, node/p2p: Fix race conditions in TestExtendedHeaderBroadcast and TestFull_P2P_Streams

- .github/workflows/lint.yml
- CHANGELOG-PENDING.md
- docker/Dockerfile
- docker/entrypoint.sh
Create a new `Dockerfile` that works for both celestia-node full and light nodes while matching the expectations of both the docker-compose and k8s cluster setups. 
At runtime the a `NODE_TYPE` environment variable matching either `full` or `light` is expected. 
If not provided it defaults to `full`. 
For examples see the [docker-compose config](https://github.com/celestiaorg/devops-test/blob/main/devnet/docker/docker-compose.yml#L84) and the [k8s config](https://github.com/celestiaorg/devops-test/blob/main/devnet/k8s/core-nodes/0/core0-deployment.yaml#L76).
This has been manually tested by building the Docker image
```
docker build -f docker/Dockerfile -t jbowen93/celestia-node:multi
``` 
and then testing it with docker-compose
```
cd devnet
./start-docker.sh
```
and with kubernetes
``` …
```
> docker: Create a single Dockerfile that works for full and light `celestia-node`s

- CHANGELOG-PENDING.md
- node/components.go
- node/config.go
- node/core/core.go
- node/fxutil/options.go
- node/fxutil/options_test.go
- node/fxutil/util.go
- node/init.go
- node/light_test.go
- node/node.go
- node/options.go
- node/p2p/identity.go
- node/p2p/p2p.go
This is a solution for https://github.com/celestiaorg/celestia-node/issues/285. It is different from the design there, as it's not possible. Finding the other solution took a lot of time, sketching, and learning. The reason why is the limitation of FX described in uber-go/fx#825. This PR solves the problem by extending `fxutil` lib to mimic `fx` functionality + new `OverrideSupply` option described in uber-go/fx#825. In future, the code of `fxutil` might be deleted once the described `fx` feature is implemented and merged.
This PR might be difficult to understand in detail as it involves reflection + understanding of the DI itself, but also a good opportunity to understand how both worlds work for the implementer and for the reviewers. 
* `fxutil` mimicing `fx` options with more new …
> node: enhance DI allowing overriding of dependencies

- service/header/subscription_test.go
This PR removes `time.Sleep` from `TestSubscriber` and instead uses the new pubsub method to wait to publish until there's at least 1 other peer listening on the topic.
> service/header: Fix `TestSubscriber` flakiness 

- CHANGELOG-PENDING.md
- node/light_test.go
- node/node.go
- node/p2p/host.go
- node/p2p/routing.go
- node/settings.go
Depends on #292 
Removing append from overrides func
Edit node.go
Adding 1 test for checking withHost functionality
Closes #299
> node: Adding WithHost options to settings section

- CHANGELOG-PENDING.md
- node/bridge_test.go
- node/settings.go
Depends on #292 and #301
Adding CoreClient option for node
Closes #302
> node: Adding WithCoreClient option

- CHANGELOG-PENDING.md
- node/store_mem.go
With current datastore, we bump into the race condition when the datastore is being both read and written to. Changing to mutex wrapped datastore has eliminated the data race error findings.
This case is heavily blocking proper initialisation of node and can cause flakiness in test execution.
Found during work on #262 
Co-authored with @Wondertan
> node: Wrap datastore with mutex to prevent data race

- CHANGELOG-PENDING.md
- Makefile
- service/share/share.go
- service/share/share_test.go
* Handle multiple rows concurrently;
Closes #184
> share: handle rows concurrently

- CHANGELOG-PENDING.md
- core/fetcher.go
- node/core/core.go
- service/header/header.go
Includes critical fix for #319 and two minor findings. Commit names are descriptive enough so check those
Closes #319
> Properly fetch Validators from Core and two more fixes

- CHANGELOG-PENDING.md
- node/bridge_test.go
Found this nit during testing. Small name change to be compliant with new naming schema
> node: fix naming of the test from full to bridge

- CHANGELOG-PENDING.md
- node/services/config.go
- node/services/service.go
- service/header/p2p_exchange.go
- service/header/p2p_exchange_test.go
Change config to log warnings with missing trusted peer
In HeaderExchangeP2P func we are creating an addr for the host instead of making it in the removed connect
Removed store in p2pExchange
Now, instead of handling connection ourselves, we are delegating this to libp2p itself and only creating NewStream in `performRequest` func in `p2p_exchange.go`
Solves the issue `panic of closing a closed channel` #350 
Co-authored-by: @Wondertan
> service/header: remove start/stop from P2PExchange

- node/services/config.go
Required for Bridge Node, but also works for Light and in future for Full. This won't be safe for them though, once we stop relying on a trusted peer for the whole syncing, but until then it is safe, as we trust a trusted peer.
Based/depends on #346 
Closes #324
> node/services: use genesis if trusted hash is not set

- CHANGELOG-PENDING.md
- service/header/subscription_test.go
Fixes #173 by separating the creation of the hosts from connecting them, allowing that we configure the gossip protocol on them, otherwise the host doesn't know to gossip with the other host.
> Fix start order of mocknet

- core/client.go
> core: suppress logging of retry-client

- CHANGELOG-PENDING.md
- node/bridge_test.go
- node/config_opts.go
- node/light_test.go
Add tests for WithMutualPeers and WithBootstrapPeers for both bridge/light types
Remove redundancy in WithMockClient test
This is needed for the swamp to initialise the light node with 2+ connections to bridge nodes
Resolves #372
> node/config: add WithBootstrapPeers option

- CHANGELOG-PENDING.md
- params/bootstrap.go
Just added a list of boostrappers
> feat(params): add bootstrappers

- .gitignore
- CHANGELOG-PENDING.md
- das/daser_test.go
- logs/logs.go
- node/components.go
- node/core/core.go
- node/fxutil/options.go
- node/services/service.go
- service/header/core_exchange.go
- service/header/core_listener.go
- service/header/core_listener_test.go
- service/header/header_serde.go
- service/header/header_verify.go
- service/header/header_verify_test.go
- service/header/interface.go
- service/header/local_exchange.go
- service/header/p2p_exchange.go
- service/header/p2p_subscriber.go
- service/header/service.go
- service/header/store.go
- service/header/store_test.go
- service/header/subscription_test.go
- service/header/sync.go
- service/header/sync_ranges.go
- service/header/sync_test.go
- service/header/testing.go
- service/header/verify.go
- service/header/verify_test.go
Previously, we were syncing only once on `Start` and were catching up the chain by Pubsub topic. This PR changes that we can sync multiple times during runtime and if we missed some new Headers from PubSub topic, that will trigger sync again to catch-up. Also, this PR starts to verify new non-adjacent headers from PubSub and caches them to later be applied adjacently to avoid unnecessary request of already rcvd headers
Also fixes a variety of minor things.
Depends on #327 
Closes: #242 
Closes: #326
> header: hardening syncing logic

- Makefile
- node/tests/swamp/config.go
- node/tests/swamp/swamp.go
- node/tests/swamp/sync_test.go
- node/tests/sync_test.go
Adapting the sync test to this change
Resolves #371 #392
> swamp: separate tendermint node creation from the swamp

- service/header/store.go
Note that I have no idea how to calculate a universal value for cache sizes in our case, so this is mostly playing around and experimenting based on a feeling that the initial values are too conservative.
> perf(services/header): increase Store caches sizes

- CHANGELOG-PENDING.md
- node/services/service.go
- service/header/interface.go
- service/header/p2p_exchange_test.go
- service/header/store.go
- service/header/store_height_indexer.go
- service/header/store_heightsub.go
- service/header/store_heightsub_test.go
- service/header/store_test.go
- service/header/sync_test.go
- service/header/testing.go
The PR makes all the writing to Store happen through writeLoop in a separate routine so that
* Appends are not blocked by long disk IO writes and DB compactions
* We can batch header writes
Also, this PR makes Append writes atomic. Meaning that all the required writes are done in one single batch. Previously, each Append did 3 full io write requests to the disk for:
* Headers themselves
* Highest head reference
* Height indices
Now we make all these writes atomically in one io write additionally to collecting multiple Appends in one big append, leading to a way lesser io writes.
Based on #430 
Closes https://github.com/celestiaorg/celestia-node/issues/448
Review commit by commit
> refactor(service/header): rework on disk writing strategy of the Store

- CHANGELOG-PENDING.md
- service/header/interface.go
- service/header/p2p_exchange_test.go
- service/header/store.go
- service/header/store_test.go
- service/header/sync.go
- service/header/sync_test.go
Currently, Store allows passing via Append partially valid header ranges, but it doesn't report back how many headers were applied, so the caller can react accordingly. This PR provides this by changing the Append method.
Based on #431 
Closes https://github.com/celestiaorg/celestia-node/issues/451
Review commit by commit
> feat(service/header): update Store.Append to return amount of applied/valid headers 

- node/tests/swamp/config.go
- node/tests/swamp/swamp.go
- node/tests/sync_test.go
- move test from swamp to tests dir
- adapt makefile to new changes in dir test placement
- rename config to infracomps
- use coreclient with swamp subscription id instead of blockfetcher
We need store to successfully save the state of node in order to start/stop the existing node
Relates to #370
> swamp: Add store method to node creation

- CHANGELOG-PENDING.md
- service/header/store.go
- service/header/store_init_test.go
Fixes #457 by making store head being lazy loaded and not on Start.
> fix(service/header): lazily load Store head

- CHANGELOG-PENDING.md
- cmd/flags_header.go
- node/config_opts.go
- node/services/config.go
- node/services/service.go
- node/tests/README.md
- service/header/p2p_exchange.go
- service/header/p2p_exchange_test.go
Fixes #364 
Chages:
* multiple trusted peers can be passed on node initialisation;
* trusted peer will be taken randomly on `performRequest`;
> Pass trusted peers to config

- CHANGELOG-PENDING.md
- service/header/interface.go
- service/header/p2p_exchange_test.go
- service/header/store.go
- service/header/sync.go
- service/header/sync_ranges.go
- service/header/sync_test.go
Mainly this PR provides an API to have a visibility of what is happening inside Syncer, via
* `State()` which shows detailed information of an ongoing sync
* `WaitSync` which allows waiting for an ongoing sync to finish
* Changes `Stop()` to wait for an ongoing sync to finish, before stopping the syncing.
Depends on #434
Closes: https://github.com/celestiaorg/celestia-node/issues/450, https://github.com/celestiaorg/celestia-node/issues/405
> service/header: SyncState

- service/header/core_listener_test.go
Attempts fix for #453 
It is not locally reproducible so we will have to run the CI several times, but I applied the same fix as in #342. I am assuming this issue stems from the same issue addressed in that PR.
> service/headers: Fix race in `TestCoreListener`

- CHANGELOG-PENDING.md
- go.mod
- node/store.go
Motivations for each configuration field are described in the comments.
Need to be reviewed ASAP for the release.
> perf(node/store): fine-tune Badgerdb params

- CHANGELOG-PENDING.md
- go.mod
- go.sum
- node/components.go
Note that the [watchdog](github.com/raulk/go-watchdog) didn't fix the OOM issue I had during synchronization and I am not entirely sure the addition of this utility is fully justified in our case. However, the problem it solves is real and according to PL folks, it helps them to prevent OOMs caused by occasional spikes of memory allocation that Badger made, like in our case. Also, the problem of Golang runtime not being able to execute GC in such cases, preventing the OOM is real and the Golang team confirmed this. To understand the issue you can narrow down through all the issues that watchdogs links to in his README. One more good point of watchdog, which sells it for me, is that it automatically captures heap profiles when heap size exceeds some threshold and I would like to have this …
> feat(node): add go-watchdog to curb OOMs

- CHANGELOG-PENDING.md
- cmd/cel-shed/header.go
- cmd/cel-shed/main.go
- service/header/store_heightsub.go
Implements a utility to force the store to change it is head. Was useful to recover from bug #457.
Very low priority to review
> feat(cmd/cel-shed): new header category and store-init cmd

- params/bootstrap.go
Their identities changed, so we need to update those.
> fix(params): update bootstrappers' peer ids

- CHANGELOG-PENDING.md
- service/header/p2p_exchange.go
This pull request would close #493.
> service/header: add network name to protocol ID

- node/tests/swamp/swamp.go
- node/tests/sync_test.go
Introduction of Full Node to the swamp tests 
1. Creation of the full node
2. Sync test for full <-> bridge and light ->full -> bridge
Based on #416 #428 #438
Resolves #417
> swamp: Full Node sync tests

- go.mod
- ipld/read.go
- ipld/read_test.go
- node/services/service.go
- service/share/full_availability.go
Fixes #247
* fetching data from root instead of particular share;
* removed share counter;
Time duration from start fetching till the end of fetching:
```
=== RUN   TestRetrieveBlockData
=== RUN   TestRetrieveBlockData/1x1(min)
374.436µs
=== RUN   TestRetrieveBlockData/32x32(med)
52.936894ms
=== RUN   TestRetrieveBlockData/128x128(max)
1.298028147s
```
Unfortunately, test  TestRetrieveBlockData/128x128(max) failed by timeout. I guess bottleneck could be [here](https://github.com/celestiaorg/rsmt2d/blob/ac0f1e1a51bf7b5420965fb7c35fa32a56e02292/extendeddatacrossword.go#L77). In the worst case we are  iterating over a slice of 65k of elements and making a pretty heavy operation of copying.
> ipld: retrieve data starting from root

- node/tests/swamp/swamp.go
- node/tests/sync_test.go
Removed all `node<T>WithStore` creation functions for each type of nodes. 
In the meantime, I've seen that execution on macOS is taking much more time comparing to linuxOS, so I've bumped the context timeouts 
Resolves #454
> swamp: remove redunancy in node creation

- .github/workflows/docker-build.yml
- docker/Dockerfile
This PR updates the docker-build GH Action. Notable changes
- Runs on pushes to all branches and tags the image with the short sha of the git commit
- Builds multi platform (amd64 and arm64) images using cross compilation
You can see an example of a successful run [here](https://github.com/jbowen93/celestia-node/actions/runs/2018410000) with the resulting images pushed [here](https://github.com/jbowen93/celestia-node/pkgs/container/celestia-node)
> Update docker-build GH action to push sha tagged images

- service/header/store_heightsub.go
Luckily, this wasn't causing any problems to us yet and I just caught it randomly by looking at the code. Pretty embarrassing bug it is.
> fix(service/header): unlock the heightSub lock on a rare case

- service/header/p2p_exchange.go
Resolves problems reported in #511 (and consequently #510) for now as we pushed a protocol upgrade without handling for backwards compatibility with the latest release / devnet. 
We will re-introduce this upgrade in the next release.
> service/header/p2p_exchange: Revert exchange protocol upgrade 

- node/config_opts.go
- node/node_bridge_test.go
- node/node_light_test.go
- node/p2p/misc.go
- node/p2p/p2p.go
- node/p2p/routing.go
- params/bootstrap.go
Currently, we allow users to configure bootstrap peers, while this set of peers is constant and defined by the network infrastructure providers, so this is something that users shouldn't be able to change deliberately. The only case where users would want to change their bootstrappers is when they want to join a different network, but this is something that will be done automatically when we start to support multiple networks (#349). Originally, we had this field to be able to quickly configure bootstrappers, but it was clear then that configuring this is not a good idea. Also, putting wrong values there may break network connectivity so altogether it makes sense to remove this field.
> This is what I decide to do together while fixing #488. Something simple to get into working mode again …
> chore(node): always use `param` defined bootstrappers and remove Bootstrappers config field

- core/fetcher.go
- go.mod
- go.sum
- service/header/core_listener.go
- service/header/interface.go
- service/header/p2p_subscriber.go
Resolves https://github.com/celestiaorg/celestia-node/issues/499. Substitutes https://github.com/celestiaorg/celestia-node/pull/507
Reviewable commit-by-commit
I coauthored @renaynay on some commits based on the code introduced in #507
> fix(core): prevent spamming of old headers during bridge node sync

- das/checkpoint_store.go
- das/checkpoint_store_test.go
- das/daser.go
- das/daser_test.go
- das/doc.go
- das/interface.go
- node/services/service.go
- service/header/testing.go
This PR implements DASing of past headers in a single routine. 
Eventually, this will be parallelised. 
Resolves https://github.com/celestiaorg/celestia-node/issues/181.
> das: DASing of past headers

- cmd/flags_header.go
- node/config_opts.go
- node/tests/sync_test.go
- Edit WithTrustedPeers to accept a slice of strings/multiaddresses
- Adapt flags
- Minor prettifying of how we treat addr[0] as a separate var called `trustedPeers`
- Increased timeout context for start/stop for stable local execution on macOS, when user executes `make test` in cli
Resolves #418
> swamp/tests: light node syncs with multiple trusted peers

- .gitignore
For some reason `./` doesn't work with gitignore
> chore(.gitignore): fix gitignore for files in root

- node/components.go
- node/fxutil/options.go
- node/node.go
- node/node_light_test.go
- node/p2p/bitswap.go
- node/p2p/host.go
- node/p2p/misc.go
- node/p2p/routing.go
- node/services/config.go
- node/services/service.go
- node/settings.go
- params/bootstrap.go
- params/default.go
- params/genesis.go
- params/network.go
- params/networks.go
Previously we had network being defined as global state in params pkg, this PR changes this so the network is registered on the node itself. This wasn't causing problems for us yet and this is a preemptive measure. Also, the more I think about it(in the context of #552), the more possible issues are jumping into my head and this solution doesn't have those. The main problem was with the way the Swamp environment had to override the network to be Private using a global state. This is now not an issue and each Node keeps track of the network on its own.
> refactor(params): globalstateless network definition

- node/node_bridge_test.go
- node/node_light_test.go
- node/testing.go
- node/tests/swamp/swamp.go
- params/bootstrap.go
- params/default.go
- params/genesis.go
- params/network.go
Substitutes #552.
Based on #556.
Closes #550 
Also, makes Node and Swamp tests run in the private setup. This is also why I did a cleanup in https://github.com/celestiaorg/celestia-node/pull/557
> feat(params): add new Private network for private/testing setups

- das/daser.go
- service/header/doc.go
Successful logging can confuse when it is not really successful
> chore(das): prevent logging of success on failed sample

- .github/ISSUE_TEMPLATE/bug-report.yml
The issue template already automatically adds the `bug` label, so the `[Bug]: ` in the title is redundant.
> Remove title from bug issue template

- service/share/share.go
- service/share/share_test.go
- service/share/testing.go
> Fix `GetSharesByNamespace` ordering

- .github/ISSUE_TEMPLATE/bug-report.yml
After merging #609 PR, bug template is not available anymore in our repo due to a template issue containing an explicit empty title. `title: ""`
This PR should fix this proprely and return back the bug template.
> github/admin: fix the empty title for bug template

- go.mod
- go.sum
- ipld/read.go
- ipld/read_test.go
- ipld/retriever.go
- ipld/retriever_quadrant.go
- ipld/retriever_test.go
- service/header/core_listener_test.go
- service/share/full_availability.go
- service/share/interface.go
- service/share/light_availability.go
- service/share/share.go
This PR comes from the requirement to make tests in #598 pass deterministically by reimplementing the original goal of #517. At first, I implemented the goal by simply updating the current code without reworking it. Unfortunately, that didn't work well, and there was a bug that made me stuck for a few days. After extensive multiday debugging, I cleaned up and reworked the existing implementation of RetrieveData in studying the code for the bug. The rework landed into a new `ipld.Retriever` component, which now not just requests the data via sampling quadrants but also retries for other quadrants. 
Eventually, the bug was about rsmt2d not being suitable for recovering over the same data square multiple times, as it sets nil shares to zeroed shares to the given flattened square slice(it …
> shares|ipld: Rework data retrieval 

- node/node.go
Looks like this now: 
```
2022-04-27T15:34:21.209+0100	INFO	node	node/node.go:104
/_____/  /_____/  /_____/  /_____/  /_____/
Started celestia DA node
node type: 	light
network: 	devnet-2
/_____/  /_____/  /_____/  /_____/  /_____/
The p2p host is listening on:
*  /ip4/192.168.1.172/tcp/2121/p2p/12D3KooWQAFwc4p5hQUpzU6UgLDEcMD5JVGpMrqWQ8SfUtrZ1G4v
*  /ip6/::1/tcp/2121/p2p/12D3KooWQAFwc4p5hQUpzU6UgLDEcMD5JVGpMrqWQ8SfUtrZ1G4v
```
> node: Distinct start node log to distinguish node type info from rest of logs

- node/node.go
- service/state/core_access.go
- service/state/interface.go
- service/state/rpc.go
This PR adds a `SubmitPayForData` endpoint that builds, signs and submits a `PayForData` msg using celestia-app's new `PayForData` API. 
So far, I've only tested the endpoint manually. Unit tests for checking state endpoints are likely not feasible (until a lightweight mock celestia-app is created), but we will look into creating a swamp test to stand up a single instance of celestia-app to test the state endpoints as an integration test instead.
> service/state: Add `SubmitPayForData` endpoint

- service/state/rpc.go
```
curl -X POST -d '{"namespace_id": "0000010000000100", 0000, "max_data_size": 16}' http://127.0.0.1:26658/submit_pfd
```
> service/state: Clean up RPC endpoint for `/submit_pfd`

- .gitignore
I had to make local changes in rsmt2d(public Get/SetCell), and new go work feature appeared to be useful for that, and I don't want it to be accidentally committed, as it defines workspace specifically for local development
> chore: update .gitignore to include go.work

- fraud/bad_encoding_test.go
- ipld/get_test.go
- ipld/retriever.go
- ipld/retriever_test.go
- service/share/full_availability.go
- service/share/share.go
> fix(ipld): simply rely on global rsmt2d.Codec constructor for now to avoid races

- node/init.go
- params/bootstrap.go
- params/default.go
This PR introduces the ability to set a custom network type, genesis hash, and bootstrappers via setting environment variables. If a custom network is specified, the following warning will be printed for the user: 
```
WARNING: Celestia custom network specified. Only use this option if the node is freshly created and initialized.
**DO NOT** run a custom network over an already-existing node store!
```
*Note*: the terms `chain-id` and `network name/ID` are used interchangeably.
* `CELESTIA_CUSTOM_GENESIS="<chain-id>=<genesis_hash>"` adds the new network to the registry with the given genesis hash
* `CELESTIA_CUSTOM_NETWORK="<chain-id>"` picks the given network from the registry (it must already exist inside the registry)
* `CELESTIA_CUSTOM_BOOTSTRAPPERS="<chain-id>=<comma-separated list of …
> params: Introduce `CUSTOM` network type

- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/flags_key.go
- node/components.go
- node/config.go
- node/config_opts.go
- node/key/key.go
- node/state/core.go
This PR adds logic to check if a key was found in the given keystore path, and if not, a new key is generated on spot for the node to use for state interaction, allowing for better UX upon node start up.
New logs: 
```
2022-05-16T11:04:36.200+0100	INFO	state-access-constructor	state/core.go:42	NO KEY FOUND IN PATH, GENERATING NEW KEY...	{"path": "/Users/<>/.celestia-full/keys"}
2022-05-16T11:04:36.208+0100	INFO	state-access-constructor	state/core.go:48	NEW KEY GENERATED...
NAME: celes
ADDRESS: celes1gflh3mcttn02w7ahhjuucw8ajt69zu2g43wl9y
MNEMONIC (save this somewhere safe!!!):
present disorder solve luxury junk army lamp toward motor hello butter rate oppose parade absurd turtle person arrive tomato junk noise script mass rocket
```
> node/state: Generate key for node if no key found in keystore path

- node/rpc_test.go
- service/share/share_test.go
This PR fixes a failing test for the `/namespaced_shares` endpoint by adding an expected err message check.
> node: Include expected err msg in`/namespaced_shares` test

- ipld/get.go
- ipld/retriever.go
- ipld/retriever_byzantine.go
* It does make sense to keep ErrByzantine in ipld/get.go
* Not to bloat Retriever
> chore(ipld): extract byzantine error and constructor for it into a separate file

- go.mod
- go.sum
- ipld/get_test.go
- ipld/retriever.go
- ipld/retriever_byzantine.go
- ipld/retriever_quadrant.go
I tried updating to this version before but didn't like that we needed to keep both flattened and imported squares, so that code became even bulkier for the next currently unpushed iteration of Retriever, so I decided to wait until the requested rsmt2d API changes to land before upgrading(cc @adlerjohn), but now we have to update as core updated already.
> deps: bump rsmt2d to 0.5.0

- node/services/service.go
- params/default.go
- params/genesis.go
This PR allows the `CELESTIA_CUSTOM` environment variable to be set with only a network name. Both `genesis hash` and `bootstrappers` are optional additions.
> params:  Allow running `CELESTIA_CUSTOM` without bootstrappers (for bridge)

- node/components.go
- node/services/empty_block.go
- service/share/empty.go
This fixes an issue with an optimisation inside of `header.MakeExtendedHeader` where if a block has empty data, we do not store it to prevent unnecessary redundancy. The problem is, we forgot to ensure that an empty block was stored **at least once**. We found this bug while trying to run a light node against a bridge node on `dryrun-2` and found that the `DAS` functionality in light node was hanging -- this was due to the bridge node not being able to serve blocks to the light node as a result of never having stored that empty block.
This PR ensures that. 
There is an additional problem with this PR however, which is that an empty block will be stored upon construction *every time*. To fix that, we need to implement a solution that checks to see if an empty block has already been stored …
> node/services: Invoke function to ensure that an empty block is stored at least once

- header/p2p/exchange.go
This PR introduces a **breaking** change to upgrade the p2p header exchange protocol ID such that it takes the following format: `/header-ex/v0.0.2/<network_ID>`
example: 
```
/header-ex/v0.0.2/dryrun-2
```
Use this PR in favour of https://github.com/celestiaorg/celestia-node/pull/546
> BREAKING CHANGE(header/p2p/exchange): Upgrade and reformat protocol ID

- das/daser.go
- das/daser_test.go
- service/share/testing.go
This PR implements a change to, instead of logging the error and continuing sampling upon failure, to just return out of the sampling routine(s) (this is true for both the catchUp routine and the general samplingRoutine).
It also implements an error log + warn log prompting users to restart the node in order to re-start the sampling routine(s). 
This design will change once https://github.com/celestiaorg/celestia-node/issues/427 is implemented.
> das: Return from sampling routine upon sampling failure

- Makefile
- cmd/cel-key/main.go
- cmd/cel-key/node_types.go
- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/celestia/main.go
This PR extracts the cosmos sdk key utility from the main celestia-node binary and into a separate `cel-key` binary. 
Use the following flag `--node.type <bridge || full || light>` in order to set the keyring-dir to bridge, light, or full store directory. 
This prevents us having to use cosmos sdk client context initialisation (which is quite messy) inside celestia-node binary.
Thank you @evan-forbes and @Bidon15 for figuring out how to make the key utility actually work after it was broken during the upgrade :) 
`make cel-key` --> builds cel-key binary
`make install-key` --> installs cel-key in GOBIN
> cmd/cel-key: Extract key utility into separate binary to prevent tight coupling between sdk and celestia-node binary

- cmd/celestia/bridge.go
This PR removes the `headers.trusted-hash` flag from bridge node options.
> cmd/bridge: Remove `--headers.trusted-hash` flag for bridge node

- core/client_test.go
- core/fetcher_test.go
- core/testing.go
- header/core/listener_test.go
- header/store/heightsub_test.go
Fixes #683
Fixes #467 
Also, #736 did a good job for us and:
Closes https://github.com/celestiaorg/celestia-node/issues/582 
Closes https://github.com/celestiaorg/celestia-node/issues/608
Hopefully closes https://github.com/celestiaorg/celestia-node/issues/584
Hopefully closes https://github.com/celestiaorg/celestia-node/issues/579
Bonus: https://github.com/celestiaorg/celestia-node/issues/476
(it does not really fix this #476, but it fixes the flakeyness that was mixed up with #476, while #476 is another one that was not reproduced for a long time, and I assume it is now fixed)
> Oblitirate test flakiness

- node/testing.go
So that `bind: address already in use` never happens on the node tests.
> fix(node): ensure RPC server is always started with 0(random) port in tests

- params/default.go
> params: Fix issue in `CELESTIA_CUSTOM` to be able to parse genesis even if bootstrappers not provided

- node/testing.go
> node: Use in-memory keyring signer for `TestNode`

- ipld/retriever.go
- ipld/retriever_test.go
An update of rsmt2d happened in https://github.com/celestiaorg/celestia-node/pull/737 during Mamaki launch preparation. This update changed our code not to reimport the square on each reconstruction attempt which silently sneaked in the problem, which is not reproducible with current tests. Reconstruction tests(#702) reproduce it, but they are not yet merged.
I was able to change the code to reproduce it reliably. Mainly I had to fetch only from columns and force the code to download only [2:4) quadrants. Unfortunately, it is hard to extract the reproducible case in a separate test, so we can either rely on reconstruction tests that are soon to be merged, or I can still try to make a test.
The reason for the bug is explained in #787, as well as a cleaner way to fix it. 
Closes #787
P.S. …
> fix(ipld): fix reconstruction by re-enabling re-importing of rsmt2d.ExtendedDataSquare

- ipld/retriever.go
Mainly this PR fixes two races:
1. One race happens when in one slice slot, two routines are trying to write the same share. Two because we have two sources for each share: Row and Col. Also, this does not happen on a happy path, and only in case, Retriever tries to fetch as many shares as possible to reconstruct the block, explaining why the race was uncovered with #702.
The mentioned race is a known one, and we had an incorrect attempt previously to fix it https://github.com/celestiaorg/celestia-node/commit/cca832acb6dbb03ac734fa5090d50bc319b9d0ba. 
This fix is correct and achieved by keeping a mutex per share. If a share comes from any of two sources first, it locks the slot and prevents a share from another source from being written.
2. The second race happened after the square was …
> fix(ipld): fix races in the Retriever's doRequest method

- header/core/exchange.go
- header/core/exchange_test.go
- header/interface.go
- header/local/exchange.go
- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/store/init.go
- header/sync/sync.go
This PR changes `Exchange` interface to just implement `Getter` as they are performing the same functions just with different names.
> header: `Exchange` interface implements `Getter`

- cmd/flags_core.go
There is no need to check if `port == ""` as `net.SplitHostPort` errors out if port is empty.
> cmd: Minor clean up in validation of given rpc endpoint

- service/share/cache_availability.go
During the review of #786, I was assuming the autobatch datastore has an internal lock, but it turns out to be not the case.
Was found while making #592
> fix(share): protect datastore autobatch in CacheAvailability with a lock

- node/tests/fraud_test.go
On latest main run, CI jobs have detected an issue : 
https://github.com/celestiaorg/celestia-node/runs/7115039774?check_suite_focus=true
> swamp: fix TestFraudProofBroadcasting call of BlockTime

- Makefile
- README.md
Resolves #332 
Although I agree with [marbar3778](https://github.com/marbar3778)'s assertion that this is an issue maybe better fixed by documentation and we could continue to use the golang native tooling, here is a PR with the Makefile target implemented as proposed.
I moved the existing `go install ...` behavior to `make go-install`. I also elected to always build before install and prompt for sudo within the `install` target, to keep the UX as `make install` rather than `make build; sudo make install`.
`$PREFIX` can be overridden like `make PREFIX=/my/dir` if needed, but I'm not sure this is worth mentioning in the README
> Add install target in Makefile, move old behavior to go-install

- logs/logs.go
- node/tests/swamp/swamp.go
This is to stop pouring out useless bitswap related debug logging in the swamp tests. Funnily, it also fixes the CI.
> feat(logs): new utility to quickly set debug logging

- README.md
Remove the test and lint badges because they stopped working after https://github.com/celestiaorg/celestia-node/pull/890
> docs: Add Go CI badge

- cmd/flags_core.go
- core/client.go
- core/testing.go
- node/components.go
- node/config_opts.go
- node/core/core.go
- node/state/core.go
- node/state/state.go
- node/testing.go
- node/tests/swamp/swamp.go
- service/state/core_access.go
This PR consolidates flags related to adding a core endpoint. The reasoning behind this is to prevent users from having to pass too many flags once #571 is resolved (since the core accessor will now need both a `gRPC` and `RPC` endpoint for the celestia-core connection).
**In the case that the default ports are exposed (grpc:9090, rpc:26657) on the celestia-core endpoint**:
```
celestia <node_type> start --core <ip addr of core endpoint>
```
**In the case that custom ports are exposed on the celestia-core endpoint**:
```
celestia <node_type> start --core <ip addr of core endpoint> --core.grpc 9090 --core.rpc 26657
```
If `--core.grpc` || `--core.rpc` are not provided, we assume the defaults and attempt to connect.
> cmd | node: Refactor core flags

- node/p2p/p2p.go
> Modular software plague warning ⚠️ ☢️ 
This makes our nodes use QUIC by default while still supporting TCP and falling back to it if there is a case. 
As simple as it is. 
Fixes #686
> feat(node/p2p): enable QUIC by default with the config

- node/components.go
Changing applied Availability type is done in order the bridge node can advertise itself in p2p network.
> fix: change applied availability for bridge node

- docs/adr/adr-008-p2p-discovery.md
https://github.com/celestiaorg/celestia-node/pull/924 sparked a discussion over whether bridge nodes should also perform active discovery or not, and after a discussion with @Wondertan, we agreed that it should for the reasons described in the changes below.
> docs/adr: Update p2p disc ADR to include bridge node details

- docs/adr/adr-004-state-interaction.md
- go.mod
- go.sum
- header/interface.go
- node/components.go
- node/state/core.go
- node/state/state.go
- service/rpc/endpoints.go
- service/rpc/state.go
- service/state/core_access.go
- service/state/helpers.go
- service/state/interface.go
- service/state/service.go
Tl;dr, instead of requesting balance from core endpoint, the node now requests proofs as well and, using the proofs, verifies the returned balance against the `AppHash` of the corresponding block.
TODO: 
Resolves #571.
Based on #910 , will rebase and mark as ready for review once merged.
> service/state: Implement balance verification against `AppHash`

- header/p2p/subscriber.go
- header/p2p/subscription.go
- header/p2p/subscription_test.go
Second part for #823
Note: ValidatorData for fraud package is implemented in #938
> header/p2p: set ValidatorData field for header message

- header/sync/ranges.go
- header/sync/sync.go
> header/sync: Unexport unintentionally exported field in `ranges`

- Makefile
A simple change; the only problem is that it requires installed `markdownlint` under the PATH. If we don't want this, we can either: ignore the error if not installed or extract into a separate Makefile command
Closes https://github.com/celestiaorg/celestia-node/issues/967
> feat(Makefile): formatting and linter for markdown

- ipld/plugin/nmt.go
My understanding of the bug right now is that the bitswap msg that was rcvd from the network had the wrong size of inner nodes hashes, and instead of erroring out, our IPLD plugin panics. It's not clear what could cause the wrong msg size under normal conditions, but it's clear that we have to fix it by checking if the sizes of msgs are correct.
Closes #952 and closes #780
> fix(ipld/plugin): verify that data written to namespaceHasher has legit size

- node/tests/p2p_test.go
Resolves #963
Root cause: pubsub was restoring the connection between the nodes, so we didn't get the disconnect event as expected.
https://github.com/libp2p/go-libp2p-pubsub/blob/60cf38003244a277084c6f3eec0e584ab6cc07bd/pubsub.go#L710
> swamp/discovery: fix flakiness in restart node discovery test

- ipld/get.go
- ipld/get_namespaced_shares.go
- ipld/get_shares.go
- ipld/get_test.go
- ipld/helpers.go
- service/share/share.go
Closes #697. Still very much a WIP, so a draft, have some open questions:
> feat(ipld): concurrent GetSharesByNamespace

- go.mod
- go.sum
Supplement for #536. Change from this commit is needed to simplify logic inside fraud sync.  
Updated to the latest pub sub version + small changes that hasn't yet merged.
Bonus: should fix https://github.com/celestiaorg/celestia-node/issues/899
> dep: update pubsub fork version

- service/state/core_access.go
This PR implements a check to ensure that the `value` returned by the ABCI balance request is not empty. If the balance is empty, it will return 0 and log out an err.
> feat (service/state): If account doesn't exist at given height, fail gracefully

- cmd/cel-key/main.go
- cmd/celestia/main.go
- service/rpc/endpoints.go
- service/rpc/state.go
- service/state/core_access.go
- service/state/interface.go
- service/state/service.go
> feat(rpc): Transaction proxy for staking tx types

- go.mod
- go.sum
This reverts commit 69a4ee5aee495299930575bfefec7a012fe47059.
Closes #1035, closes #1032, closes https://github.com/celestiaorg/celestia-node/issues/1034
> Revert "chore(deps): bump github.com/ipfs/go-bitswap from 0.8.0 to 0.9.0"

- fraud/testing.go
- node/node.go
On main rn there are two linter errors, making any branches need to fix the linting errors when a PR is opened. This fixes that
So `fx.Extract` got deprecated (actually it was soft-deprecated a while ago but they recently forced the deprecation)
The solution is to throw the `Node` struct directly into `fx.Populate`, meaning we need to add `fx.In` to the struct, and ignore the unexported fields (start, stop)
Other one is probably from fraudsync, as its in `fraud/testing.go`
> chore: resolving linter errors on main

- cmd/cel-key/node_types.go
- cmd/cel-shed/header.go
- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/flags_node.go
- params/default.go
- params/genesis.go
- params/network.go
Closes #1066 .
- node store, extend home directory with network name
- Keep CELESTIA_CUSTOM, deprecate CELESTIA_PRIVATE_GENESIS
- panic will be taken care of by the node store naming extension
- Add `--node.network < arabica || mamaki || ... >`
- Fixes cel-shed and cel-key packages
> feat(cmd): Provide ability to specify network to user

- header/header.go
- header/sync/ranges.go
- header/sync/sync.go
- header/sync/sync_head.go
- header/sync/sync_test.go
- header/verify.go
- node/rpc_test.go
- node/services/service.go
- params/network.go
In https://github.com/celestiaorg/celestia-node/pull/978 we started adding the `Head` method to Syncer; however, it's not that straightforward, and the deeper we looked, the more issues we found in Syncer related to the new `Head` method, so it was decided to extract a separate preparation PR that ensures the new `Head` is safe to use by multiple routines and returns as recent header as possible.
The previous version of Syncer struggled with two issues:
* On Syncer's start, synchronization didn't start and waited for a gossiped header trigger sync and set a sync target (only when the subjective head was not expired)
* This is why Node could wait up to block time second to start syncing
* There was no way to request the most recent objective header of the network
* I.e. if the user wanted …
> feat|refactor(header/sync): network head determination

- service/rpc/endpoints.go
- service/rpc/state.go
- service/state/core_access.go
- service/state/interface.go
- service/state/service.go
- service/state/state.go
Closes #986.
Also removes the abstraction of `sdk.Address` to make it explicit that our queries only support their corresponding address type, `AccAddress` or `ValAddress`
> feat(rpc): implementing staking reads and replace sdk.Address

- header/interface.go
- header/sync/sync_head.go
- node/state/core.go
- node/state/state.go
- service/state/core_access.go
- service/state/service.go
`CoreAccessor` relies on the `Syncer` implementation of `header.Head` instead of the `header.Store` implementation of `header.Getter` in order to provide access to more current network head, and consequently, balance information.
> refactor(service/state): `CoreAccessor` relies on `header.Head` instead of `header.Getter`

- docs/adr/adr-11-blocksync-overhaul.md
[Rendered](https://github.com/celestiaorg/celestia-node/blob/hlib/docs/adr-11/docs/adr/adr-11-blocksync-overhaul.md)
> docs(adr): BlockSync Overhaul ADR #011 - Part 1

- go.mod
- go.sum
- service/state/core_access.go
Removes ibc-go as a dependency of node and uses cosmos-sdk DefaultProofRuntime instead.
> refactor(service/state): Use DefaultProofRuntime instead of ibc-go `VerifyMembership` endpoint

- CONTRIBUTING.md
I didn't have `protoc` installed so when I ran `make pb-gen` I encountered an error
> Add Protobuf section to CONTRIBUTING.md

- service/rpc/state.go
- service/state/core_access.go
- service/state/interface.go
- service/state/service.go
- service/state/state.go
Closes #1085 
Notes:
- The `Accessor` interface still requires an `AccAddress` in Transfer. This is because the transfer does in fact need an account address. However: We can convert a `ValAddr` to an `AccAddr` while handling the request.
- BalanceForAddress does take ANY address type again (so `sdk.Address`), and the RPC handles only `AccAddress` and `ValAddress`.
- When querying the balance of validators, something blows up with retrieving proofs. For example try querying the balance of `celestiavaloper1t5x0tdfepqjnez24keew4p46v89a0wn0s7fmup` on Arabica.
Good insight to keep:
The underlying bytes of an `sdk.Address` do not include the HRP or checksum, so we can convert between all address types using it. But we need at least one valid Bech32 address first to convert from (which is why …
> feat(rpc): Allowing for `ValAddr` on `/transfer` and `/balance/$ADDRESS`

- nodebuilder/fraud/module.go
It's not nessesary to invoke `new(fraud.Subscriber)` in the Module creation because this instances of fraud.Subscriber is not used anywhere. According to our logic it should be passed to [OnProof](https://github.com/celestiaorg/celestia-node/blob/b95d48647a3a1da2de7a69c4a071ae85ef9159e3/fraud/proof.go#L52) and OnProof is invoked from [Lifecycle](https://github.com/celestiaorg/celestia-node/blob/b95d48647a3a1da2de7a69c4a071ae85ef9159e3/nodebuilder/fraud/fraud.go#L74) that receives fraud.Service as an input parameter.
> bugfix(nodebuilder/fraud): remove fraud.Subscriber from module

- nodebuilder/tests/reconstruct_test.go
The main root cause was in timeout duration.
Discovery takes 7-10 seconds. 
` reconstruct_test.go:160: discovery done after: 7.190291886`
Syncing blocks ~15
`sync/sync.go:197	finished syncing	{"from": 19, "to": 58, "elapsed time": 15.208134365}`
So, sometimes the 30 Seconds timeout was not enough to discover full node, sync headers and reconstruct 20 headers.
```
reconstruct_test.go:181: fill blocks finished
reconstruct_test.go:170: retreiving header with height 1
reconstruct_test.go:174: retreiving header with height 1 finished in 0.000001
reconstruct_test.go:170: retreiving header with height 2
reconstruct_test.go:174: retreiving header with height 2 finished in 0.000000
reconstruct_test.go:170: retreiving header with height 3
reconstruct_test.go:170: retreiving header with height 4 …
```
> bugfix: fix flakiness in TestFullReconstructFromLights

- .github/workflows/markdown-lint.yml
Ref https://github.com/celestiaorg/celestia-app/pull/794
Apparently quotes are needed if you have some subdirectory structure. Note that official examples use quotes: https://github.com/igorshubovych/markdownlint-cli/tree/f891b45ee50f621330160e5dcfa47435ac2220f8#globbing-examples
> Fix markdown lint workflow to run on directories

- .github/workflows/go-ci.yml
Actions for unit test has been running integration tests as well since #997 was merged, fixing here.
> fix (.github/workflows): Skip over integration tests in unit test action

- README.md
This doc was moved in https://github.com/celestiaorg/celestia-node/commit/a0232625250c9128c0d6fa74d27329c113603138
> fix: README link for header doc

- nodebuilder/settings.go
- nodebuilder/state/core.go
- nodebuilder/state/module.go
#1083 introduced `state.WithMetrics` that takes a `CoreAccessor` instead of the `Module`, so the DI currently fails to build.  This fixes the DI for nodes running metrics
> fix(state): returning CoreAccessor from nodebuilder for state.WithMetrics

- nodebuilder/state/service.go
- state/core_access.go
Getting address from node's account
This is a handy feature that testground's tests are already utilising in upcoming PFD test-plans 
Tested on this PR https://github.com/celestiaorg/test-infra/pull/87
Ref: 
#1056 #506 
External Ref: https://github.com/celestiaorg/test-infra/issues/33
P.S. I've prettified the code-base with `golines`. Let me know if this should be opted out to a different PR
> feat(nodebuilder): add AccountAddress to state's Module

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/pb/extended_header_request.pb.go
- header/p2p/pb/extended_header_request.proto
- header/p2p/server.go
Let's the party begins 😅 .
This is a first part of changes requested in https://github.com/celestiaorg/celestia-node/issues/497. 
Current PR resolves:
* #635 
* #197
* #366 (n/a)
> feat!(header/p2p): add deadlines on stream and rework proto

- nodebuilder/header/header.go
- nodebuilder/header/module.go
Here we solve two issues:
* Tests and red CI without downgrading FX while keeping node modules construction order independent
*  The recent FX update(to 1.18.2) changed the order of fx.Invoke executions and uncovered an issue with order between connection to a trusted peer and joining the header-sub topic. Connection to the trusted peer happens implicitly during store initialization, and initialization happens during Invoke, hence it's ordering was changed after the update.
* Node constructor free from network calls
* store.Init does a network call, and it was invoked during node construction. Now, we do this only during the Start, where network calls are acceptable.
Store initialization during the Start lifecycle goes after the Syncer is started, causing Syncer to error, as it requires …
> fix(nodebuider/header): initialize Store during start lifecycle instead of fx.Invoke

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/server.go
Resolves:
* https://github.com/celestiaorg/celestia-node/issues/980
* https://github.com/celestiaorg/celestia-node/issues/1019
> header/p2p: request head from multiple peers

- .github/workflows/ci_release.yml
Small update to include running the CI on versioned tags, i.e. any tag starting with a `v`. 
This allows for tagging release candidates manually.
> .github: add triggering on versioned tags

- share/ipld/namespace_hasher.go
> refactor(share/ipld): Use consts for node type determination

- share/ipld/namespace_hasher.go
- share/ipld/namespace_hasher_test.go
@walldiss Does this look okay to you?
The nodes sync successfully now, even without explicitly handling the legacy case.
> fix: returning nil sum when hasher receives data with incorrect length

- nodebuilder/node_test.go
- state/core_access.go
- state/core_access_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1248 and https://github.com/celestiaorg/celestia-node/issues/1246
> fix(state): `CoreAccessor` manages its own context

- state/core_access.go
> fix: restricting PFD metrics to successful PFDs

- nodebuilder/tests/swamp/swamp.go
Before: PASS: TestFraudProofSyncing (7.57s)
After: PASS: TestFraudProofSyncing (5.93s)
@evan-forbes, any clue why it takes so long to generate accounts?
> chore: gen less acounts to reduce test execution times

- core/fetcher.go
Self-explanatory (found by @jbowen93)
> refactor(core/fetcher): Improve error messages for fetcher methods

- das/daser_test.go
- fraud/requester.go
- fraud/service.go
- fraud/service_test.go
- fraud/sync.go
- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/server.go
- nodebuilder/fraud/fraud.go
- nodebuilder/header/header.go
- nodebuilder/header/module.go
> fix: removing protocolIDs from global namespace in p2p and fraud

- nodebuilder/init.go
After conversation with @jbowen93 , we decided to allow using custom networks over an already-initialised node store. 
The issue this was originally attempting to prevent is accidental corruption of chain data in the case that a user accidentally leaves their environment variable set up and connects to another network over an old node store.
This issue is actually currently prevented thanks to #1073 extending the node store name with the network name.
> refactor(nodebuilder): Allow custom networks to work over already-initialised store

- share/eds/eds_test.go
- share/test_helpers.go
> feat(blocksync): Benchmarks for `ReadEDS` and `WriteEDS`

- Makefile
I was getting the following errors on `v0.2.6` of `go-acc`. Updating to latest fixed these errors. 
```
celestia-node % make cover
--> Generating Code Coverage
go install github.com/ory/go-acc@v0.2.6
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/zsyscall_darwin_amd64.go:28:3 …
```
> Makefile: update go-acc version due to errors and new release

- das/coordinator.go
- das/coordinator_test.go
- das/daser.go
- das/daser_test.go
- das/options.go
- das/state.go
- nodebuilder/config.go
- nodebuilder/das/config.go
- nodebuilder/das/daser.go
- nodebuilder/das/module.go
- nodebuilder/das/opts.go
- nodebuilder/module.go
- nodebuilder/settings.go
The DAS module is currently reliant on default constant global variables acting as configuration variables.
This makes changing configuration values for the DAS module non-trivial, as it requires code changes and binary re-building.
In this PR, we refactor the global configuration variables used in the DAS module to use the functional options pattern, which will trivialize the process of configuring a Celestia node.
#1063 
#709 
The `das` package is now configurable using a set of functional options, namely:
```
WithSamplingRange(uint64)
WithConcurrencyLimit(int)
WithBackgroundStoreInterval(time.Duration)
WithPrioritySizeQueue(int)
WithGenesisHeight)
```
This allows the `das` package to be configured with values other than the default parameters defined in `das/options.go:29`
An example …
> refactor(daser): use functional options pattern to configure daser

- api/gateway/server.go
- api/gateway/server_test.go
- api/rpc/server.go
- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- nodebuilder/config.go
- nodebuilder/gateway/config.go
- nodebuilder/gateway/flags.go
- nodebuilder/gateway/gateway.go
- nodebuilder/gateway/module.go
- nodebuilder/gateway/rpc.go
- nodebuilder/module.go
- nodebuilder/node.go
It adds the gateway back onto the node (closes #1182) with it's own config, disabled by default, which is activated by the flag `--gateway` (closes #1183).
> feat(gateway): reenabling gateway, adding flag to enable

- share/ipld/nmt.go
> refactor(share/ipld): Use `NamespaceSize` var for consistency

- nodebuilder/das/daser.go
- nodebuilder/das/mocks/api.go
- nodebuilder/das/module.go
- nodebuilder/fraud/mocks/api.go
- nodebuilder/header/mocks/api.go
- nodebuilder/node.go
- nodebuilder/node_bridge_test.go
- nodebuilder/rpc/module.go
- nodebuilder/rpc/rpc.go
- nodebuilder/share/mocks/api.go
- nodebuilder/state/mocks/api.go
> feat(rpc): adding daser stub for friendly API error

- api/gateway/server.go
- api/gateway/server_test.go
- api/rpc/server.go
- api/rpc_test.go
- nodebuilder/testing.go
Closes #1286
This is mainly a fix for test flakiness.
> fix(gateway): switch to separate Listen/Serve

- nodebuilder/fraud/module.go
- nodebuilder/gateway/flags.go
- nodebuilder/gateway/module.go
- nodebuilder/header/module.go
- nodebuilder/p2p/module.go
- nodebuilder/p2p/routing.go
- nodebuilder/state/module.go
> refactor(nodebuilder): Logger names in subpackages to `constructor/<subpkg>`

- nodebuilder/node_bridge_test.go
Fixes issue with this test not using in-memory keyring.
> fix(nodebuilder): Use test node for tests instead of New

- share/eds/retriever.go
- share/eds/retriever_quadrant.go
The latest rsmt2d version allows us to set cells/share directly into the imported square. Hence, we can avoid using flattened slices and the complexity it introduces when calculating position or index to set a share. Also, we now avoid reimporting the square on each repair retry and overall optimizing the whole process.
Closes #824 
Blocked on https://github.com/celestiaorg/rsmt2d/issues/127 and https://github.com/celestiaorg/rsmt2d/pull/128
> refactor(ipld): use Set/GetCell API from rstm2d

- nodebuilder/das/opts.go
This PR fixes the `das.WithMetrics` fx invokation which enables metrics collection in the DASer module.
Negligeable
@derrandz
> fix(das): Correct `WithMetrics` fx Invocation

- nodebuilder/p2p/flags.go
- nodebuilder/p2p/flags_test.go
- nodebuilder/p2p/network.go
* Allows users to specify the network alias rather than the actual value of the network ID when passing `--p2p.network`
* Fails out on init if invalid network specified via `--p2p.network`
Supersedes https://github.com/celestiaorg/celestia-node/pull/1353
Ensures https://github.com/celestiaorg/docs/pull/304 does not need to happen.
> refactor(nodebuilder/p2p): Allow specifying network alias with `--p2p.network` flag

- state/core_access.go
PFD submissions collect metrics. I swapped the arguments to an && condition that ensures a struct is only accessed if the err != nil.
> fix(coreaccessor): pfd submission nil check

- share/eds/byzantine/bad_encoding.go
- share/eds/byzantine/bad_encoding_test.go
Fixes https://github.com/celestiaorg/celestia-node/issues/1355
Adds a test for a false positive for BEFPs.
> fix(eds/byzantine): trim `NMTWrapper`'s namespace during BEFP validation

- nodebuilder/p2p/network.go
we changed the codec in v0.5.0-rc3, and unless we want to support the old codec forever, we have to reset the block data and therefore increment the chain-id for arabica.
> chore!(nodebuilder/p2p): increment the chain-id for arabica

- das/daser.go
- das/daser_test.go
- das/state.go
Exposes WaitCatchUp from DASer to subscribe to catchup event from external caller. Requested for https://github.com/celestiaorg/celestia-node/pull/1341
> feat(das): make WaitCatchUp public

- Makefile
The command `make openrpc-gen` was pointing to the incorrect command path, and using the deprecated `daser` path.
- ~~New and updated code has appropriate documentation~~ NA
- ~~New and updated code has new and/or updated testing~~ NA
- ~~Visual proof for any user facing features like CLI or documentation updates~~ NA
- ~~Linked issues closed with keywords~~ NA
> fix: pointing `make openrpc-gen` to the correct cmd

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/options.go
- header/p2p/server.go
- header/p2p/server_test.go
- header/p2p/session.go
- nodebuilder/config.go
- nodebuilder/header/config.go
- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
> feat(header/p2p): add functional params for header/p2p package

- header/p2p/exchange.go
main isn't building due to a change in the api of a dependency and a recent PR. this PR adds an arbitrary number to fix that. 
NOTE: I don't actually know what number we should put here. 3 seemed like a good number, so I used it.
> fix(header): add extra arg to fix build

- nodebuilder/module.go
- nodebuilder/node/type.go
- nodebuilder/share/module.go
- nodebuilder/testing.go
- nodebuilder/tests/swamp/swamp.go
- share/eds/store.go
This PR is based on #1232 and closes #1114. It supplies bridge and full nodes with an instance of EDSStore. The base path is provided by FX from `nodebuilder.Store` through a string alias.
It also fixes a bug that occurred when initializing the eds.Store twice, where the directories already existed. I have swapped MkDir out for MkDirAll, which does not err if the directory already exists.
No test modifications are done, but the Lifecycle tests would fail if it were to fail building or not be able to provide the EDSStore to the nodes.
> feat(share): Supplying `eds.Store` to bridge and full nodes

- nodebuilder/p2p/p2p.go
- share/eds/store.go
- share/eds/store_test.go
This PR implements a goroutine that runs during the lifetime of the `EDSStore`, which calls `dgstr.GC` periodically. This garbage collection cleans up shards from transient storage that are available but inactive or errored.
The PR is based on #1232 and closes #1116.
> feat(share): Periodic GC over EDSStore

- cmd/cel-key/node_types.go
Users will have to specify `--p2p.network` instead of `--node.network` in order to direct the cel-key utility to the correct repository -- default network is still `arabica` alias.
> refactor(cmd/cel-key): Unify flag names `--node.network` -> `--p2p.network`

- .gitignore
- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/celestia/util.go
Closes #1331
When I compile cel-key, I see the binary is output to root, then I guess 'celestia' in the .igitigonre means the compiled binary, however it's moved to another place and not in root now.
> Extract common parsing logic into single function.

- share/availability/discovery/set.go
Improvement for https://github.com/celestiaorg/celestia-node/pull/1451
Notify multiple readers instead of one.
> improvement(share/discovery): send peer to multiple readers

- core/client_test.go
- core/fetcher_test.go
- core/testing.go
- nodebuilder/node_bridge_test.go
Fixes #1365
Replace StartTestClient with StartTestCoreWithApp within tests
> core: Deprecate/remove StartTestClient in favour of StartTestCoreWithApp

- nodebuilder/p2p/network.go
Based on #1434 
Switches default network from arabica to mocha
> refactor(nodebuilder/p2p): Switch default network from `arabica` to `mocha`

- api/gateway/state.go
- docs/adr/adr-009-public-api.md
- nodebuilder/state/mocks/api.go
- nodebuilder/state/state.go
- state/core_access.go
Adding fee parameter to `CoreAccessor` operations.
All transaction endpoints now have a "fee" key needed in the JSON request. An example value for this can be 2000. This includes the following endpoints:
- SubmitPayForData
- Transfer
- Delegate
- BeginRedelegate
- Undelegate
- CancelUnbondingDelegation
After this change, a new field is added to the json requests in the gateway:
`{oldRequest..., "fee": 2000}`
> feat(state)!: Adding fee parameter to `CoreAccessor` operations

- .markdownlint.yaml
Don't see why we would disallow having the same name shared between multiple headers. Got this from working on #1326
> chore(markdownlint): disable 'Multiple headings with the same content' rule

- go.mod
- nodebuilder/p2p/host.go
- nodebuilder/p2p/mocks/api.go
- nodebuilder/p2p/module.go
- nodebuilder/p2p/p2p.go
- nodebuilder/p2p/p2p_test.go
This is a temporary fix for bootstrappers. Infinite Limits seem to be buggy. The proper fix is to update to the latest version of libp2p
> fix(node/p2p)!: remove resource manager and it's API

- header/p2p/exchange.go
- header/p2p/options.go
- header/p2p/server.go
- header/store/options.go
- header/store/store.go
- nodebuilder/header/config.go
- nodebuilder/header/module.go
Return a struct instead of a pointer to a struct in params creation
> fix: return a struct instead of a pointer in params creation

- share/eds/eds.go
- share/ipld/namespace_hasher_test.go
- share/ipld/nmt.go
- share/ipld/test_helpers.go
This PR removes usage of nmt's defaultHasher to allow for concurrent writingSessions.
- ~~New and updated code has new and/or updated testing~~
- ~~Visual proof for any user facing features like CLI or documentation updates~~
- ~~Linked issues closed with keywords~~
> fix(eds): WriteEDS thread safety for concurrent writingSessions

- api/rpc/permissions/permissions.go
- api/rpc/server.go
- go.mod
- go.sum
- nodebuilder/node/auth.go
- nodebuilder/node/module.go
- nodebuilder/rpc/constructors.go
Related to #1187 
**This PR is based on #1313** 
**It implements:** 
* providing a new JWT secret from the `nodebuilder/node` module to both the node module and the rpc server.
* auth middleware for the `rpc.Server` that verifies the given token with the server's secret
In a follow-up PR will come the ability to create an rpc client with elevated permissions (this branch restricts client access to read-only API methods).
> feat(api/rpc): Implement auth middleware on `Server`

- cmd/celestia/main.go
Fix https://github.com/celestiaorg/celestia-node/issues/1504
Now it looks like:
```
$ celestia --help
____      __          __  _
/ ____/__  / /__  _____/ /_(_)___ _
/ /   / _ \/ / _ \/ ___/ __/ / __  /
/ /___/  __/ /  __(__  ) /_/ / /_/ /
\____/\___/_/\___/____/\__/_/\__,_/
Usage:
celestia [command]
Available Commands:
bridge      Manage your Bridge node
full        Manage your Full node
light       Manage your Light node
version     Show information about the current binary build
Flags:
-h, --help   help for celestia
Additional help topics:
celestia         
Use "celestia [command] --help" for more information about a command.
```
> fix: correct spacing of celestia banner

- .gitignore
Closes #1442 
Limit some pattern to root folder.
Remove duplicated pattern.
> github/CI: Fix over kill of '.gitignore'.

- cmd/cel-key/node_types.go
- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/flags.go
- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
Allows users to pass the network alias instead of the full network name to the `cel-key` utility as is done with the celestia binary. 
We allow networks other than the "valid" networks to be specified with the cel-key utility since it can be used for testing, but it will print a warning.
> improvement(cel-key): Network alias check for `--p2p.network` flag

- api/rpc/client/client.go
- api/rpc/permissions/permissions.go
- api/rpc/perms/permissions.go
- api/rpc/server.go
- api/rpc_test.go
- nodebuilder/node/mocks/api.go
Resolves #1187
* Adds `NewClientWithPerms` which takes a token and adds it to the request header for rpc calls
* Adds tests for authenticated methods
> feat(api/client): Implement RPC client authentication

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/peer_tracker.go
- header/p2p/peer_tracker_test.go
- nodebuilder/header/constructors.go
- nodebuilder/header/module_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1531
> feat(header|p2p): add blacklisting to peerTracker

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/peer_stats.go
- header/p2p/session.go
- nodebuilder/header/module_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1406
> feat(header/p2p)!: implement retry mechanism for header/p2p session

- cmd/auth.go
- cmd/celestia/auth.go
- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- docs/adr/adr-009-public-api.md
- nodebuilder/node/auth.go
- nodebuilder/p2p/p2p.go
- nodebuilder/p2p/p2p_test.go
Resolves #1187
This PR adds an `auth` subcommand to `bridge`, `full` and `light` nodes. 
Intended use: after a node is already initialized and started, a user can use the CLI to generate a signed token with some given perms via the `auth` cmd.
Example:
```
celestia bridge auth admin 
```
The above command outputs a signed JWT token with admin permissions that a user can use with `client.NewClient()` to access admin-level methods on the node.
Reference [this commit](https://github.com/celestiaorg/celestia-node/pull/1429/commits/2c833bca89790ff5503822875751f3330207b87f) for the actual diff.
> feat(cmd/celestia): Add `auth` subcommand to bridge, full and light

- docs/adr/adr-009-public-api.md
- nodebuilder/p2p/mocks/api.go
- nodebuilder/p2p/p2p.go
- nodebuilder/p2p/p2p_test.go
Based on #1429 
Adds an error as a return value for all methods as it is needed for elevated permission methods.
> refactor(nodebuilder/p2p): Add errors for all methods

- nodebuilder/header/module.go
Not needed anymore after [#initStore](https://github.com/celestiaorg/celestia-node/pull/1515)
> chore(modheader): don't ignore Syncer error on start

- header/p2p/exchange.go
- header/p2p/peer_tracker.go
We need to connect to trusted peers and kick off various protocols to start talking to them. In the past, a node was always connected to trusted peers to get headers from them. As from recent improvements to header-ex, we now only rely on trusted peers for initialization. Hence, if a node is already initialized, it won't contact go to connect to trusted peers and this commit fixes this.
This was found during fixing `no trusted peers` issue in swamp tests in https://github.com/celestiaorg/celestia-node/pull/1556
> fix(header/p2p): preconnect trusted peers on header-ex start

- go.mod
- go.sum
- nodebuilder/node/mocks/api.go
- share/ipld/namespace_hasher.go
- share/ipld/namespace_hasher_test.go
In preparation for the full libp2p update
* New version of go-multihash has a stricter rules on passed hash.Hash implementation and check size
* Previously, we returned 32 as what underlying sha256 returns, but in fact Sum results in 48, thus the change
* Removes old ugly 'if' and supporting tests that came as solution for go-multihash omitting error check after Write
* Makes namespaceHasher fully compliant with hash.Hash and it can now be reused anywhere and ideally moved to NMT lib
LI or documentation updates
> fix(ipld): Make namespaceHasher fully implement hash.Hash and update go-multihash

- share/ipld/get.go
- share/ipld/proof.go
Fix the order of inclusion proof nodes returned by `GetSharesByNamespace` to be possible incorrect.
> fix(share): order proof nodes by depth before returning

- nodebuilder/p2p/config.go
> fix: use udp/quic instead of tcp/quic in NoAnnounceAddress

- nodebuilder/tests/fraud_test.go
Previously it succeeded, but the FP was actually transmitted through PubSub and not fraud syncing.
It also makes the test discovery independent.
> tests(swamp): correct fraud syncing test

- header/interface.go
- header/sync/sync.go
We need to fix this earlier to fix fraud tests in #1555
Closes https://github.com/celestiaorg/celestia-node/issues/1386
> fix(header): don't stop Subscriber in Syncer and remove Stop from interface

- share/p2p/shrexeds/client.go
- share/p2p/shrexeds/exchange_test.go
This PR removes the retry logic from the shrex/eds client and adds test skipping to test cases that can either be refactored or removed when implementing #1489. This logic is being removed so that ShrexGetter can handle retry/round-robin logic for both the shrex/eds and shrex/nd clients.
> refactor(shrexeds): removing retry logic from client

- fraud/sync.go
Fixes a rare data race found in https://github.com/celestiaorg/celestia-node/pull/1596
```
WARNING: DATA RACE
Write at 0x00c0066ef4a0 by goroutine 6416:
github.com/celestiaorg/celestia-node/fraud.(*ProofService).syncFraudProofs()
/home/runner/work/celestia-node/celestia-node/fraud/sync.go:50 +0x784
github.com/celestiaorg/celestia-node/fraud.(*ProofService).Start.func1()
/home/runner/work/celestia-node/celestia-node/fraud/service.go:90 +0x58
Previous read at 0x00c0066ef4a0 by goroutine 6467:
github.com/celestiaorg/celestia-node/fraud.(*ProofService).syncFraudProofs.func1()
/home/runner/work/celestia-node/celestia-node/fraud/sync.go:82 +0x638
github.com/celestiaorg/celestia-node/fraud.(*ProofService).syncFraudProofs.func3()
/home/runner/work/celestia-node/celestia-node/fraud/sync.go:107 …
```
> fix(fraud): fix race by using correct peer id in log statement

- header/p2p/options.go
- header/p2p/server.go
- header/store/store.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
This PR introduces server-side context deadlines for **all** requests down to store with a config parameter for the server `RequestTimeout`
> improvement(header/p2p): Implement context deadline on requests to store inside server

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/helpers.go
- header/p2p/options.go
- header/p2p/peer_stats.go
- header/p2p/peer_stats_test.go
- header/p2p/server.go
- header/p2p/session.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1607
> fix(header/p2p): add peerScore decreasing in case of failed request

- das/state.go
- das/state_test.go
DASer `waitCatchUp` method has a data race for catchUpDoneCh pointer. Pointer needs to be swapped gracefully. 
Would occur only if user was fortunate enough to call `waitCatchUp` in the span of time the pointer was being swapped.
> fix(daser) replace catchUpDoneCh channel gracefuly 

- share/availability/discovery/discovery.go
- share/availability/full/availability.go
- share/availability/light/availability.go
Closes https://github.com/celestiaorg/celestia-node/issues/1613
Test will be implemented in a scope of https://github.com/celestiaorg/celestia-node/issues/1612
> feat(share/discovery): Ensure only one instance of EnsurePeers is running

- core/listener.go
Fixes a bug found in implementation of datahash broadcasting in bridge nodes -- now bridge nodes will only broadcast a hash if its connected core node is synced up.
> fix(core/listener): Only broadcast datahash if core node is not syncing

- libs/header/p2p/exchange.go
- libs/header/p2p/options.go
Anyway, we should have a retry mechanism for requests here(but long term, it should be a better than this implementation), and also, this seems to be helping with #1623 during the first initialization of a node.
> fix(header/p2p): add trivial retrying for trustedPeer requested

- share/availability/test/corrupt_data.go
Fixes a flake in TestNamespaceHasher_CorruptedData that occurs when we try to hash an empty byte array.
> fix: flake in TestNamespaceHasher_CorruptedData

- das/metrics.go
- das/worker.go
This (not very elegantly) fixes an issue with tracking `totalSampled` inside the DASer which results in 2x the amount of sampled headers as were actually sampled. 
From @walldiss: 
```
It happens because DASer does not call Sampling directly, instead it calls SharesAvailable that ensures that block is sampled. Under the hood, SharesAvailable will check the internal cache and if it hits, it will return immediately. This logic was utilised in DASer design, to simplify independent tracking of recent headers sampling. So sampling recent headers could call SharesAvailable twice: first by recent sampling job and by catchup job later. It was done to simplify already complex DASer logic.
```
Eventually, `totalSampled` should probably be tracked inside `CacheAvailability` as that's the only place …
> refactor(das): Don't increment totalSampled if header `isRecent`

- share/p2p/peers/manager.go
- share/p2p/peers/manager_test.go
This fix resolves an issue where peers who would broadcast hashes via shrex-sub that were already retrieved by the node would get blacklisted. This happened because after retrieval of a given hash, the `syncPool` corresponding to the given hash gets deleted, so when a delayed peer would broadcast the same hash after retrieval, the manager would create a new pool that goes unvalidated since the header was already received via header-sub, causing the delayed peers in the recreated pool to get blacklisted. 
The solution is to do a soft-delete of the pool such that delayed peers are GC'd rather than blacklisted.
> fix(share/shrex/peer_manager): peer manager needs to do soft delete on synced pool instead of hard one

- nodebuilder/config.go
- nodebuilder/p2p/config.go
Turns on peer exchange for bridges and fulls for better connectivity guarantees.
> improvement(nodebuilder/p2p): Turn on PEX by default for bridges and fulls

- core/listener.go
Increases the chances that the EDS hash will arrive before the `ExtendedHeader` so that by the time `SharesAvailable` is called on the `ExtendedHeader` by recipient peer, it is more likely to have more peers available for the given eds hash.
> refactor(core): `CoreListener` broadcasts EDS hash before it broadcasts `ExtendedHeader`

- nodebuilder/gateway/module.go
Since the gateway's endpoints are not authenticated and it is disabled by default, we should warn users to use the gateway with caution if gateway is enabled.
Closes #1752
> feat(nodebuilder/gateway): Add warn log if gateway is enabled so users know to use with caution

- nodebuilder/share/constructors.go
- share/availability/full/availability.go
- share/getters/shrex.go
- share/getters/store.go
- share/p2p/peers/manager.go
- share/p2p/shrexeds/options.go
- share/p2p/shrexnd/options.go
Closes #1755 
Also, cleans up error logs. Before:
```
2023-02-16T14:22:10.256+0100	ERROR	share/full	full/availability.go:62	availability validation failed	{“root”: “9bVWFLfSHJwY9Fotfkdb//8i9GcQWESAtX3cGIFNYnI=“, “err”: “getter/store: failed to retrieve eds: failed to get CAR file: failed to get accessor: failed to initialize shard acquisition: F5B55614B7D21C9C18F45A2D7E475BFFFF22F46710584480B57DDC18814D6272: shard not found; getter/tee: failed to store eds: failed to write EDS to file: share: creating eds writer: committing inner nodes to the dag: before batch commit: context deadline exceeded; getter/ipld: failed to retrieve eds: context deadline exceeded”, “errCauses”: [{“error”: “getter/store: failed to retrieve eds: failed to get CAR file: failed to get accessor: failed to initialize …
```
> refactor(share/getters): cleaning up error logs, wrapping cascadegetter with teegetter

- das/daser.go
- nodebuilder/tests/fraud_test.go
- share/availability/full/availability.go
Getters returning context errors to the `CascadeGetter` instance were appended to a multierr. This meant that `ErrByzantine` errors were short-circuited in the daser, returning the context error instead of the `ErrByzantine`.
> fix(das | share): handle `ErrByzantine` from `multierr`s when found with `context.Canceled`

- nodebuilder/share/constructors.go
- nodebuilder/share/module.go
Enables use of `GetSharesByNamespace` and `GetEDS` over shrex for LNs.
> feat(share): allow LNs to GetSharesByNamespace and GetEDS over shrex

- nodebuilder/share/constructors.go
- nodebuilder/share/module.go
This PR reverts providing shrex-getter and its associated components to light nodes as they are both unnecessary for now and are buggy, causing the following error to occur: 
light node tries to sample a recent header and fails on the first try with 
```
"PT2agmOhBwBuDZu++Vq+LGcATmrI9UZbJKEsvlHKlls=", "err": "getter/shrex: GetShare is not supported; getter/ipld: failed to retrieve share: promise channel was closed", "errCauses": [{"error": "getter/shrex: GetShare is not supported"}, {"error": "getter/ipld: failed to retrieve share: **promise channel was closed**"}]} 
```
but succeeds on a second try when the `catchUp` routine inside the DASer samples once again over that height.
For now, we will remove this feature (which will only impact the "speed" of the RPC call for requesting data by …
> fix(nodebuilder/share): Revert providing `shrex.Getter` and its associated components to light node

- share/eds/retriever.go
As we now store EDS in TeeGetter, we don't need to store EDS during reconstruction
> fix(eds): don't commit reconstructed EDS in Retriever

- nodebuilder/share/module.go
- share/availability/discovery/discovery.go
- share/p2p/peers/manager.go
- share/p2p/peers/manager_test.go
Extracts `ensurePeers` lifecycle management from `peer.Manager`, and privatizes `ensurePeers`.
As All the node types call it, so we can do it by default.
> refactor(share/p2p): Discovery controls `ensurePeers` lifecycle

- nodebuilder/share/constructors.go
- nodebuilder/share/module.go
Bridge does not need: 
* shrexeds.Client
* shrexnd.Client
* *shrex.Getter
* peer.Manager
Bridge and Lights will also spawn EnsurePeers lifecycle from nodebuilder instead (as they don't use peer.Manager yet)
> fix(nodebuilder/share): Only provide necessary components to Bridge

- fraud/gossip_score.go
- libs/header/p2p/gossip_score.go
- nodebuilder/header/mocks/api.go
- nodebuilder/p2p/pubsub.go
- share/p2p/shrexsub/pubsub.go
Closes #1330 
Ideally, we should test how our network performance under these new parameters before merging. However, the parameters here do not substantially diverge from parameters from Prysm and Filecoin, so it is safe to go without it.
Some refs:
* https://gist.github.com/blacktemplar/5c1862cb3f0e32a1a7fb0b25e79e6e2c
* https://github.com/ethereum-optimism/optimism/blob/develop/op-node/p2p/gossip.go
* https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/p2p/gossip_scoring_params.go
* https://github.com/filecoin-project/lotus/blob/master/node/modules/lp2p/pubsub.go
TODO:
* Add topic params for FraudSub
* FraudSub should have better resiliency to eclipse attacks and do flood publish. However, it's not possible to configure this for a specific topic in PubSub at this point.
* …
> feat(modp2p): tune GossipSub

- das/checkpoint.go
- das/coordinator.go
- das/daser_test.go
- das/metrics.go
- das/state.go
- das/stats.go
- das/worker.go
- Prevent DASer from doing same job twice in case of recent sampling is run on synced node.
- Log recent jobs with info level
> feat(das): Don't sample recent jobs twice

- nodebuilder/p2p/pubsub.go
- share/availability/full/availability.go
- share/availability/full/testing.go
> perf(share/full): avoid loading EDS for subsequent availability checks

- libs/header/sync/sync.go
- libs/header/sync/sync_test.go
Made a mistake and calculated `to.Height` incorrectly
> fix(libs/header/syncer): fix bounds during syncing

- share/availability/full/reconstruction_test.go
- share/getters/ipld.go
Introduction of cascade getter created a case where ctx is created just before call to `ipld.GetShare` and this local context is canceled right after the call. 
It turns out ipld.Session is created with ctx from first call that created it, instead of parent context from Availability. Session context should common parent context from ShareAvailable call, instead of local single request call.
> fix(share/ipld): use parent context for ipld session instead of request context

- Makefile
Running the command make lint without installed import-reviser will fail because of `command not found` but it will try to execute it against every file. We should stop the iteration once we get an error.
> fix(Makefile): exit if an error appears

- libs/header/p2p/session.go
- libs/header/p2p/session_test.go
Added extra condition to verify the adjacency-only in headers from the received range.
> bugfix(libs/header/p2p): fix range validation in session

- .github/workflows/issue-label-automation.yml
Rene was interested in external issue labels, was easier to just do it then explain it in slack :-)
> Extend label automation to add external label

- .github/workflows/issue-label-automation.yml
@Wondertan asked for pr labels, so he shall get pr labels. 
This extends the label automation for issues so that it also adds the `external` label to prs when the author is not part of the node team.
> .github: add labels to PRs

- cmd/cel-key/main.go
`KeysCommand` from the sdk is quite wonky in that it really only sets a keyring backend if the flag was `changed`, so this hack ensures we can properly set a default and that the default is `test`.
Resolves #1876
> fix(cmd/cel-key): Ensure keyring-backend is actually `test` by default

- libs/header/p2p/session.go
> fix(header/p2p): return on context to avoid ugly errors on stop

- libs/header/metrics.go
- libs/header/p2p/metrics.go
- nodebuilder/header/opts.go
- nodebuilder/settings.go
We accidentally stopped invoking header store head metrics [here](https://github.com/celestiaorg/celestia-node/pull/1794), but this fixes the issue.
> fix(nodebuilder): Also invoke header store head metrics

- go.mod
- go.sum
Memory leak fix https://github.com/libp2p/go-libp2p-pubsub/pull/528
> deps: update libp2p pubsub

- cmd/start.go
The repo remains unclosed if an error happens during node instantiation or lifecycle.
> fix(cmd): repo should be closed on defer

- nodebuilder/config.go
- nodebuilder/das/config.go
- nodebuilder/das/module_test.go
DASer default settings are based on IPLD only getters measurements. With introduction of blocksync to full nodes as main sampling protocol, value should to be revised. Shrex has much less roundtrips to obtain data, thus it is much better at utilising network bandwidth with fewer workers. Default DASer setting are now updated with relation to node type.
> refactor(nodebuilder/das): update default DASer setting 

- nodebuilder/store.go
Because the datastore is lazily loaded, we may close the Store and hit segfault
> fix(nodebuilder): fsStore check for nil Datastore

- libs/header/sync/sync_head.go
Pretty often, when you start a node for the first time, there is a warning complaining about an unsynced trusted peer, while we know that the peer is 100% synced. This warning also means we make an additional Head request for a bad reason. The fix is introducing a half-block time drift. I've tested it like 20 times and wasn't able to reproduce the warning. We also don't need to be super precise about head to worry about this additional half. The main goal here is to get the head quick enough after being a day or more out of sync.
> fix(header/sync): add drift to recency detection

- nodebuilder/share/module.go
Since light nodes no longer call a constructor that takes discovery, fx was never starting it.
This bug was caught by `TestBootstrapNodesFromBridgeNode`
> fix(share): enabling discovery on light nodes

- core/eds.go
- core/eds_test.go
- core/header_test.go
- header/header.go
A bug was caught on blockspacerace network that caused a data root mismatch between bridge nodes and core nodes because celestia-node incorrectly assumes an empty square if there are no transactions which is not the case as squares can contain only tail-padding even if no transactions land in the block itself. 
We also will now: 
* rely on using `data.SquareSize` from the block data for extending shares instead of calculating square size from `len(shares)`, and
* panic on data root mismatch
**Future considerations:**
* we need a fuzzing suite against our block extension mechanism that can generate all kinds of blocks (our integration testing doesn't test for edge cases like this.
* we need to audit the rest of the codebase to ensure we perform the same calculations over square size or …
> fix(core): Only assume empty square if reported square size is 1 *and* there are no txs

- nodebuilder/p2p/routing.go
Previously, only bootstrappers would use `dht.ModeServer`. Now it is enabled for all full and bridge nodes.
> fix(nodebuilder/p2p): all full and bridge nodes use `dht.ModeServer`

- api/docgen/openrpc.go
- api/rpc/version.go
- nodebuilder/node/admin.go
Introduce a version string to the API
Resolves #1345
> feat(nodebuilder/node | api): Version the API

- header/serde.go
This patch attempts to solve the header duplication issue on the ITN network by making the msg-id always equal to the header hash. As a byproduct, this also simplifies the logic for msg-id and avoids additional serialization rounds.
The only way to really check if this fixes #1958 is by updating the whole network
> perf(header): make HeaderSub msgid to be header hash

- core/exchange.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101a611fc]
goroutine 525 [running]:
github.com/celestiaorg/celestia-node/core.(*Exchange).getExtendedHeaderByHeight(0x140007b02a0, {0x103229658, 0x14008e568a0}, 0x0)
/Users/vladkrintisn/Celestia/celestia-node-original/core/exchange.go:141 +0x13c
github.com/celestiaorg/celestia-node/core.(*Exchange).Head(0x1049da160?, {0x103229658, 0x14008e568a0})
/Users/vladkrintisn/Celestia/celestia-node-original/core/exchange.go:131 +0x8c
github.com/celestiaorg/go-header/sync.(*syncGetter[...]).Head(0x14000021500, {0x103229658?, 0x14008e568a0})
/Users/vladkrintisn/go/pkg/mod/github.com/celestiaorg/go-header@v0.2.3/sync/sync_getter.go:29 +0x150 …
```
> fix(core/exchange): handle nil height pointer in log

- Dockerfile
When using a container and mounting a host folder to the default home (`/home/celestia`) in the container the `entrypoint.sh` gets overwritten.
This PR uses another path so this can't happen.
> fix: changing entrypoint path to /opt

- cmd/celestia/main.go
- cmd/celestia/rpc.go
Based on #3047. Beginning of the CLI.
Adds CLI over RPC. Format:
`celestia rpc [module] [method] [...args]`
`--auth TOKEN` flag sets the auth header (otherwise it reads it from the env, if not found, doesn't set auth)
`--url URL` sets request url, default localhost:26658
Most methods are easy to call. The args for `SubmitPayForBlob` are parsed specially, to improve UX. Other methods can be given special argument parsing rules for improved UX.
These special rules:
- The namespace ID can be encoded as either hex or base64
- The blob can be hex (`0x...`), base64 (`"..."`), or a normal string which will be encoded to base64 (`'"Hello There!"'`)
- `fee` doesn't need to be passed as a string as it normally would need to be, it is passed the same was as gasLim
examples of valid commands:
``` …
```
> feat(cmd): RPC over CLI

- share/eds/store.go
This PR replaces FSMount with FileMount, getting rid of the need for transients and avoiding unnecessary copying.
> fix(eds/share): replacing fsmount with filemount registration

- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
So far we know that connecting to bootstrappers in issues like #2006 fails with `dial backoff`. This context option always forces a dial. An experiment to know if it happens or not
> bypass backoff on dial

- nodebuilder/p2p/host.go
To facilitate the investigation of issues like #2006, I propose temporarily removing the RoutedHost as instead of returning a real dial error, it returns the `failed to find any peer in table`. We need to see what folks error with. So far, we know they fail with `dial backoff`(related https://github.com/libp2p/go-libp2p/issues/2220), but there could be other errors as well. To be included in the next release
Note that https://github.com/libp2p/go-libp2p/pull/2169 was merged more than a month ago but was not released yet, thus this temporal workaround. 
Originally, I wanted to merge it in the main, but then decide to put it into the testing #1985 branch.
> chore(modp2p): temporary remove routed host

- .github/dependabot.yml
The only issue I can see with this is if the dep upgrade leads to a breaking change for some reason. But in that case, we can manually change the label.
> ci(.github): Fix kind label for dependabot

- .github/dependabot.yml
- cmd/flags_misc.go
- go.mod
- go.sum
- nodebuilder/node/module.go
- nodebuilder/settings.go
Integrates [pyroscope](https://github.com/grafana/pyroscope) to the node. Adds three flags:
`--pyroscope`
`--pyroscope.tracing`
`--pyroscope.endpoint <ENDPOINT>` (default `http://localhost:4040`)
> feat: pyroscope integration

- README.md
- nodebuilder/store.go
While profiling with pyroscope, I noticed that while `badger/v2.(*DB).doWrites` stays constant for days, `badger/v2/y.(*WaterMark)` grows consistently over days.
`Watermark` helps in managing the memory usage and ensuring that certain thresholds are not exceeded, allowing the system to perform optimizations, such as compaction. Badger's garbage collection (GC) primarily targets the value log to free up space on disk, not in memory. The value log GC reclaims space by removing stale and obsolete data from the value log files, which are stored on disk. BUT: invoking the RunValueLogGC() method can have an _indirect_ impact on memory usage: value log GC occurs helps stabilize the growth of the WaterMark by preventing an excessive number of small value log files from accumulating. This can, in …
> fix: enabling badger gc

- api/gateway/state.go
- nodebuilder/node/admin.go
- nodebuilder/state/mocks/api.go
- nodebuilder/state/state.go
- state/core_access.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1840
> refactoring!(state): extend SubmitPayForBlob method

- .github/workflows/go-ci.yml
- Dockerfile
- README.md
- cmd/celestia/main.go
- cmd/start.go
- das/state_test.go
- das/worker.go
- go.mod
- header/headertest/testing.go
- nodebuilder/p2p/p2p_test.go
- nodebuilder/store.go
- nodebuilder/tests/swamp/swamp.go
- share/availability/full/availability_test.go
- share/availability/light/availability_test.go
- share/availability/test/corrupt_data.go
- share/eds/adapters_test.go
- share/eds/retriever_test.go
- share/get_test.go
- share/getters/cascade.go
- share/getters/cascade_test.go
- share/getters/shrex.go
- share/getters/shrex_test.go
- share/getters/utils_test.go
- share/ipld/nmt_test.go
- share/ipld/test_helpers.go
- share/p2p/peers/options.go
- share/test_helpers.go
- upgrade golang to 1.20
- replace multierr with new errors.Join
- replace deprecated math/rand Read with crypto/rand Read
> chore(deps): Upgrading to go 1.20

- share/p2p/shrexsub/pubsub.go
Return TTL back to the default value to avoid message duplication with the same msgID.
> refactoring(share/p2p): remove TTL in pubsub

- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/pubsub.go
- nodebuilder/tests/p2p_test.go
- nodebuilder/tests/reconstruct_test.go
- nodebuilder/tests/sync_test.go
Some hotfixes that fix swamp tests. Would like to understand why these fixes work before taking out of draft
> fix(swamp): fixing p2p_test and reconstruct_test

- blob/blob.go
Based on https://github.com/celestiaorg/celestia-node/pull/1963.
> feat(blob): introduce structure of blob

- logs/logs.go
Partially fix #1992.
I'm not sure this is a final fix, but at least let's disable the spam message first, or we could not see any real problem.
I let it run on blockspacerace for about 2 hours after modify, don't see any problem besides having to resync bridge again.
My bridge established no more than 20 connections, seems very low.
> chore(log): Suppress pubsub logs to WARN and net/identify to ERROR

- cmd/celestia/cmd_test.go
- cmd/celestia/rpc.go
Adds function signatures (excluding input context field, and output error field) to the RPC CLI autocompletions. Now the autocompletions for the methods looks like this:
> feat: include function signatures in rpc cli autocompletions

- cmd/flags_misc.go
This PR adds traces back to the pyroscope dashboard. I had them activated in the demo but for some reason it ended up deactivated in the original integration PR.
> fix: adding traces to pyroscope dashboard

- share/eds/inverted_index.go
- share/eds/inverted_index_test.go
- share/eds/store.go
This PR closes #2045, more specifically it closes #2057 . It introduces a custom inverted index plugin for the dagstore that is more compatible with our usage of badger as a storage backend, as well as more compatible with our usecase (we only need to index one shard per multihash).
The issue with the previous implementation was that many keys were being updated very often. This is probably due to padding, but there is more investigation necessary to determine why we have so many CIDs that appear in a lot of shards. Because we use badger as a storage backend, these updates were filling the value log, duplicating the value and adding an extra shard key every time. This resulted in explosive data usage on blockspacerace. At the time of writing, without this fix, the size of the store …
> fix(share/eds): add custom inverted index for badger as storage backend

- go.mod
- go.sum
Temporary fix until our fixes are merged upstream (and we can remove this replace). REQUIRES a full store reset.
Didnt know whether to make the PR chore(deps) or fix(eds/store)
Closes #2031
> fix(eds/store): use `Path` instead of `Host` in `FileMount` serialization/deserialization

- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/reset_store.go
- nodebuilder/init.go
- nodebuilder/store.go
Closes #109. Doesn't include any flags. Tested for all node types locally, works well.
> feat(cli): adding unsafe-reset-store command

- docker/entrypoint.sh
This change in the `entrypoint.sh` is for supporting docker compose setup in [rollkit/gm](https://github.com/rollkit/gm). See [here](https://github.com/rollkit/gm/pull/2).
When the `NODE_STORE` env variable is set, the init command specifies the `node.store` parameter to this environment variable.
This is non-breaking; if the variable is not set, nothing changes.
> feat: if NODE_STORE is set use it in custom init command

- cmd/flags_misc.go
- nodebuilder/init.go
- nodebuilder/p2p/config.go
- nodebuilder/p2p/host.go
- nodebuilder/p2p/metrics.go
- nodebuilder/p2p/module.go
- nodebuilder/p2p/module_test.go
- nodebuilder/p2p/resources.go
- nodebuilder/settings.go
- nodebuilder/store.go
* Introduces unit tests for p2p module builds to avoid such issues in future
* Reworks and cleans up resource manager registering with an actual fix
* Removes libp2p metrics config
* There is no need for users to configure Prometheus port because of future #2007 
* Moves `WithP2PMetrics` `nodebuilder` -> `modp2p`, because it needs access to private funcs
> fix(modp2p): fix libp2p metrics

- logs/logs.go
- share/p2p/shrexeds/client.go
- share/p2p/shrexeds/params.go
- share/p2p/shrexeds/server.go
- share/p2p/shrexnd/client.go
- share/p2p/shrexnd/server.go
Sort out logging level for shrex client / server logs.
DEBUG: unimportant errors, that doesn't affect logic
WARN: errors that could been induced by either party (client or server)
ERROR: node malfunction that needs operator attention
Since shrex client / server implementation propagates errors to the caller, default logging level should be set to ERROR, to reduce cognitive load on operator. Currently it is set in nodebuilder, but I would rather move default log level setting inside the package at some point.
> refactor(share/shrex): cleanup shrex logs

- nodebuilder/init.go
- nodebuilder/state/keyring.go
Resolves some confusion for users as previous behaviour would pick the first key in the keyring if no keyring.accname was specified and several keys were present in the keyring.
> refactor(nodebuilder): Use `my_celes_key` as default if no `--keyring.accname` is specified

- go.mod
- share/getters/shrex.go
- share/p2p/middleware.go
- share/p2p/peers/manager.go
- share/p2p/peers/pool.go
- share/p2p/shrexeds/client.go
- share/p2p/shrexeds/server.go
- share/p2p/shrexnd/client.go
- share/p2p/shrexnd/server.go
- Previously shrex-nd and shrex-eds error logs were indistinguishable, that lead to confusion of errors source. 
- add peerID to server logs
- Improve some other shrex logging.
Resolves https://github.com/celestiaorg/celestia-node/issues/2035
> refactor(share/shrex): improve shrex logging

- api/gateway/availability.go
- api/gateway/header.go
- api/gateway/share.go
If header was not in header store, gateway would hang until client context was canceled. PR allows gateway to return an error immediately in this case.
> refactor(api/gateway) return error from gateway if header is not synced yet

- api/gateway/util.go
Closes #2141 
writeError is called by almost all gateway endpoints. If a client makes a request for bad data, that is not an error for the server - but still useful as a debug log.
> fix(gateway): deescalating log in gateway's writeErr

- nodebuilder/node.go
Was originally for debugging purposes but actually solved the issue. The bootstrapper with a corrupted DAGstore state was not able to start quickly enough. 
Ideally, we should make this value configurable(https://github.com/celestiaorg/celestia-node/issues/2126)
> chore(nodebuilder): timeouts, errors and logs

- cmd/celestia/rpc.go
@jcstein Noticed that the json parsing stopped working for GetSharesByNamespace, this PR fixes that and also fixes a minor bug where only the first parameter was checked for JSON contents
> fix(cmd/rpc): parsing JSON for all parameters, and adding handler to GetSharesByNamespace

- nodebuilder/tests/reconstruct_test.go
- nodebuilder/tests/swamp/swamp.go
Fx requires trusted peers now so this fix is needed in the meantime to satisfy that.
Don't worry, these tests will be THOROUGHLY cleanussied in follow up PRs.
> fix(nodebuilder/tests): Add dummy trusted peers to satisfy fx

- logs/logs.go
- nodebuilder/node.go
Granular change descriptions are in comments
> fix(nodebuilder): fix error log and shut the fx

- share/availability/discovery/discovery.go
* Use only TTL provided by us.
* Don't wait 8hs upon error
* Increase the advertise timeout
> fix(share/discovery): fixes from Advertise logic audit

- share/p2p/shrexeds/client.go
Resolves item 7 on https://github.com/celestiaorg/celestia-node/issues/2176
> fix(share/p2p/shrexeds): return correct err on context error

- share/availability/discovery/discovery_test.go
Fix for error:
```
WARNING: DATA RACE
Read at 0x000001ead5c8 by goroutine 282:
github.com/celestiaorg/celestia-node/share/availability/discovery.(*Discovery).discoveryLoop()
/home/runner/work/celestia-node/celestia-node/share/availability/discovery/discovery.go:174 +0x59
github.com/celestiaorg/celestia-node/share/availability/discovery.(*Discovery).Start.func2()
/home/runner/work/celestia-node/celestia-node/share/availability/discovery/discovery.go:99 +0x58
Previous write at 0x000001ead5c8 by goroutine 172:
github.com/celestiaorg/celestia-node/share/availability/discovery.TestDiscovery()
/home/runner/work/celestia-node/celestia-node/share/availability/discovery/discovery_test.go:31 +0x14c
testing.tRunner()
/opt/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1576 +0x216 …
```
> fix(discovery): race in discovery tests

- das/state.go
In some rare cases when header height was not available for sampling and also picked up by both `recent` and `catchup` workers it could result in two parallel `retry` workers spawned for same header height. This PR fixes given case.
> fix(daser): do not spawn retry job twice

- das/checkpoint.go
- das/coordinator_test.go
- das/state.go
- das/worker.go
- share/p2p/metrics.go
If job was being handled by retry worker on node shutdown the retry backoff counter would be lost after restart.
> fix(daser):  persist retry count after restart

- share/availability/discovery/discovery.go
- share/availability/discovery/set.go
Self-explanatory.
The deadlock eventually blocks the disconnect event processing in Discovery, causing libp2p connection processing to stall. Was discovered via libp2p metrics
> fix(share/discovery): deadlock in limitedSet

- Makefile
Some docstrings and phony targets were outdated/incomplete. Fix.
> Fix Makefile docstrings and phony targets.

- header/header.go
Remove docstring for removed function `IsBefore`.
`IsBefore` was removed in #1304:
> `IsBefore` inlined, so we don't need to include this method in interface (it's a oneliner used once)
> Remove docstring for removed function IsBefore.

- share/availability/discovery/discovery.go
- share/p2p/shrexeds/server.go
- share/p2p/shrexnd/server.go
Add some warn logs for shrex server for to improve edge cases visibility.
> refactor(shrex/server): add warn logs to shrex server

- docs/adr/adr-009-public-api.md
- nodebuilder/header/header.go
- nodebuilder/header/service.go
Adds`WaitForHeight` endpoint which was formerly `GetByHeight` that just exposes store.GetByHeight
> feat(nodebuilder/header): Add `WaitForHeight` endpoint

- share/availability/discovery/discovery.go
Fixes #2204 
Regarding the case where we exhausted all the peers on the network and backed them all off. It can happen on the smaller network, and in the worst case, the node will wait 10 minutes(the default backoff time), which is acceptable considering peers from shrexsub #2105
> feat(share/discovery): Discard method

- header/header.go
- nodebuilder/tests/fraud_test.go
During the BEFP discussion on TG with @vgonkivs, we figured out that with have ___CRITICAL___ vulnerability in the header validation process. The funniest part is that we abuse this vulnerability to make our BEFP test in Swamp work, and the test represents the exact scenario of such vulnerability: a malicious BN/FN can substitute any value in RawHeader it wants like DAH and the verification on the client side still passes. This is because we don't check that BlockID(Hash) in Commit is aligned with recomputed RawHeader hash.
Unfortunately, this breaks our BEFP testing suite, and the only way to reliably produce FPs now is by modifying the Core/App node.
> fix(header): check that Commit corresponds to Header

- das/subscriber.go
- das/worker.go
Every new head now produces fewer logs + makes the more informative
Looks like below now
> chore(das): improve logging

- header/header.go
- header/headertest/testing.go
#2215 was approved and merged too quickly, making some tests fail. This PR fixes that. Expect further a new PR to clean up Validate func and increase coverage for it.
> fix(header): fix testing utilities and tests

- share/availability/discovery/backoff.go
- share/availability/discovery/discovery.go
- share/availability/discovery/metrics.go
> feat(share/discovery): add backoff metrics

- .github/workflows/go-ci.yml
- Makefile
Separate unit test coverage run to two separate steps: unit test and then upload code coverage report. Adds the token so that code coverage actually gets pushed to codecov.
> chore(.github): Fix coverage run to separate unit test and coverage upload to codecov

- nodebuilder/core/flags.go
> feat(nodebuilder): add ip resolving capabilities to core.ip

- cmd/auth.go
- libs/authtoken/authtoken.go
- nodebuilder/node.go
- nodebuilder/node_test.go
This PR adds the jwt.Signer to the node struct to be able to generate auth tokens for integration tests that use celestia-node's RPC.
> feat(nodebuilder): Add jwt.Signer to Node struct for auth token access

- nodebuilder/node.go
- nodebuilder/node_test.go
LNs don't need that much time to run
> chore(nodebuilder): decrease lifecycle timeout for LN

- blob/service.go
- nodebuilder/tests/blob_test.go
Gas estimation broke from an incorrect constant, that can now be replaced with an app import
> fix(blob): use default min gas price from core

- cmd/celestia/rpc.go
- nodebuilder/tests/blob_test.go
This PR does the following:
`blob.Submit` has been added with custom parsing for posting a single blob.
`blob.GetAll` also only takes a single namespace id for now. This will make devx easier
Now the request can also be displayed along with the json response. This will both help for debugging and building things that need to build the requests themselves
Namespaces are now encoded correctly again. In addition, if you pass a namespace of 8 bytes, it will zero-pad and use share/nID version 0.
Another issue was the change to an array. We now submit an array of a single blob, and changed the order of the arguments.
The order is now: fee, gasLimit, namespaceID, blob data
JQ is no longer needed to have an indented output. But colors are missing
> feat(cmd/rpc): adding blob module to rpc cli and fixing namespace parsing

- share/getters/cascade.go
- share/getters/cascade_test.go
Also fixes incorrect errors.Is for `share.ErrNamespaceNotFound`
Resolves https://github.com/celestiaorg/celestia-node/issues/2174
> fix(getter/cascade): cascade getter should return fast on context cancel

- blob/blob_test.go
- core/eds.go
- go.mod
- go.sum
- share/eds/eds_test.go
- share/ipld/nmt.go
- share/share.go
bumps app to latest release candidate. I'm not sure how celestia-node wants to handle app version changes. I'm completely unaware of any existing plans, so aplogies if this is already planned for, but ideally we don't rely on the latest appversion constant. This is definitely fine for v1, but when v2 comes along we will want to change which version we use according to what is in the header.
> chore: bump celestia-app to v1.0.0-rc2

- .github/workflows/docker-build-publish.yml
With v0.2.0 from common docker pipeline, we will have a faster generation of docker images for amd64. 
As with v0.1.1 arm64 is holding the generation of builds
> chore: bump common docker ci version pipeline

- api/gateway/state.go
- api/gateway/state_test.go
- api/gateway/util.go
Closes https://github.com/celestiaorg/celestia-node/issues/2328
> !feat(api/gateway): return txdata from submitPFB if it is present

- cmd/celestia/rpc.go
> fix(cmd/rpc): plaintext parsing of data for blob.Submit and state.SubmitPayForBlob

- logs/logs.go
Dagstore's debug logs increase startup time by 3-4x, and dagstore in general produces a lot of debug logs that are not very important for collecting.
> fix(dagstore): changing log level to WARN to shorten startup

- api/rpc/client/client.go
While working on #2356 I uncovered a bug:
When using the `client.NewClient` constructor, it uses a global static struct to set the modules. This led to clients overwriting each other when multiple are initialized.
> fix(rpc/client): stop overwriting existing clients

- api/docgen/examples.go
- api/gateway/state.go
- cmd/celestia/rpc.go
- nodebuilder/state/mocks/api.go
- state/address_test.go
- state/core_access.go
- state/integration_test.go
- state/state.go
While debugging #2322 , I noticed that it is not only an RPC issue, but also a broken API one. All RPC methods that used the type `state.Address` were unusable, both via the client and via raw JSON calls. This is because the server was unable to marshal the address string value back into the interface type. 
To circumvent this, I have embedded the sdk.Address type in the same way that we embed the fraud proof type, to allow us to unmarshal it back into a concrete type. I have also added unit tests to fix this.
In addition, it fixes the RPC parsing - so it closes #2322 .
> fix(state): JSON marshaling for sdk Address wrapper

- api/gateway/das.go
- api/gateway/endpoints.go
- api/gateway/state.go
- nodebuilder/gateway/config.go
- nodebuilder/gateway/constructors.go
- nodebuilder/gateway/flags.go
- nodebuilder/gateway/module.go
- Adds a warn log on startup if --gateway is passed
- Deprecated endpoints are now disabled by default. This includes:
- /balance
- /submit_pfd
- /query_delegation
- /query_unbonding
- /query_redelegations
- Deprecated endpoints can be activated by passing `--gateway.deprecated-endpoints`
- When using deprecated endpoints, the node will log a warning, giving the alternative RPC method to call in the future. 
The ugly config change/flag will be removed when fully deprecating the endpoints
> chore!(gateway): add deprecation notices

- nodebuilder/header/service.go
- nodebuilder/tests/api_test.go
#2173 missed a +1 check on the syncer head
Closes https://github.com/celestiaorg/celestia-node/issues/2357
> fix(header): GetByHeight requests for syncer head +1 shouldnt error

- share/eds/store.go
Caught a flake, and here is a fix: init map on Start, rather than in gc routine 
```
--- FAIL: TestEDSStore_GC (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1011ad8]
goroutine 15855 [running]:
testing.tRunner.func1.2({0x110b7a0, 0x1d73c30})
/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1529 +0x39f
panic({0x110b7a0, 0x1d73c30})
/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/panic.go:884 +0x213
github.com/celestiaorg/celestia-node/share/eds.TestEDSStore_GC(0xc01f719860) …
```
> fix(share/eds): fix test flake

- nodebuilder/config.go
- nodebuilder/node.go
- nodebuilder/node/config.go
Closes #2315 
Doing this proactively even though it is a good-first issue in case other dagstore startup issues are not fixed in time. Breaks the config.
> feat!(nodbuilder): making lifecycle timeouts configurable

- go.mod
- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/swamp/swamp.go
- nodebuilder/tests/sync_test.go
While fixing https://github.com/celestiaorg/celestia-node/issues/825, I discovered a race. We were not synchronizing writes to containers on the node. Additionally, I simplified storing of registered nodes by using map instead of per type slices. We don't use this per type separation anyhow
> fix(swamp): use synchronized map as container for nodes

- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/p2p_test.go
- nodebuilder/tests/swamp/swamp.go
- nodebuilder/tests/sync_test.go
This PR is a part of the swamp cleanussy effort to clean up our integration tests and make them more deterministic + readable. 
This PR focuses on `sync_test.go` file.
It also contains a change to fraud proof broadcasting test but I can happily split out into separate PR.
> chore(nodebuilder/tests): Clean up sync_test tests

- api/rpc/server.go
- libs/authtoken/authtoken.go
- nodebuilder/node.go
- nodebuilder/node/admin.go
- nodebuilder/node/mocks/api.go
- nodebuilder/node/module.go
- nodebuilder/node/node.go
- nodebuilder/node_test.go
- nodebuilder/tests/api_test.go
Implements node.AuthVerify and node.AuthNew.
Removes the jwt.Signer from the Node struct and replaces it with the nodebuilder.Node module, along with the other services.
Includes a minor version bump to the API.
> feat(node): implement node.AuthVerify and node.AuthNew

- share/namespace.go
- share/namespace_test.go
- share/nid.go
Mostly copied from the app's Namespace type with multiple modifications. In preparation for https://github.com/celestiaorg/celestia-node/issues/2301.
We want a more straightforward Namespace type from what the app provides:
* Repsents 1:1 mapping of the serialized form of Namespace [version byte + namespace id]
* So that it does not allocate on the hot path when getting data by namespace
* and had simpler json serialization
> share: introduce Namespace type

- api/gateway/state.go
Fixes a panic that can occur if txResp is nil and also returns actual error in the case of nil txResp.
Reported by @tuxcanfly
> fix(api/gateway): Handle err from tx properly to avoid panic

- go.mod
- go.sum
bumps app to rc5
[full changelog](https://github.com/celestiaorg/celestia-app/compare/v1.0.0-rc4...v1.0.0-rc5)
> chore: bump celestia-app to v1.0.0-rc5

- libs/utils/address.go
Fixes an issue where `localhost` was not accepted as a valid `--gateway.addr`. Uses net.ResolveIPAddr instead.
Found by @tuxcanfly
> fix(libs/utils): Use valid ip4 address

- share/getters/shrex.go
> feat: adding spans to shrex getter

- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
hello team!
This PR contains the updates for arabica-9:
- the genesis hash
- chain-id
- bootstrapper multiaddresses
thanks in advance! 🚀 
Jose Ramon Mañes
> chore!: bump arabica-9

- Dockerfile
- Makefile
hello team!
This PR contains a couple of things:
- Update the base version of Go Alpine to `golang:1.20-alpine3.18`
- In the Makefile, I've added the following line:
```Makefile
main.semanticVersion=$(shell git describe --tags --dirty=-dev 2>/dev/null || git rev-parse --abbrev-ref HEAD)'"
```
Basically what it does is, in case this commit doesn't contain any tag, it uses the branch name.
At the moment we are having some issues using the flag `version`, the output command is:
With this change, we'll have something like:
*Already tested*
Let me know what you think about it and if it's worth it 😊 
Thanks in advance! 🚀 
Jose Ramon Mañes
> feat: update Go base alpine - add branch in makefile

- share/p2p/shrexnd/client.go
`RequestND` doesn't actually verify the inclusion proofs; this is done later in `GetSharesByNamespace`:
https://github.com/celestiaorg/celestia-node/blob/main/share/getters/shrex.go#L237
> doc(share/p2p/shrexnd): Improve accuracy of RequestND description

- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
Update to mocha-3 chain name when init is called.
> chore(nodebuilder/p2p)! Upgrade to mocha-3

- nodebuilder/p2p/genesis.go
changes the trusted hash for mocha-3 to that of height 15045. this is a temporary fix the issue experienced on mocha-3 where commit verification fails because the validator set changed >2/3 in a single block
> fix: update the header hash in mocha-3 to be for height 15045

- .github/workflows/docker-build-publish.yml
hello team!
I've created a new version in the common pipeline, this one should fix the issues with the forks and we'll have the version output that we're currently missing when using the docker containers. 
If this works, we could close the PR: https://github.com/celestiaorg/celestia-node/pull/2421
I've tested on my end and seems to be working 🤞 
*PR where we've done the fix*: https://github.com/celestiaorg/.github/pull/65
Thanks in advance! 🚀 
Jose Ramon Mañes
https://github.com/celestiaorg/devops/issues/370
> feat: use context in the common pipeline

- header/headertest/verify_test.go
- header/verify.go
- nodebuilder/p2p/genesis.go
This PR disables skipping verification and accepts all the incoming non-adjacent headers. These headers will later be verified via adjacent verification and rejected if invalid. 
Test that proves that Syncer rejects and continues to work with a fault header: https://github.com/celestiaorg/go-header/pull/76
Potential outcomes of doing so: https://github.com/celestiaorg/go-header/issues/79
Additionally, the PR reverts the genesis hash change to the hash pointing to height 1.
Supersedes #2449, which became zombie
> fix(header): temporary disable skipping verification

- cmd/celestia/rpc.go
This PR fixes the error message returned by the rpc cli client, when an invalid height is passed to the `Get`, `GetAll` commands of the Blob module.
> cmd: rpc.go fix error parsing height message

- share/p2p/discovery/discovery.go
> chore(share/p2p/discovery): demote disc peers log to debug

- share/availability/full/availability.go
- share/availability/light/availability.go
Small cleanup to prevent node from spamming error availability logs on shutdown.
> refactor(share/availability): don't log error canceled operation

- cmd/flags_misc.go
- nodebuilder/node_test.go
- nodebuilder/settings.go
> feat(nodebuilder): Invoke traces from fx

- share/eds/byzantine/bad_encoding.go
Extend a BEFP validation.
Related to https://github.com/celestiaorg/celestia-node/issues/2377
> feat(share/byzantine): handle additional cases in befp validation

- nodebuilder/tests/swamp/swamp.go
Necessary to get core client to produce blocks in swamp at the moment.
Found by @rootulp
> fix(nodebuilder/tests/swamp): Bump timeout

- share/eds/store.go
Dagstore GC performs garbage collection by reclaiming transient files of shards that are currently available but inactive, or errored. We don't use transient files right now, so GC is turned off by default.
> fix(share/eds): turn off eds store dagstore gc by default

- share/eds/store.go
- share/eds/store_test.go
Needed fro and extracted from #2482 
I honestly have a concern about DagStore scalability. It loads *all* the shard's info on the map, which long term will have to store all the edses we ever stored, which will be a looot.
> feat(share/eds): introduce List method for the Store

- share/p2p/shrexeds/exchange_test.go
Quick fix for race in test. Found in [CI run](https://github.com/celestiaorg/celestia-node/actions/runs/5741418796/job/15561457106?pr=2444)
> fix(share/p2p): fix race in shrexeds test

- nodebuilder/settings.go
- nodebuilder/share/opts.go
- share/eds/metrics.go
- share/eds/store.go
I hate boilerplate, but I think it is reasonable here. If I generalise all operations right now, it will be huge pain later to modify specific ones later (like put metric is already different).
> feat(share/store): add eds store metrics

- nodebuilder/settings.go
Currently there is only one global attribute, that build by concatenating both exported attributes:
```
"job" = "Bridge/robusta-11rc9/12D3KooWAEQUSJh7aJFq7Cw1mP4VWnqfHtHwwwnsXHFhpQ2DMn7j"
```
`Breaking`, because this PR is breaking metrics compatibility.
> misc(metrics)!: split global attributes into two

- blob/blob.go
- cmd/celestia/blob.go
- cmd/celestia/rpc.go
- share/getters/cascade.go
Fixes all found rpc issues
Fixes https://github.com/celestiaorg/celestia-node/issues/2503 and https://github.com/celestiaorg/celestia-node/issues/2500
> fix(rpc): fix commands handling

- cmd/celestia/blob.go
As we expect direct types every time, I would suggest skipping error handling in case of format data(and simply return data if casting fails). I think this is the best way to keep logic generic and avoid any additional bool flags, options etc.
> fix(cmd): fix formatting during submit

- share/eds/store.go
When shard recovered in dagstore, it was read from in-memory mount, that could have been read 0 times and had no in-memory buffer.
> fix(share/eds): don't use in-memory buffer for mount after shard recover

- nodebuilder/store_test.go
- share/eds/store.go
Turns out `dagstore` has bug in its restore shard code. For each shard it attempts to create deep copy of registered type, but copies only basic struct fields of the mount type. In out case it means, that it copies a pointer.  That causes all shards to point to the same mount (same pointer).
Before `dagstore` is fixed to take into account possibility of pointers/interface (and any other reference type) in mount type struct fields, we will use direct copy of `mount.FileMount` instead of `mount.Mount` interface.
> fix(share/eds): dagstore shard restore reflection workaround

- logs/logs.go
`bitswap-client` logger generates 10k logs per sec in INFO level. This PR sets default log level to WARN
> fix(nodebuilder): set default log level for bitswap-client

- share/availability/full/reconstruction_test.go
TestShareAvailable_DisconnectedFullNodes had multiple bugs which caused it to be a false positive. The following issues were fixed:
1. The parameters used now don't allow for reconstruction from a single subnetwork, as they did before. This has been verified with a simulation - for `s = 20`, and `k = 16`, `c` set to 32 gives a 99.5% chance of reconstruction, and 16 (single subnetwork) gives a 0.5% chance. Before, both values of `c` gave a near 100% chance for reconstruction.
2. Increased the timeout for the first reconstruction. There was a check that verified that reconstruction was not possible from a single subnetwork, but it only failed to reconstruct because the timeout was too short. Increasing the timeout with the original parameters verified this. 
3. Shape the network topology …
> fix: TestShareAvailable_DisconnectedFullNodes

- share/p2p/discovery/discovery.go
libp2p routed host will attempt to find address, if none are provided. First in `Peerstore`, then by calling `FindPeer`:
```
// if we were given some addresses, keep + use them.
if len(pi.Addrs) > 0 {
rh.Peerstore().AddAddrs(pi.ID, pi.Addrs, peerstore.TempAddrTTL)
}
// Check if we have some addresses in our recent memory.
addrs := rh.Peerstore().Addrs(pi.ID)
if len(addrs) < 1 {
// no addrs? find some with the routing system.
var err error
addrs, err = rh.findPeerAddrs(ctx, pi.ID)
if err != nil {
return err
}
}
```
It is worth to try to connect in such case.
> fix(share/discovery): discovery should try to connect to empty hosts peers

- nodebuilder/core/config.go
- nodebuilder/fraud/lifecycle.go
- nodebuilder/module.go
- nodebuilder/node_light_test.go
- nodebuilder/node_test.go
- nodebuilder/settings.go
- nodebuilder/state/core.go
- nodebuilder/state/module.go
- nodebuilder/state/stub.go
- state/core_access.go
This is a pre-requisite for #2511 
It makes a check in CoreAccessor constructor to see if a core endpoint was provided, and returns nil CoreAccessor if not. A stubbed state module will then be provided if no core endpoint was provided so that errors are more readable. 
Previously, node start logic relied on the fact that the grpc Dial inside CoreAccessor.Start was non-blocking so it could silently fail under the hood and any calls made on state Module would return errors from the inability to reach the address that is the default for the core config (which was confusing).
> feat(nodebuilder/state): Provide stubbed state module if a core endpoint not provided

- cmd/celestia/blob.go
> fix(cmd/blob): fix response

- nodebuilder/core/config.go
Now that we short-circuit on the IP address being empty, it's fine to set defaults for RPC and GRPC ports 
This fixes swamp tests as well
> nodebuilder/core: Set default ports for RPC and GRPC

- go.mod
- go.sum
Updating dagstore should fix the issue with panic of mmap on bitswap reads.
> chore(deps): bump dagstore 

- share/namespace.go
- share/namespace_test.go
Addresses two follow-ups from https://github.com/celestiaorg/celestia-node/pull/2581
Closes https://github.com/celestiaorg/celestia-node/issues/2561
> refactor: address namespace follow-ups from celestia-app v1.0.0-rc12 bump

- cmd/cel-shed/eds_store_stress.go
- cmd/cel-shed/main.go
- libs/edssser/edssser.go
- nodebuilder/init.go
We need a way to stress test EDS Store now and long-term. This PR provides a tool that can be used to run such tests and measure, debug, explore, and fine-tune various aspects of the EDS storing sub-system in isolation.
The main goal is to investigate https://github.com/celestiaorg/celestia-node/discussions/2480 and ensure the future fix/solution is
> feat(edssser): introduce EDS Store Stresser and cel-shed utility

- share/getter.go
- share/getters/cascade.go
- share/getters/getter_test.go
- share/getters/ipld.go
- share/getters/store.go
GetShare would panic on RPC calls if the passed indicies were out of bounds.
> fix: fixing panic on GetShare with out of bounds indexes

- .github/workflows/go-ci.yml
- .golangci.yml
- cmd/celestia/rpc.go
- nodebuilder/config.go
- state/core_access.go
Self explanatory. The reason for the fix in core_accessor was an implicit memory aliasing. It was taking the address of the loop variable, which doesn't change in between iterations ofc, so the every blob pointed to the last blob
> chore(deps): bump golanci-lint workflow

- share/eds/metrics.go
Adds metrics to expose shards statistics.
> feat(share/eds) add dagstore shards status metric

- das/daser_test.go
- header/headertest/fraud/testing.go
- header/headertest/testing.go
- nodebuilder/fraud/lifecycle.go
- nodebuilder/p2p/opts.go
- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/swamp/swamp.go
- share/eds/edstest/testing.go
- share/getters/cascade.go
- share/getters/ipld.go
Reworked swamp test for the BEFP
> tests(swamp): befp testing

- nodebuilder/tests/p2p_test.go
- nodebuilder/tests/sync_test.go
Cleans up swamp tests in `p2p_test.go`.
Based on #2162
> chore(nodebuilder/tests): Clean up integration tests in `p2p_test`

- go.mod
- go.sum
Bumps go-header.
Resolves https://github.com/celestiaorg/go-header/issues/102 which was blocking sync for arabica-10
> chore(go.mod): bump go-header

- go.mod
- go.sum
- libs/pidstore/pidstore.go
- libs/pidstore/pidstore_test.go
- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
- nodebuilder/p2p/misc.go
Provides `PIDStore` to header module so that it can be used in `peerTracker` and replaces mem `peerstore.Peerstore` with on-disk `peerstore.Peerstore` so that `peerTracker` can quickly bootstrap itself with previously-seen peers and allow syncer to initialise its sync target from tracked peers rather than trusted so long as it has a subjective head within the trusting period.
Overrides #2133 
Closes #1851, mitigates issues resulting from #1623
Swamp integration tests to follow (tracked in #2506)
This PR introduces a soon-to-be deprecated feature from libp2p (on-disk peerstore). Once libp2p deprecates and removes this feature, the PIDStore will have to become a PeerAddrStore such that it can save addr info of good peers to disk instead of just their IDs.
> feat(nodebuilder/header): Bootstrap from previously seen peers

- nodebuilder/p2p/config.go
We already support WT as part of default libp2p supported transport, but node won't receive any connections unless they explicitly listen to them and this PR changes that/
> feat(modp2p): listen on WebTransport by default

- core/eds_test.go
- core/header_test.go
- core/listener_test.go
- das/coordinator_test.go
- das/daser_test.go
- header/header.go
- header/headertest/testing.go
- nodebuilder/share/share_test.go
- share/availability.go
- share/availability/cache/availability.go
- share/availability/cache/availability_test.go
- share/availability/light/availability_test.go
- share/availability/test/testing.go
- share/eds/byzantine/bad_encoding_test.go
- share/eds/eds.go
- share/eds/eds_test.go
- share/eds/edstest/testing.go
- share/eds/store.go
- share/eds/store_test.go
- share/empty.go
- share/getters/getter_test.go
- share/getters/shrex_test.go
- share/getters/testing.go
- share/p2p/shrexeds/exchange_test.go
- share/p2p/shrexnd/exchange_test.go
Somewhere we were using Root and somewhere DAH. Also, we mostly use DAH generator from the app. 
These PRs clean up all the usages and localize the Root/DAH type in `share` pkg as was originally intended.
Up to discussion is rename of `share.Root` to `share.DAH` to minimize discrepancies between app and node. Alternatively, if we wanna keep Root naming as it is, we should also rename DAH name on the ExtendedHeader(and son tags) and in other places, which is breaking.
Now, I think that calling it Root was not right and we should be calling the DataHash type Root, which is in fact the Merkle root of all the shares in the EDS.
> chore: cleanup usage of `share.Root`(DAH)

- nodebuilder/share/module.go
Fixes panic:
```
panic: invalid type received %!s(<nil>)
goroutine 602 [running]:
github.com/celestiaorg/go-header/p2p.(*subscription[...]).NextHeader(0x103fbeaa0?, {0x103fdcd50, 0x14000723310?})
/Users/rford/go/pkg/mod/github.com/celestiaorg/go-header@v0.3.1/p2p/subscription.go:44 +0x2ac
github.com/celestiaorg/celestia-node/share/p2p/peers.(*Manager).subscribeHeader(0x1400158c960, {0x103fdcd50, 0x14000723310}, {0x103fbe928?, 0x14000676250?})
/Users/rford/Programming/Celestia/celestia-node/share/p2p/peers/manager.go:299 +0xc0
created by github.com/celestiaorg/celestia-node/share/p2p/peers.(*Manager).Start in goroutine 262
/Users/rford/Programming/Celestia/celestia-node/share/p2p/peers/manager.go:180 +0x410
```
> fix(modshare): start peer manager after Syncer

- cmd/celestia/blob.go
Added fee and gasLimit flags to submit the blob
Tested on arabica-10:
```go
celestia rpc blob submit 0x42690c204d39600fddd3 'gm' --fee 10000
{
"result": {
"height": 62559,
"commitment": "IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E="
}
}
celestia rpc blob submit 0x42690c204d39600fddd3 'gm' --fee 10000 --gas.limit 100000
{
"result": {
"height": 62561,
"commitment": "IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E="
}
}
celestia rpc blob submit 0x42690c204d39600fddd3 'gm' --gas.limit 100000
{
"result": {
"height": 62562,
"commitment": "IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E="
}
}
```
cc @jcstein
> feat(cmd/blob): add fee and gasLimit flags

- das/options.go
- nodebuilder/p2p/network.go
Block times will be closer to 10 seconds on average than 15, so we should shift this to make calculations based on block time in our codebase more accurate.
This will also fix issues with syncing `arabica-10`
> chore(nodebuilder/p2p): BlockTime from 15 sec --> 10 sec

- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
- nodebuilder/testing.go
> refactor(nodebuilder/header): get rid of `InitStore`

- cmd/celestia/rpc.go
- cmd/celestia/share.go
> feat(rpc): add share cmd

- share/p2p/shrexeds/client.go
If we receive a valid StatusMessage, we only CoseWrite side of the stream, but the stream interface states:
```
// CloseWrite closes the stream for writing but leaves it open for
// reading.
//
// CloseWrite does not free the stream, users must still call Close or
// Reset.
CloseWrite() error
```
> fix(shrexeds): close stream

- go.mod
- go.sum
Related: https://github.com/celestiaorg/nmt/pull/233
> deps!: bump nmt, breaking JSON RPC return types including nmt Proofs

- share/availability/full/availability.go
When we stopped wrapping full availability with cache availability we forgot to add a short circuit to full avail.
This will save us a datastore hit through the eds store Has call.
> fix(full/availability): short-circuiting SharesAvailable on empty DAH

- nodebuilder/state/stub.go
After getting the following response from the RPC
```
➜ celestia rpc state AccountAddress
{
"jsonrpc": "2.0",
"id": 1,
"error": {
"code": 1,
"message": "node is running without state access"
}
}
```
I realized it would be more helpful to tell users what they can do to resolve the issue. Knowing that the node needs to be passed --core.ip when you see "node is running without state access" is not something obvious
> fix: improve ErrNoStateAccess message

- share/p2p/discovery/options.go
Resolves https://github.com/celestiaorg/celestia-node/issues/2704
> refactor(share/discovery): decrease default Advertisement interval

- nodebuilder/blob/cmd/blob.go
Closes #2707
Added usage template for `blob.submit`, that allows to hide confusing -1 param for a fee and add an extra line that explains what will happen if `fee` and `gas.Limit` won't  be provided
```
Submit the blob at the given namespace.
Note:
* only one blob is allowed to submit through the RPC.
* fee and gas.limit params will be calculated automatically if they are not provided as arguments
Usage:
celestia blob submit [namespace] [blobData] [flags]
Flags:
--fee int          specifies fee (in TIA) for blob submission [optional]
--gas.limit uint   sets the maximum amount of gas that is allowed to consume during blob submission [optional]
-h, --help             help for submit
Global Flags:
--token string   Authorization token (if not provided, the CELESTIA_NODE_AUTH_TOKEN environment …
```
> refactor(rpc/blob) extend docs in blob

- cmd/auth.go
- cmd/celestia/rpc.go
- cmd/flags_node.go
- cmd/rpc.go
Added node.store flag to all rpc cmds that allows to get auth token from the config
`celestia blob submit 0x42690c204d39600fddd3 'gm' --node.store=~/.celestia-light-arabica-10`
> feat(cmd/rpc): add node store flag

- share/eds/store_test.go
- share/getters/getter_test.go
Adds benchmarks to ensure cache overload performance.
1. Measures time to fully load accessor from disk to cache
2. Measures time it takes for multiple parallel ipld readers (clients) to sample eds directly from store, when there is not enough cache slots. Results shows it takes ~12s to sample for parallel 10 readers.
> test(share/eds/cache): benchmark eds cache eviction performance

- .github/dependabot.yml
Fixes dependabot regex to not use`^`, since it seems to not support anything but `*` wildcard
> chore(deps): fix dependabot otel grouping

- .github/dependabot.yml
currently only the go.mod dependabot PRs were getting the `kind:deps` label, so others that targer Docker or github actions would fail a label check
eg: https://github.com/celestiaorg/celestia-node/pull/2794
this should fix that. minor tweak.
> (chore) ensure all dependency group PRs get the default label

- share/p2p/peers/manager.go
- share/p2p/peers/pool.go
Resolves https://github.com/celestiaorg/celestia-node/issues/2807
> fix(share/peer-manager): use mutex for peer-manager pool cleanup

- docs/adr/adr-009-public-api.md
- nodebuilder/header/header.go
Fixes https://github.com/celestiaorg/go-header/issues/72
> fix(docs): fix GetVerifiedRange doc

- share/ipld/get.go
- share/ipld/get_shares.go
- share/ipld/namespace_data.go
- share/ipld/nmt.go
The load these traces can produce is massive. In the case of ODS size 128 and the whole block is sampled for namespace data, it will be **48896** spans `(128*2-1)*128*2 - (128 * 128)`. Besides, there is zero value this tracing brought us so far.
> chore(share/ipld): obliterate expensive ipld getter tracing

- share/eds/blockstore.go
- share/eds/cache/accessor_cache_test.go
- share/eds/metrics.go
- share/eds/store.go
- share/eds/store_test.go
- share/p2p/peers/pool.go
Fixes races in eds cache tests:
- read / write isClosed flag in Cache mock
- write / write for error object from 2 goroutines
- read / write of cache object inside edsStore on cache swaps in tests.
Resolves https://github.com/celestiaorg/celestia-node/issues/2833
> fix(share/eds): fix races in cache tests

- nodebuilder/p2p/addrs.go
- nodebuilder/p2p/host.go
Disables QUIC by default yet allows to enable it with ENV var. 
This is temporary and until https://github.com/libp2p/go-libp2p/issues/2591 is investigated and fixed.
The current solution disables QUIC programmatically while we still keep writing in the config QUIC listen addresses by default. This removes the need for users to reinit their configs once we turn QUIC back by default.
This works perfectly fine on mocha.
> fix(modp2p): temporary disable quic

- .github/workflows/ci_release.yml
- .github/workflows/docker-build-publish.yml
Final bug fix https://github.com/celestiaorg/.github/pull/82
Visual proof of action executing as expected now
https://github.com/celestiaorg/celestia-node/actions/runs/6509222904/job/17680437495
> bug: fix duplicate docker build stages

- cmd/flags_node.go
Also part of #2823 
Stacked on #2840
> fix: removing chainid from default store name for mainnet

- share/getters/shrex.go
Should fix issue where GetEDS hangs on empty data root
To test run:
`celestia share get-eds “$(celestia header get-by-height 500 --node.store ~/.celestia-light-mocha-4 | jq .result)” --node.store ~/.celestia-light-mocha-4`
with and without the PR
> fix(share/getters): short-circuit on empty root in ShrexGetter

- blob/service.go
Error returned by `GetAll` is not formatted correctly. It's especially important, because users of the method will most probably try to detect `ErrBlobNotFound` (to differentiate from other errors).
> fix(blob): properly wrap error in GetAll method

- core/listener.go
Block time can vary quite a bit so do not trigger re-subscription unless there's a significant lag (3x blocktime). This issue was found by bridge node runners on `mocha-4` where block time sometimes exceeded 20s
> fix(core): Increase listener timeout to 3x block time

- .github/pull_request_template.md
As discussed, overrides the organization wide `.github/pull_request_template.md` with the checklist everyone ignores, instead favoring just a comment when opening the PR and a request to add a reference to an issue for a PR check we'll add shortly, opening a PR should just look like this now:
> override organization pull_request_template.md

- .github/workflows/go-ci.yml
- blob/service_test.go
Refs https://github.com/celestiaorg/celestia-node/issues/1584
Lets run our test suite on multi configurations as they sometimes pass one not other (as reported by @vgonkivs)
- Task: run tests on > 1 OS (previously ubuntu-latest only) now `ubuntu-latest` and `macos-latest`
- currently ONLY for the unit tests (do we want to change this for all the tests?)
- also makes a small unrequested tweak to make the execution in go-ci run AFTER the mod and lint checks, so it'll pause if those two fail and fail the entire pipeline faster. Save some wasted compute time, which will be at least x2 worse once we matrix these
example run: https://github.com/celestiaorg/celestia-node/actions/runs/6559066381/job/17813974060
> (ci) matrix tests for different OS

- share/eds/byzantine/bad_encoding.go
- share/eds/byzantine/bad_encoding_test.go
Extend test cases for befp.Validate.
> tests(share/byzantine): extend befp tests

- .github/workflows/ci_release.yml
- .goreleaser.yaml
mimics the signed binaries by goreleaser as implemented in `celestia-app` so node can also generate signed binaries
@MSevey confirmed that we have an org level secret for `GPG_SIGNING_KEY` and `GPG_PASSPHRASE` so should require no repo setup
implementation for app: https://github.com/celestiaorg/celestia-app/commit/934fdeda062229f5c150e9dce74f05b0557ea123
Will follow up with some work to ensure this workflow actually gets triggered (currently the steps before do not pass and generate binaries)
closes: https://github.com/celestiaorg/celestia-node/issues/2679
> signed binaries for goreleaser

- core/listener.go
Resolves https://github.com/celestiaorg/celestia-node/issues/2875
> fix(core/listener): make listener to retry subscribing on errors

- cmd/auth.go
minor annoyance where running `auth admin` always has the token output run right into the next shell prompt.
> chore(cmd): add a newline after printing token so it doesn't run into shell prompt

- .github/workflows/go-ci.yml
Today I faced multiple times with `timeout exceeded` error on ci action. Increasing timeout helps to avoid this issue.
> chore: increase lint timeout

- share/availability/full/testing.go
All tests that used TestAvailability were flaky. They could randomly receive `tempdir remove all cleanup unlinkat directory not empty`. It happened to me 100% time when I was running a test with `--count > 50`. It happened because the eds store was storing the data and the temp folder could not be deleted.
> fix(test/daser): stop the eds store before finishing the test

- .github/workflows/go-ci.yml
Disable "fail-fast" so if the `ubuntu-latest` matrix unit test fails then it wont cancel the run of `macos-latest`, this will help with easing ability to merge as we've reduced the requirement for both to merge
> chore(ci): disable fail-fast on matrix tests

- blob/service.go
- blob/service_test.go
- share/eds/utils.go
- share/getter.go
- share/getters/shrex.go
Fixes https://github.com/celestiaorg/celestia-node/issues/2860
Proof:
> fix(blob/service): handle absence proof

- go.mod
- go.sum
- state/core_access_test.go
This PR bumps to v1.4.0 of celestia-app, which should be a non-breaking version and has been tested by syncing from scratch on mainnet. We still need to test on robusta before moving onto arabica-11 and mocha-4.
> chore: bump celestia-app to v1.4.0

- nodebuilder/p2p/bitswap.go
Decouples Bitswap into Client and Server. This is necessary to provide new custom options to the Client. In particular, this brings `client.WithoutDuplicatedBlockStats()` option to the table as nice little optimization for LNs. It disables one metrics we don't care much about atm, but avoids expensive Has call to DB as profiles show.
> refactor(modp2p): decouple Bitswap

- .goreleaser.yaml
Configure GoReleaser's prerelease-suffix: https://goreleaser.com/customization/git/#git
If the prerelease-suffix is not configured, then GoReleaser will treat `v1.5.0-rc0` as more recent than `v1.5.0`. This is problematic because if the real release is cut after the release candidate, then GoReleaser won't attach pre-built binaries to the real release. This just happened on celestia-app v1.5.0 so ideally this saves ya'll some time when celestia-node starts publishing pre-built binaries.
Motivating issue: https://github.com/celestiaorg/celestia-app/issues/2897
> ci: configure prerelease-suffix

- share/eds/edstest/testing.go
- share/getter.go
- share/getters/shrex_test.go
- share/sharetest/testing.go
- share/store/eds_file.go
- share/store/mem_file.go
- share/store/mem_file_test.go
Adds in-memory file implementation
> feat(store/mem_file): add in-memory eds file implementation

- cmd/util.go
json.MarshalIndent cut the result in case of error is received in `PrintOutput`, so the string representation was empty. 
`celestia state balance-for-address celestia1kanc76z0xet2kgq5fl3pj59axy56htk367trer --url=https://full.consensus.mocha-4.celestia-mocha.com --node.store=~/.celestia-light-mocha-4`
`{
"result": "RPC client error: sendRequest failed: Post \"https://full.consensus.mocha-4.celestia-mocha.com\": dial tcp 151.115.12.131:443: connect: connection refused"
}`
> fix(cmd): explicitly set a string representation of the error

- nodebuilder/p2p/addrs.go
- nodebuilder/p2p/host.go
Reverts disabled quic. We weren't able to reproduce [the issue](https://github.com/libp2p/go-libp2p/issues/2591) since we first observed it, as well as quic released changes to address this. Even if the issue is there, I think it's more or less safe as we always have TCP as fallback
> Revert "fix(modp2p): temporary disable quic (#2837)"

- .github/dependabot.yml
opening this as a possible solution and to discuss if we want to make the matching more greedy, but this implements a suggestion by @walldiss last week to have dependabot be less aggressive with suggesting EVERY patch release for all dependencies, only limiting to major and minor updates as suggestion. 
Arguably, we could expand the wildcard to more than `*otel*` and apply to everything, but maybe we just let it run on otel for a bit and see what the consequences are before considering applying it more broadly.
Also, i think we should review the security alert configuration side of dependabot as a companion to this to ensure we DO get security alerts if a CVE or issue is patched. But that will be separate
> ignore otel patch updates

- go.mod
- go.sum
A regular bump with multiple minor fixes as well broader optimizations like TCP eyeballing 
https://github.com/libp2p/go-libp2p/releases/tag/v0.32.0
It may also fix the issue behind #2837, but this has to be confirmed yet
> chore: bump go-libp2p

- core/exchange.go
We should have been using the high-level `Verify` check from go-header inside of the `CoreExchange` instead of the `ExtendedHeader`-based implementation of Verify.
> fix(core): Use `Verify` from go-header pkg in `CoreExchange`

- go.mod
This PR does not change any of the dependency, it only reorders the go.mod file into a direct and undirect import section, as go versions do since 1.17.
The reason your go.mod file got so many require sections is because during the 1.16 to 1.17 go.mod styling transition you had different contributors updating the go.mod file with pre 1.17 and post 1.17 releases of go.
See https://go.dev/doc/modules/gomod-ref:
> At go 1.17 or higher:
section for a description of what changed.
> chore: cleanup go.mod file require sections

- libs/pidstore/pidstore_test.go
- nodebuilder/p2p/cmd/p2p.go
- nodebuilder/tests/api_test.go
- nodebuilder/tests/swamp/swamp.go
- share/getters/shrex_test.go
- share/ipld/corrupted_data_test.go
- share/p2p/peers/manager.go
- state/core_access.go
Used a tool to find stray spellings then fix them, hopefully this will prevent future small PRs for little fixes emerging and we can encourage more significant / valuable PRs from external contributors
> chore(spelling): fix all stray typos across comments and tests

- api/rpc/server.go
- api/rpc_test.go
- nodebuilder/rpc/constructors.go
In the current skip-auth implementation, there was an issue: Authentication could be skipped, but it still required the `Authentication` header to be set (it just wouldn't check it).
This PR improves the devex by removing this requirement. I missed it the first time because I tested by using the CLI, which always sets the header regardless of what you pass. This came up while implementing https://github.com/eigerco/lumina/pull/210, since the wasm client cannot set headers.
I also think the solution is cleaner than the original.
> fix: improve rpc.skip-auth

- api/docgen/examples.go
Open RPC spec generation errors, due to a missing sample value for blob.GasPrice.
Missing sample value in `api/docgen/examples.go`.
Logs from running on v0.13.0:
```json
--> Generating OpenRPC spec
failed to retrieve example value for type: blob.GasPrice on parent 'blob.GasPrice')
{
"openrpc": "1.2.6",
"info": {
"title": "Celestia Node API",
"description": "The Celestia Node API is the collection of RPC methods that can be used to interact with the services provided by Celestia Data Availability Nodes.",
"version": "v0.11.0"
},
```
Output from logs running on v0.11.0, as another check to see that this worked before:
```json
--> Generating OpenRPC spec
{
"openrpc": "1.2.6",
"info": {
"title": "Celestia Node API",
"description": "The Celestia Node API is the collection of RPC methods that …
```
> feat: add example value for blob.GasPrice

- .github/workflows/integration-tests.yml
- nodebuilder/tests/da_test.go
- split the new flakey DA tests into own tag and call so we don't think blob has started failing suddenly
- Total shutdown of DA integration test `GetIDs` until we can figure out what is going on
> chore(ci): split da into own tag, and skip a consistently failing test

- api/docgen/examples.go
- cmd/auth.go
- cmd/cel-shed/header.go
- cmd/rpc.go
- core/fetcher.go
- core/listener.go
- das/daser.go
- das/options.go
- share/eds/inverted_index.go
- share/eds/store_options.go
Some parameterless errors should be using errors.New instead of fmt.Errorf
> improve: use errors.New to replace fmt.Errorf with no parameters

- .github/workflows/ci_release.yml
- .github/workflows/go-ci.yml
- .golangci.yml
- api/docgen/openrpc.go
- cmd/cel-shed/eds_store_stress.go
- cmd/cel-shed/p2p.go
- cmd/config.go
- cmd/docgen/openrpc.go
- cmd/init.go
- cmd/reset_store.go
- cmd/start.go
- nodebuilder/core/module.go
- nodebuilder/das/cmd/das.go
- nodebuilder/header/cmd/header.go
- nodebuilder/node/cmd/node.go
- nodebuilder/node/metrics.go
- nodebuilder/p2p/bitswap.go
- nodebuilder/p2p/cmd/p2p.go
- nodebuilder/p2p/metrics.go
- nodebuilder/share/module.go
- nodebuilder/state/cmd/state.go
- share/eds/cache/metrics.go
- share/eds/metrics.go
- share/p2p/discovery/metrics.go
- share/p2p/peers/metrics.go
- state/metrics.go
with our `1.22` upgrade i got inadvertently upgraded to `golangci-lint` 1.56 locally and experiencing different results to what was in CI so figured, why not upgrade, i believe this upgrade makes 'revive' active and a replacement to golint, which introduced some better/stricter checks
- upgrades `golangci-lint` to 1.56
- fixes or marks `//nolint:revive` a few new unused variable errors that were triggering
- configures revive to ignore `_test` files
- CI passes with new checks
> ci(lint): upgrade golangci-lint to 1.56 and fix revive errors that emerged

- nodebuilder/config.go
- nodebuilder/init.go
- nodebuilder/init_test.go
- nodebuilder/store.go
Review discussion that did't get to the PR because of automerge
> refactor(nodebuilder): stick to lock semantics, not file

- Dockerfile
This should be a non-breaking change.
This only changes the work directory when the container is started. This means that if you want to execute a command in a running container, it will be automatically in that directory instead of '/'. This improves maintaining and debugging our environments.
> feat: add workdir to dockerfile

- nodebuilder/share/cmd/share.go
This PR resolves https://github.com/celestiaorg/celestia-node/issues/3226
Numbers with an even amount of digits are valid hex :) we should try to parse uint first, then attempt to parse hash.
> fix(nodebuilder/share/cmd): Fix parsing of uint for height in `share` rpc CLI commands

- nodebuilder/module.go
- nodebuilder/testing.go
We never did anything with the errors provided to fx, we can just short-circuit and return quickly if either fails.
> fix(nodebuilder): return fx error if theres an error getting keystore or constructing signer

- share/eds/retriever.go
Store repaired shares and calculated nmt proofs if reconstruction failed.
> feat(share/eds): Store nmt nodes on failed reconstruction

- core/listener.go
Subscription was never cancelled on Stop, found while working on swamp tests for #3188
> fix(core): Unsubscribe from new block event on Stop in listener

- go.mod
- go.sum
- nodebuilder/module.go
- nodebuilder/state/core.go
- nodebuilder/state/keyring.go
- nodebuilder/state/module.go
- nodebuilder/state/opts.go
- nodebuilder/testing.go
- nodebuilder/tests/blob_test.go
- nodebuilder/tests/swamp/swamp.go
- state/core_access.go
- state/core_access_test.go
- state/integration_test.go
Closes: #3296
This adds the [`Signer`](https://github.com/celestiaorg/celestia-app/blob/bcab06582c9802f1d49a2bee86820792258bb587/pkg/user/signer.go#L31) struct from celestia-app's user package. 
Signer keeps track of both the network and local sequence number allowing for multiple messages to be signed within a single block.
This also uses the `EstimateGas` function of the signer to estimate the gas, when the user provides 0 as the `gasLim`
TODO: we should probably introduce some gas multiplier (default: 1.1) to the `EstimateGas` as it seems to underestimate the value (cc @vgonkivs)
> feat(state): Integrate new Signer for concurrent tx submission

- share/p2p/recovery.go
- share/p2p/shrexeds/server.go
- share/p2p/shrexnd/server.go
Add recovery middleware to shrex-eds and shrex-nd server implementation
> feat(share/p2p/shrex): add recovery middleware to shrex-nd and shrex-eds servers

- go.mod
- go.sum
> chore: bump go-libp2p-pubsub

- blob/blob.go
- blob/parser.go
- blob/service.go
- blob/service_test.go
> doc: improve godoc for the blob service

- logs/logs.go
```
May 24 04:10:51 celestia[1806932]: 2024-05-24T04:10:51.439Z        INFO        bitswap-server        server/server.go:547        Bitswap Client ReceiveError: Application error 0x0 (local)
May 24 04:10:51 celestia[1806932]: 2024-05-24T04:10:51.440Z        INFO        bitswap-server        server/server.go:547        Bitswap Client ReceiveError: stream reset
May 24 04:10:51 celestia[1806932]: 2024-05-24T04:10:51.443Z        INFO        bitswap-server        server/server.go:547        Bitswap Client ReceiveError: Application error 0x0 (local)
May 24 04:10:51 celestia[1806932]: 2024-05-24T04:10:51.443Z        INFO        bitswap-server        server/server.go:547        Bitswap Client ReceiveError: Application error 0x0 (local)
May 24 04:10:51 celestia[1806932]: 2024-05-24T04:10:51.443Z …
```
> chore(logs): lower bitswap-server verbosity

- go.mod
- go.sum
New version was released https://github.com/celestiaorg/nmt/releases/tag/v0.21.0
> chore(deps): Bump github.com/celestiaorg/nmt from v0.20.0 to v0.21.0

- cmd/node.go
Adds `--experimental-pruning` flag to LN
> fix(cmd): Add pruner flags to LN as well

- share/getter.go
- share/getters/getter_test.go
- share/getters/shrex_test.go
- share/ipld/get_shares.go
Make return of shares consistent accross tall getter, when encountering non-inclusion case
Improves unnecessary allocations of empty slice.
Resolves https://github.com/celestiaorg/celestia-node/issues/3448
> fix(share/getters)!: return nil shares from all getters in non-inclusion case

- share/new_eds/accessor.go
- share/new_eds/axis_half.go
- share/new_eds/eds.go
- share/new_eds/in_mem.go
- share/new_eds/in_mem_test.go
- share/new_eds/nd.go
- share/new_eds/nd_test.go
- share/new_eds/rsmt2d.go
- share/new_eds/rsmt2d_test.go
- share/shwap/namespace_data.go
- share/shwap/row.go
- share/shwap/row_namespace_data.go
- share/shwap/row_namespace_data_test.go
- share/shwap/row_test.go
- share/shwap/sample.go
- share/shwap/sample_test.go
- Reintroduce file interface as eds interface. Change aims to allow usage of EDS interface outside of storage package and to be high level interface of EDS methods.
- Renames of eds interface methods to align with returned shwap types names
- Share() -> Sample
- Data -> Row data
- Extracts New<shwap_type_name>FromEDS functions to eds file methods
- moves associated tests to eds pkg
**Additional refactoring:**
- **Change Interface Name**: Realized that 'EDS' is a terrible name for an interface. Renamed `eds.EDS` to `eds.Accessor` to more accurately reflect its functionality rather than its internal content.
- **Separate Closer**: Extracted `Closer` from `Accessor`. Now it is available in a new composite interface `AccessorCloser`.
- **Rename InMem**: Renamed `InMem` to `rsmt2d` to better …
> refactor(shwap): Extract eds interface

- blob/parser.go
- blob/service_test.go
- nodebuilder/pruner/module.go
- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/prune_test.go
- nodebuilder/tests/swamp/swamp.go
- pruner/checkpoint.go
- pruner/checkpoint_test.go
- share/eds/byzantine/share_proof.go
This PR add safety check, that prevents node runner from converting previously pruned node to archival, because it is not supported.
> feat(share/pruner): disallow converting pruned node to archival

- nodebuilder/share/module.go
- nodebuilder/tests/prune_test.go
- share/getters/shrex_test.go
Since it is a network constant, shrex getter request routing should be based on the hardcoded light.Window rather than the avail window that is passed to it. `light.Window` should be used network-wide to determine which peer pool (`full` or `archival`) would be most likely to serve the request.
This also fixes a bug where archival nodes would not route historic EDS requests to the archival pool due to AvailabilityWindow being 0.
> fix(nodebuilder/share): Pass `light.Window` to shrex getter construction regardless of node type / pruning mode

- share/ipld/namespace_data.go
Moving from raw `int64` and atomic operations to the `atomic.Int64` type. As a result fixing a few places where we were accessing atomic variables non-atomically. Which isn't a problem 'cause there were only reads BUT these places would reported by race detector and fail our tests for not a big reason.
> refactor(share): use atomic.Int64 and fix 'racy' bugs

- share/eds/cache/noop.go
- share/new_eds/accessor.go
- share/new_eds/rsmt2d.go
- share/new_eds/rsmt2d_test.go
- share/new_eds/testing.go
- share/shwap/row_namespace_data.go
Adds generalised testing framework for file interface implementaions
Also adds non-inclusion proofs handling in RowNamespaceDataFromShares and closes https://github.com/celestiaorg/celestia-node/issues/3428
> feat(share/eds) Add Accessor test infra

- nodebuilder/fraud/lifecycle.go
- nodebuilder/p2p/misc.go
- share/eds/cache/noop.go
- share/p2p/discovery/discovery.go
These logs would happen infrequently anyway (hourly) and we only logged error case so would be nice to see the success case without having to enable debug logs.
Also some random linter failure fixes on my end.
> chore(share/p2p/discovery): Change success case logging for advertisement to INFO level

- nodebuilder/store_test.go
- share/eds/edstest/testing.go
- share/sharetest/testing.go
Small refactoring to use testing.TB instead of require.T in testing pkgs
> refactor(testing): replace require.TestingT with testing.TB

- .github/workflows/ci_release.yml
- .github/workflows/go-ci.yml
somewhere along the upgrades, the input parameters to the golangci-lint action changed where `skip-pkg-cache` and `skip-build-cache` became just `skip-cache`. CI would show a warning that these were no longer known inputs but not fail. Thus, updating.
eg:
> ci: remove golangci-lint action warning

- go.mod
- share/new_eds/axis_half.go
- share/new_eds/axis_half_test.go
- share/new_eds/rsmt2d_test.go
- share/new_eds/testing.go
- share/shwap/row_namespace_data.go
- share/shwap/sample.go
- store/file/codec.go
- store/file/codec_test.go
- store/file/header.go
- store/file/ods.go
- store/file/ods_test.go
- store/file/square.go
This PR adds ods file, that implements eds.Accessor interface. The file stores ods part of eds on disk and lazily reads data upon request. If requested data is from Q4, it reads full ods in single read and stores it in-memory for later re-use.
Based on https://github.com/celestiaorg/celestia-node/pull/3425
> feat(shwap): Add ODS file

- .github/workflows/ci_release.yml
- .github/workflows/create_release_tracking_epic.yml
- .github/workflows/docker-build-publish.yml
pulling in update/change from https://github.com/celestiaorg/.github/pull/109 to remove the GitHub actions CI warning about using an action that uses node 16 which is deprecated, simple.
> ci: update celestia shared dep to remove node 16 warning

- api/docgen/exampledata/blob.json
- api/docgen/exampledata/blobProof.json
- api/docgen/examples.go
Improved examples for blob related types to be consistent throughout (Commitment, Proof, Blob, Namespace). Previous blob.Proof and blob.Commitment were not valid values.
Also added a valid example value for libhead.Hash
> feat(docgen): improve examples

- .github/workflows/ci_release.yml
- Dockerfile
- README.md
- go.mod
- go.sum
We want testnets to use whichever version of celestia-app is specified by celestia-node's go.mod so this PR bumps the celestia-app dependency so that v1.12.0 can get deployed.
> chore(deps): upgrade to celestia-app v1.12.0

- share/new_eds/testing.go
- store/file/ods.go
- store/file/ods_test.go
- store/file/q1q4_file.go
- store/file/q1q4_file_test.go
Q1Q4 file stores 2 quadrants and allow more efficient reads of Q4 samples compared to ODS file
> feat(shwap): add Q1Q4 file

- cmd/flags_node.go
- nodebuilder/core/config.go
- nodebuilder/core/config_test.go
- nodebuilder/core/flags.go
- nodebuilder/core/flags_test.go
identified by @tac0turtle (TYBG) whereby, in the specific case where you had edited you node store's config values to be non-default for `Core.RPCPort` or `Core.GRPCPort`, if you were to then provide a different value for Core.IP via the `--core.ip` flag at node start time, then the flag defaults for `core.rpc.port` and `core.grpc.port` would revert the values to defaults and override the custom values in config.toml. Fix is to check that the default value had been reset in the flag, and only use the default if no value had been set in the passed in config, which in most cases is already loaded as default or the config.toml values.
Took liberty to add some tests, and update some duplication of default values while in here.
fixes #3523
> fix(nodebuilder/core): non default values from config.toml are written over by flag defaults in specific circumstances

- nodebuilder/node/buildInfo.go
- nodebuilder/node/buildinfo_test.go
- nodebuilder/p2p/host_test.go
It looks as though when the useragent name request of #2932 was addressed in https://github.com/celestiaorg/celestia-node/pull/2956 a 'v' was added to the string formatting with the `BuildInfo.SemanticVersion` which is added to the useragent. (see: https://github.com/celestiaorg/celestia-node/pull/2956/files#diff-78ab4bf0b5adebb93a427d5c0222a637919ca538457678126428146a3bf3c663R35) and carried over in the PR with tests and refactoring (https://github.com/celestiaorg/celestia-node/commit/86f4b2aa1dd54a390dd213d5011b48ab51aa7321#diff-4bbc044dfe14e79d9f168542d12302c631a91f5b5d9c17f55e5ef81ea7fb5611R35)
We actually set this SemanticVersion from git tags at build time [here](https://github.com/celestiaorg/celestia-node/blob/main/Makefile#L6) with ldflags and the tag already has `v` in the …
> fix(nodebuilder/p2p): remove prepended v against detected semantic version 

- nodebuilder/blob/cmd/blob.go
Partly refs #3335
```
celestia blob get 1337536 0x42690c204d39600fddd3 IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E=
{
"result": {
"namespace": "0x42690c204d39600fddd3",
"data": "gm",
"share_version": 0,
"commitment": "IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E=",
"index": 1
}
}
```
```
celestia blob get 1337536 0x42690c204d39600fddd3 IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E= --base64=true
{
"result": {
"namespace": "AAAAAAAAAAAAAAAAAAAAAAAAAEJpDCBNOWAP3dM=",
"data": "Z20=",
"share_version": 0,
"commitment": "IXg+08HV5RsPF3Lle8PH+B2TUGsGUsBiseflxh6wB5E=",
"index": 1
}
}
```
Current PR fixes namespace representation, so it will be consistent with the passed one. Blob cmds require hex-based namespaces only now.
> fix(cmd): fix namespace representation in cmd output

- share/new_eds/validation.go
- share/new_eds/validation_test.go
- share/shwap/eds_id.go
- share/shwap/eds_id_test.go
- share/shwap/p2p/bitswap/row_block.go
- share/shwap/p2p/bitswap/row_block_test.go
- share/shwap/p2p/bitswap/row_namespace_data_block.go
- share/shwap/p2p/bitswap/row_namespace_data_block_test.go
- share/shwap/p2p/bitswap/sample_block.go
- share/shwap/p2p/bitswap/sample_block_test.go
- share/shwap/row_id.go
- share/shwap/row_id_test.go
- share/shwap/row_namespace_data_id.go
- share/shwap/row_namespace_data_id_test.go
- share/shwap/sample_id.go
- share/shwap/sample_id_test.go
PR separates Verify and validate functions for shwap id types. The change is crutial to allow server side application to do initial validation on shwapID, that server as requests in shwap, before accessing DAH. Verify is meant to be used only by server, after Validation passed and when there is access to the file.
> feat(shwap): Separate verify and validate for shwap ids

- blob/service.go
- blob/service_test.go
- nodebuilder/blob/blob.go
- nodebuilder/tests/blob_test.go
Resolves #3192 , https://github.com/celestiaorg/celestia-node/issues/3292
> misc(blob/service)!: return empty values in case blobs were not found

- store/cache/accessor_cache.go
- store/cache/accessor_cache_test.go
- store/cache/cache.go
- store/cache/doublecache.go
- store/cache/metrics.go
- store/cache/noop.go
This pull requests adds caching layer that will be used for shwap store.
Based on https://github.com/celestiaorg/celestia-node/pull/3531
> feat(shwap): Add store cache

- nodebuilder/blob/cmd/blob.go
This PR removes the base64 flag and its related functionality as it was completely unused. Additionally, it changes the return type of the commitment to its hex representation.
```
{
"result": {
"height": 1399400,
"commitments": [
"0x21783ed3c1d5e51b0f1772e57bc3c7f81d93506b0652c062b1e7e5c61eb00791"
]
}
}
celestia blob get 1337536 0x42690c204d39600fddd3 0x21783ed3c1d5e51b0f1772e57bc3c7f81d93506b0652c062b1e7e5c61eb00791
{
"result": {
"namespace": "0x42690c204d39600fddd3",
"data": "gm",
"share_version": 0,
"commitment": "0x21783ed3c1d5e51b0f1772e57bc3c7f81d93506b0652c062b1e7e5c61eb00791",
"index": 1
}
}
celestia blob get-all 1337536 0x42690c204d39600fddd3
{
"result": [
{
"namespace": "0x42690c204d39600fddd3",
"data": "gm",
"share_version": 0,
"commitment": …
```
> improvement(blob/cmd): remove base64 representation

- api/gateway/bindings.go
- api/gateway/bindings_test.go
- api/gateway/state.go
- nodebuilder/state/mocks/api.go
- nodebuilder/state/state.go
- nodebuilder/state/stub.go
- state/core_access.go
This PR removes the `state.SubmitTx` endpoint from the RPC, and the `submit_tx` endpoint from the gateway. 
Related: #3348 
This endpoint was never fully documented, and no usage examples exist. 
When creating usage examples after a discussion in #3345 , we realized the endpoint is not very useful at all. In order to use it, you need to construct a transaction, importing app, tendermint... all to then proxy it to an app instance via node anyways. Here is a snippet from @jcstein in the docs tutorial for submitting data.
The example for `celestia-openrpc`/`celestia-node` would essentially be exactly the same, except we build a rpc connection to node instead of a grpc to app. I think it is clear from this example why SubmitTx is too much of a hassle to use, and if users do need this …
> refactor(state/gateway)!: remove SubmitTx endpoint from RPC and Gateway

- blob/service.go
Refs #3335 
Attempts to create more accurate doc/comments on Get and GetProof in `blob/service.go` to improve legibility and comprehension of how these methods behave to API consumers
specifically cc @vgonkivs
> docs(blob): update godoc comments to better match what Get and GetProof actually do

- pruner/find.go
- pruner/service.go
- pruner/service_test.go
We were resetting `maxHeadersPerLoop` to a different value (`1024`) which has no relations to the default value (`512`). Which isn't that bad because it's a test but still we have a side-effect in the `TestPrune_LargeNumberOfBlocks` test.
Also, changing type of `maxHeadersPerLoop` to `int` 'cause in most places we use it as an `int` and not `int64`.
> refactor(pruner): reset maxHeadersPerLoop properly

- .goreleaser.yaml
Changes goreleaser.yml config to ensure that tags/releases are not automatically promoted to latest by adding the `release.prerelease = auto` config (previously defaulted to false), also set a proper pre-release suffix for tag filtering etc. This allows us to create signed binaries for pre-releases/release candidates.
Tested on a private branch and ensured that with  `release.prerelease: auto` releases created in github and with the toggle "Set as a pre-release" set to true, goreleaser would NOT set them as latest upon publishing artifacts.
> fix(ci/release): golreleaser pre-release behavior

- Makefile
basic and i just want to close the ticket really, but this fixes #1379 where we were incorrectly passing `-m` vs `--m` to cfmt, hence the discrepancy, also we allow 120 length in golangci hence why there is a difference between `make lint` and golangci-lint not finding same issue cc @distractedm1nd
> ci(lint): correct cfmt argument in make lint

- share/eds/eds.go
- share/eds/store.go
- share/new_eds/accessor.go
- share/new_eds/close_once.go
- share/new_eds/close_once_test.go
- share/new_eds/proofs_cache.go
- share/new_eds/rsmt2d.go
- store/cache/accessor_cache_test.go
- store/cache/noop.go
- store/file/ods.go
- store/file/q1q4_file.go
- store/store_test.go
In https://github.com/celestiaorg/celestia-node/pull/3545, I requested to rename `DataHash` to `DataRoot` to match the name of the original name in the Core's RawHeader. However, I realized it is called `DataHash` in the header, so this PR reverts that change. I think this confusion comes from the fact that we are always referring to this field as `DataRoot` in our discussions, so it feels like this is the correct phrasing, but it's not. 
It actually does not matter how it's called, honestly, and both are correct in some way, but it's good to be consistent in the code and avoid confusion with tautology.
> refactor(shwap): revert DataRoot -> DataHash

- nodebuilder/p2p/routing.go
Resolves https://github.com/celestiaorg/celestia-node/issues/3574
Potentially targets https://github.com/celestiaorg/celestia-node/issues/3573
> fix(nodebuilder/p2p): LNs restricted to acting as DHT clients *only*

- share/eds/edstest/testing.go
- share/new_eds/accessor.go
- share/new_eds/close_once.go
- share/new_eds/close_once_test.go
- share/new_eds/nd.go
- share/new_eds/nd_test.go
- share/new_eds/proofs_cache.go
- share/new_eds/rsmt2d.go
- share/new_eds/testing.go
- share/root.go
- share/shwap/row_namespace_data_test.go
- store/cache/accessor_cache_test.go
- store/cache/noop.go
- store/file/ods.go
- store/file/ods_test.go
- store/file/q1q4_file.go
- store/file/q1q4_file_test.go
- store/store.go
- store/store_test.go
Add axis roots to all Accessor implementations. It will allow server side to handle namespace requests without the need to know exact rowIdxes beforehand.
> feat(shwap): Add axis roots to Accessor

- store/file/ods.go
- store/file/q1q4_file.go
- store/store_test.go
Use buffered write of eds shares and axis roots to the disk. According to benchmark it improves write time for writing single block from 79ms -> 19ms (4x).
> feat(shwap): Add bufferisation for writing ods/Q1Q4 files

- share/shwap/p2p/bitswap/getter.go
- share/shwap/p2p/bitswap/getter_test.go
Implements new `Getter` over Bitswap p2p composition.
This PR does not intend to implement unit tests for the Getter itself. Adding them here is not trivial as we don't have the `Getter` test suite, which will soon be replaced with the `Accessor` interface. The current coverage of every `Block` is sufficient to prove every method works while `Getter` itself is simply an adapter. We need this `Getter` _temporary_ to accelerate testing of `Shwap` and replace it with an `Accesor` once we allocate time for refactorings.
> feat(shwap/p2p): Bitswap Getter

- blob/service.go
- blob/service_test.go
- header/headertest/testing.go
- nodebuilder/blob/blob.go
- nodebuilder/blob/module.go
- state/core_access.go
- state/tx_config.go
Introduces `blob.Subscribe`. Takes a `share.Namespace`, returns a `<-chan *BlobsubResponse` containing a `height uint64` and `blobs []*blob.Blob`. 
I made the decision to not support subscribing to multiple namespaces with one call, because the complexity of the return type mitigates the benefits for the client. It is likely more convenient to have one subscription per namespace:
Imagine you are watching two namespaces for different things. On the client side, you would have a `select` statement reading from the two channels in two cases. This is cleaner than receiving everything in one case, but then having to manually parse and send to the respective handlers yourself.  
This closes #2737 , with the caveat that we are not taking the map approach (see rationale above)
> feat(blob): blobsub

- core/eds.go
- core/exchange.go
- core/exchange_test.go
- core/listener.go
- core/listener_no_race_test.go
- core/listener_test.go
Adds core integration. We need to call store.Put for empty edses now, to ensure heights are linked to empty eds.
> feat(shwap): Shwap core integration

- store/store.go
- store/striplock.go
- No need to put in cache empty eds
- in-mem accessor needs to be closed to release created reference in cache.
> fix(shwap): don't cache empty eds and close recent accessor

- blob/blob.go
- blob/blob_test.go
- nodebuilder/blobstream/data_root_tuple_root.go
Added a `Length()` method to the Blob struct that helps to determine the number of the shares in the blob.
> feat(blob): implement length method

- das/coordinator.go
- das/coordinator_test.go
- das/daser.go
- das/daser_test.go
- das/worker.go
- header/headertest/fraud/testing.go
Add shwap integration to DASer
> feat(shwap): update daser for shwap

- header/headertest/verify_test.go
Verification for headers coming via backward sync should be verified properly. So, literally what title says.
> testing(header): extend `ExtendedHeader.Verify` test with older headers

- libs/utils/address.go
- libs/utils/address_test.go
- nodebuilder/core/config.go
- nodebuilder/core/config_test.go
Refs #3570 and I believe solves the issue well enough
previously, on start, node would resolve DNS hostnames to IP when validating. This is somewhat legitimate and necessary when building multiaddr format, but the same code was being used for configuring http clients for RPC/gRPC connections. 
This meant, that in the event of some server administration or an incident, if DNS was updated for a "core" node (as configured via `--core.ip`) this meant a long running node would suddenly lose it's destination and get stuck failing and retrying. 
Instead, this seeks to separate validation, for validating --core.ip for rpc/grpc clients do NOT resolve to IP on start/validate, then should make requests over the DNS using hostname, meaning a core node moving, should eventually resolve again properly, …
> fix(libs/utils): rely on DNS for rpc/grpc requests to core

- go.mod
- go.sum
- nodebuilder/p2p/host.go
0.36.0 [was retracted](https://github.com/libp2p/go-libp2p/commit/16a27ff08cfda4ec780e6dd69e178a2031adbeab)
> deps: bump libp2p(again)

- go.mod
- share/shwap/p2p/bitswap/bitswap.go
- share/shwap/p2p/bitswap/block_fetch.go
- share/shwap/p2p/bitswap/block_fetch_test.go
This PR abstracts away Bitswap parameterization and provides simple constructors optimally configured for Shwap protocol composition.
> feat(shwap/bitswap): Shwap optimized Bitswap constructors

- store/cache/accessor_cache.go
- store/store.go
- store/store_cache_test.go
- Force close Accessor if not closed within timeout
- Close Accessor and log Error if ref was removed by GC instead of user
- close Accessor on has check hitting the cache
> feat(shwap): Improve eds store cache refcounter forgot Close() protection

- blob/commitment_proof.go
- blob/helper_test.go
- blob/service.go
- core/header_test.go
- go.mod
- go.sum
- header/header.go
- header/headertest/validate_test.go
- nodebuilder/blobstream/module.go
In preparation for V2, we should change the header validation logic to ensure that we support validation for V2 and below.
> refactor(header): `Validate` should check that the raw header's app version is not greater than latest app version

- nodebuilder/p2p/bitswap.go
Decoupled client was not able to notify server on newly available blocks.
> fix(p2p): couple bitswap client and server

- nodebuilder/p2p/bootstrap.go
This is a non-breaking change to make the domain name more consistent.
The old DNS is still pointing to the nodes.
> feat: mocha update DNS of BN bootstrapper

- share/eds/edstest/testing.go
- share/new_eds/proofs_cache.go
- share/new_eds/read.go
- share/new_eds/rsmt2d.go
- share/new_eds/share_reader.go
- share/new_eds/share_reader_test.go
- share/new_eds/testing.go
- share/share.go
- share/shwap/p2p/shrex/shrexeds/client.go
- store/file/header.go
- store/file/ods.go
- store/file/q4.go
- store/file/square.go
Implements tail padding share trimming a.k.a. compression with supporting changes. The actual trimming logic turned out extremely simple and does not even require any form of indexing. (896bdd3211dc36ede3209a66b35888f996a5d8bc)
This PR is reviewable commit-by-commit and is supposed to merge as so.
Depends on #3643
> feat(shwap/ods_file): tail padding trim

- .goreleaser.yaml
I expect your goreleaser-check CI workflow to start failing soon. See this [deprecation notice](https://goreleaser.com/deprecations/#snapshotname_template).
Related: https://github.com/celestiaorg/celestia-app/pull/3795
> ci: fix goreleaser check deprecation warning

- share/eds/cache/accessor_cache.go
- Force close Accessor if not closed within timeout
> fix(store/cache): force close Accessor if not closed within timeout

- .github/workflows/go-ci.yml
- share/eds/blockstore.go
Adds lint imports check to CI to ensure imports order is correct. Found by failed lint locally, that was green in ci.
> chore(ci): add lint imports ci action

- .github/workflows/go-ci.yml
- .golangci.yml
- core/exchange.go
- nodebuilder/rpc/flags_test.go
- share/eds/retriever_test.go
- share/eds/utils.go
- share/getters/getter_test.go
- share/ipld/get_shares_test.go
Bump linter and fix errors caused by upgrade.
> chore(lint): bump golang-ci lint to 1.60

- .github/workflows/ci_release.yml
- Dockerfile
- README.md
- go.mod
- go.sum
Bump golang build version to newest 1.23
Depends on https://github.com/celestiaorg/celestia-node/pull/3677
> chore: bump bump go to 1.23

- store/file/ods.go
- store/file/q4.go
We don't need manual FS syncs. The underlying FS decides when to flush its internal buffers. If the FS fails to write to disk after we finish writing to it, it's a bug on the FS side. Also, during historical block sync, manually syncing files per every block to FS will apply a performance penalty for no good reason.
Also, after #3679, files become immutable, meaning we can safely do delayed writes in FS by avoiding `Sync`
> perf(store/sync): avoid syncing files

- share/p2p/discovery/discovery_test.go
TestDiscovery has been increasingly unstable lately. This fix aims to make it stable
> fix(share/discovery): fix TestDiscovery test

- go.mod
Use toolchain version instead of golang version in go.mod. It will allow auto-upgrade of toolchain by compiler.
> chore(go.mod): use toolchain version in go.mod

- nodebuilder/p2p/config.go
- nodebuilder/p2p/module.go
- nodebuilder/p2p/routing.go
- nodebuilder/share/p2p_constructors.go
- nodebuilder/tests/helpers_test.go
- share/shwap/p2p/discovery/dht.go
- share/shwap/p2p/discovery/discovery.go
- share/shwap/p2p/discovery/discovery_test.go
- share/shwap/p2p/shrex/peers/manager_test.go
Add versioning for discovery, so we can separate shwap network from older one. Metrics will still use tag instead of topic, so we can support multiple visions with same dashboard
> feat(shwap): Add discovery version

- share/shwap/p2p/bitswap/bitswap.go
Otherwise, it has additional `/` e.g. `//celestia/private/shwap/ipfs/bitswap/1.2.0`
> fix(shwap/bitswap): correct protocol id

- share/shwap/eds_id.go
- share/shwap/eds_id_test.go
- share/shwap/namespace_data_id.go
- share/shwap/namespace_data_id_test.go
- share/shwap/p2p/bitswap/block.go
- share/shwap/p2p/bitswap/block_fetch.go
- share/shwap/p2p/bitswap/block_test.go
- share/shwap/p2p/bitswap/cid.go
- share/shwap/p2p/bitswap/row_block.go
- share/shwap/p2p/bitswap/row_namespace_data_block.go
- share/shwap/p2p/bitswap/sample_block.go
- share/shwap/row_id.go
- share/shwap/row_id_test.go
- share/shwap/row_namespace_data_id.go
- share/shwap/row_namespace_data_id_test.go
- share/shwap/sample_id.go
- share/shwap/sample_id_test.go
We need to check that requested ID is equal to received ID.
This was the case, but implicitly in the Bitswap layer.
This change adds another explicit check for that, ensuring IDs are printed on error
> feat(shwap): check ID equality

- store/file/ods_q4.go
Opened bool was stored before actual value of q4 was updated, which made it possible for concurrent reader to read nil value before it was updated.
Alternatively code can be refactored to use RWMutex instead of Mutex+atomic.Bool, which can improve readability of logic.
> fix(store/odsq4): fix order of opened flag stored

- share/eds/testing.go
- store/file/ods_q4_test.go
- store/file/ods_test.go
Various accessor tests improvements:
- added empty file to test suite
- test Shares in parallel
- added randomised test for samples
- removed file references from tests
- add support for createAccessor func in benchmarks
> refactor(share/eds): various accessor testing suite improvements

- blob/service_test.go
Subscription can be not immediately canceled. This due to the fact that select can choose either of cases of ctx.Done() and sending message.
> fix(blob): fix blobsub subscription cancellation test

- store/store.go
There is limitation on max amount of hard links in ext4 filesystem of 65000. Some chains have more empty blocks (arabica). We will use symlinks for empty blocks to avoid this limitation, while keeping hard-links for non-empty blocks.
> fix(store): use symlinks for empty blocks heighs

- core/eds.go
- header/headertest/fraud/testing.go
- libs/edssser/edssser.go
- share/availability/full/availability.go
- share/availability/full/availability_test.go
- share/shwap/p2p/shrex/shrex_getter/shrex_test.go
- share/shwap/p2p/shrex/shrexeds/exchange_test.go
- share/shwap/p2p/shrex/shrexnd/exchange_test.go
- store/getter_test.go
- store/metrics.go
- store/store.go
- store/store_cache_test.go
- store/store_test.go
Avoid storing q4 for data outside of availability window
> feat(share/availability): Dont store q4 on archival

- store/cache/accessor_cache.go
- store/cache/accessor_cache_test.go
- store/cache/cache.go
- store/cache/doublecache.go
- store/cache/noop.go
- store/store_cache.go
- store/store_cache_test.go
With Bitswap moving to using blockstore.Has soon, we need a way to check if the Accessor is present on the cache before reading the disk and this change does exactly that.
> feat(store/cache): add Has methods

- cmd/celestia/main.go
- go.mod
Set go:debug directive  "asynctimerchan=1" until https://github.com/golang/go/issues/69312 is fixed.
> Chore(fix): set asynctimerchan=1 on build

- .github/workflows/integration-tests.yml
- nodebuilder/tests/prune_test.go
Prunning test has been running with every other test in ci. This PR will separate running pruning test from other tests
> fix(ci): Run pruning integration test separately in ci

- cmd/flags_misc.go
- nodebuilder/p2p/host.go
- nodebuilder/p2p/metrics.go
This PR fixes the bug of prometheus registry not being provided to libp2p constructor as well as few additional improvements of adjustment code:
- provide Registrer to libp2p if flag is enabled
- clarify telemetry enabling flag names and avoid overwrites
> fix(nodebuilder/host): Ensure libp2p metrics are collected to prometheus

- go.mod
- nodebuilder/p2p/bitswap.go
- nodebuilder/p2p/metrics.go
Bitswap metrics are initialised inside constructors and require prometheus to be injected before the call. This PR enforces initialisation order:
1. set prometheus global Registrer
2. inject bitswap metrics fabric
3. set bitswap component scope though ctx
4. init bitswap components
> fix(nodebuilder/p2p/metrics): enforce init order for bitswap metrics

- cmd/cel-key/node_types.go
- cmd/flags_node.go
- nodebuilder/store.go
- nodebuilder/store_test.go
This mainly fixes the usage of `CELESTIA_HOME` env var. Previously, it worked like `XDG_HOME` in the form of `$CELESTIA_HOME/.celestia-<network>-<type>`. This change makes `$CELESTIA_HOME` the actual path to which node data goes.
This is promoted by me logging into the pods on Robusta and being tired of constantly passing the `--node.store` flag while `CELESTIA_HOME` is already set. 
---
Besides, it contains a minor refactor to use respective types for node and network instead of strings.
> fix(node): fixup CELESTIA_HOME

- .github/workflows/docker-build-publish.yml
This PRs shows how to use the new input for the docker ci workflow added in https://github.com/celestiaorg/.github/pull/112
This would allow triggering the docker workflow on a tag that (such as the new arabica and mocha tags) that didn't trigger the workflow originally.
> chore(ci): add workflow dispath to docker ci to manually trigger

- core/listener.go
Previously we observed panic with `leveldb: closed` in integration tests. It was caused by core.listener accessing already closed core block generator. The reason for it could be leaked listener subscriber routine after node is closed, that was trying to access generator. 
The PR introduces graceful shutdown for listener, that will wait for spawned routines to stop before exiting.
> fix(core/listener): wait listener to shutdown before exit

- nodebuilder/share/p2p_constructors.go
I realized by seeing logs that the archival tag and version weren't rearranged in #3777
> fix(modshare): discovery leftover from #3777 

- go.mod
- go.sum
Upgrade to https://github.com/celestiaorg/celestia-app/releases/tag/v2.2.0-mocha
v2.2.0-arabica has baked on Arabica since Thursday and no new issues reported.
> chore(deps): upgrade to v2.2.0-mocha

- blob/blob.go
- blob/parser.go
- blob/service.go
- blob/service_test.go
Closes https://github.com/celestiaorg/celestia-node/issues/3629
> feat: keep using the namespace proof for GetBlob and GetAll

- docker/entrypoint.sh
When using port forwarding in docker, you need to use the `any` address interface `0.0.0.0` otherwise you would be able to communicate to the server inside the container. 
This PR updates the `entrypoint.sh` file to set the RPC and Gateway addresses to `0.0.0.0` so that developers can properly communicate to the node when exposing ports, for example `-p 26658:26658`.
> fix(docker): set addr flags to 0.0.0.0 in entrypoint file

- logs/logs.go
Bitswap decision engine has certain important logs for us and node operators to keep in mind, thus the change.
Like https://github.com/ipfs/boxo/blob/ceb514cc23b0c60494ddac6579dae3829459cb93/bitswap/server/internal/decision/engine.go#L727
> chore(logs): increase verbosity for bitswap log

- store/store.go
- store/store_test.go
In case of unexpected shutdown file might be partially written, while link is not. This PR will ensure we that put will result in both link and file on success.
File validation will be tackled in another PR
> fix(store): check if link exists on write

- share/ipld/nmt_adder.go
Previous prealloc calc was incorrect resulting in higher allocation than needed. This is chart of amount of allocation we should have done and actually done:
```
eds size; needed alloc; real alloc
2 3 4
4 7 24
8 15 112
16 31 480
32 63 1984
64 127 8064
128 255 32512
256 511 130560
512 1023 523264
```
Fixes https://github.com/celestiaorg/celestia-node/issues/3858
> fix(eds/cache): Fix prealloc for proof nodes

- store/file/ods_q4.go
TLDR: It was possible to return with error before reading from channel. Which could lead to leak of q4 writing go-routine.
Fixed a race condition when writing/removing the Q4 file. The main go-routine wasn’t waiting for the Q4 write to finish, causing the file to be removed before the write completed. This could leave unpredictable data on disk after the removal. These changes ensure the write operation finishes before any removal is attempted.
> fix(store/file): wait for q4 to be written before returning

- api/gateway/availability.go
- api/gateway/share.go
- nodebuilder/node_test.go
- nodebuilder/share/cmd/share.go
- nodebuilder/share/mocks/api.go
- nodebuilder/share/share.go
- nodebuilder/tests/nd_test.go
- nodebuilder/tests/prune_test.go
- nodebuilder/tests/reconstruct_test.go
- nodebuilder/tests/sync_test.go
Use height instead of header in share module API
> !refactor(api/share): use height in share module

- state/core_access.go
This resolves #3884, reversing order of variables in error message.
Tested, and it works as expected now:
```bash
./build/celestia light start --core.ip rpc-mocha.pops.one
Error: node: failed to start: wrong network in core.ip endpoint, expected celestia, got mocha-4
```
> fix: wrong network error

- share/share.go
> chore(share): remove unused ShareWithProof

- share/availability/light/availability.go
- Fix ctx canceled error being returned before sampling result is persisted.
- Store Put error should be propagated to the caller, to allow retry of sampling for the same height.
> fix(share/availability): propagate errors from light availability properly

- .github/workflows/ci_release.yml
We don't want automatic version bump 'cause we do this manually and do it well.
> fix(ci): do not version_bump

- share/shwap/p2p/shrex/shrexeds/server.go
- share/shwap/p2p/shrex/shrexnd/server.go
middleware was unused. Most likely shwap rebase on main artefact
> fix(shwap/shrex): enable recovery middleware in shrex server

- share/availability/light/availability.go
- share/availability/light/availability_test.go
- share/availability/light/sample.go
Store coordinates of successful sampling calls
> feat(share/availability): Store success results for light availability

- nodebuilder/tests/blob_test.go
Added test case to cover BlobV1
> test(swamp): cover v1 blobs in swamp tests

- api/gateway/share.go
- blob/service.go
- blob/service_test.go
- nodebuilder/da/mocks/api.go
- nodebuilder/share/cmd/share.go
- nodebuilder/share/share.go
- nodebuilder/tests/nd_test.go
- share/availability/light/availability_test.go
- share/shwap/getter.go
- share/shwap/getters/cascade.go
- share/shwap/getters/mock/getter.go
- share/shwap/getters/testing.go
- share/shwap/p2p/bitswap/getter.go
- share/shwap/p2p/shrex/shrex_getter/shrex.go
- share/shwap/p2p/shrex/shrex_getter/shrex_test.go
- store/getter.go
- store/getter_test.go
> !refactor: rename GetSharesByNamespace to GetNamespaceData

- .github/workflows/docker-build-publish.yml
hello!
bumping version to: https://github.com/celestiaorg/.github/releases/tag/v0.5.0
best!
> ci(docker): bump version

- go.mod
- go.sum
bumps to celestia-app v3.0.0-mocha. there is only a single breaking change compared to v3.0.0-rc0 / v3.0.0-arabica. This only has an effect on the state machine of the arabica-11 network. The rest of the diff is only from docs / tests.
> chore: bump to celestia-app v3.0.0-mocha

- api/docgen/exampledata/extendedHeader.json
- header/header.go
Fixes https://github.com/celestiaorg/celestia-node/issues/3918
**Please note: this PR is BREAKING** as header encoding has changed.
> fix(header)!: tendermint compatible json marshall

- blob/blob.go
Closes https://github.com/celestiaorg/celestia-node/issues/3356
Removes an unnecessary conditional because of [this comment](https://github.com/celestiaorg/celestia-node/issues/3356?notification_referrer_id=NT_kwDOADhxZ7MxMDQ5ODY2MzI4NDozNjk5MDQ3#issuecomment-2471477558).
> refactor: remove blob size check

- core/exchange.go
The `Data` field of `core.ResultSignedBlock` was retained even after we constructed the respective header and moved on. This was due to the header consisting of pointers pointing to fields of `core.ResultSignedBlock`, retaining the whole structure, including the `Data` field. A BN, by default, has a header store cache of size 4096; thus, holding on `Data` with 8 MB blocks took around 32GiB of RAM.
Initially, we believed that the issue was with JSON unmarshalling. However, we were wrong about this being the whole story, as while profiles did confirm that the allocations did originate there, the allocated data wasn't cleaned up.  Kudos to @rach-id for helping us figuring this out!
This is a hotfix and is meant to be replaced with a better solution described on TODO. Also, the origin of this …
> hotfix(core): don't hold on Data

- nodebuilder/p2p/addrs.go
- nodebuilder/p2p/host.go
quic has been unstable lately as a transport. This PR disables quic and web transport support temporary until all related issues are resolved and tested.
> fix(p2p): disable quic

- go.mod
- go.sum
- share/shwap/p2p/bitswap/bitswap.go
Yet another change to the bitswap configuration
* Adds `MinTimeout`. 
* Robusta was having hard times with tail latency being too long, skewing timeout estimations, and causing cascade of simulated DONT_Haves that aren't real.
* Basically only needed on low-latency envs like robusta.
* Reverts wantlist limit for peers to 4096
* We observed limit overflow with FN syncing over bitswap. The overflow wasn't reached in any subsequent runs after the limit was raised back
> fix(shwap/bitswap): update boxo and config

- go.mod
- go.sum
Bumps fork to fix the last known nasty leak in bitswap.
The fix is in this commit: https://github.com/celestiaorg/boxo/commit/70a650316c3b9e4734df0bcb79ea8e530d86aae8
> chore(go.mod): bump boxo fork

- share/availability/light/availability.go
- share/availability/light/availability_test.go
Fixes #3943 
Another PR will come later which optimises the request for the single-share-square case :)
> fix(share/availability/light): Allow retries on ODS size 1

- share/shwap/p2p/bitswap/getter.go
- share/shwap/p2p/bitswap/getter_test.go
In the Robusta environment this change:
* Improved load distribution across BN/FNs
* Sped up sampling
Originally, I was testing Bitswap with this change but decided against including it in the patch, as it is solely an optimization. However, without this change on the rc tag, load distribution was rather strange. One LN sampled at 180/s, while all 4 others at 4/s. Adding pooling fixed the issue and resulted in all 5 LNs at about 100/s.
> perf(shwap/bitswap): add session pools inside Getter

- .github/workflows/ci_release.yml
Do not allow goreleaser to automate tagging of releases - we always do this manually.
> fix(.github/workflows): no automatic tagging of releases for CI

- api/rpc/perms/permissions.go
- api/rpc_test.go
- cmd/auth.go
- cmd/rpc.go
- libs/authtoken/authtoken.go
- nodebuilder/node/admin.go
- nodebuilder/node/cmd/node.go
- nodebuilder/node/node.go
- nodebuilder/tests/helpers_test.go
> fix: jwt token nonce and expiration time

- core/eds.go
- go.mod
- go.sum
Upgrade to the latest celestia-app release: https://github.com/celestiaorg/celestia-app/releases/tag/v3.0.2
Please LMK if you want me to manually backport this to release branches (i.e. release/v0.20)
> chore(deps): upgrade to celestia-app v3.0.2

- .goreleaser.yaml
```
git:
#
tag_sort: -version:creatordate
```
https://goreleaser.com/customization/git/
> fix(goreleaser): tag_sort

- nodebuilder/pruner/module.go
Enforces pruning for LNs by default.
Resolves https://github.com/celestiaorg/celestia-node/issues/3505
> nodebuilder/pruner: Enforce light pruning 

- share/availability/window.go
This trick allowed me to reuse an old 8mb snapshot, even though it is already far beyond the availability window. I think it is helpful to add it to main.
> feat(availability): env var to disable pruning

- share/availability/light/availability.go
Initially reported as panic by @Wondertan 
```
fatal error: concurrent map iteration and map write goroutine 424607 [running]: [github.com/ipfs/go-datastore/autobatch.(*Datastore).Flush(0xc0015ff300](http://github.com/ipfs/go-datastore/autobatch.(*Datastore).Flush(0xc0015ff300), {0x3aacc20, 0xc00bb3b340}) /go/pkg/mod/github.com/ipfs/go-datastore@v0.6.0/autobatch/autobatch.go:108 +0xa5 [github.com/ipfs/go-datastore/autobatch.(*Datastore).Put(...)](http://github.com/ipfs/go-datastore/autobatch.(*Datastore).Put(...)) /go/pkg/mod/github.com/ipfs/go-datastore@v0.6.0/autobatch/autobatch.go:67 [github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).SharesAvailable(0xc00050ba40](http://github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).Sh …
```
> fix(share/availability): add missing protection for autobatch

- core/eds.go
- core/exchange.go
- core/exchange_test.go
- core/listener.go
- core/option.go
- das/daser.go
- das/daser_test.go
- das/options.go
- das/worker.go
- nodebuilder/das/constructors.go
- nodebuilder/pruner/module.go
- share/availability/full/availability.go
- share/availability/full/availability_test.go
- share/availability/full/options.go
- share/availability/light/availability.go
- share/availability/light/availability_test.go
- share/availability/light/options.go
- share/availability/window.go
This PR makes the concept of `archival` node explicit, splitting it away from sampling window. Now, both the node's pruning status (archival or not) and the sampling window will have to be provided to availability implementations for them to determine what to sync + what to store. This also applies to `core` package for BNs as that's their "availability implementation" technically.
> refactor(share/availability/light | share/availability/full): Availability implementations are aware of sampling window, removed from DASer

- nodebuilder/blob/cmd/blob.go
> fix(cmd/blob): fix namespace parsing in cli

- Makefile
- README.md
- celestia-node.mk
Alternative to #3973 
Sharing the command line help: 
```sh
make node-help
Celestia Light Node Management Commands:
Available targets:
node-install        - Install celestia node and cel-key binaries
get-address        - Display the wallet address from cel-key
check-and-fund     - Check wallet balance and request funds if needed
reset-node         - Reset node state and update config with latest block height
light-arabica-up   - Start the Celestia light node
Special usage:
light-arabica-up options:
COMMAND=again    - Reset the node before starting
CORE_IP=<ip>     - Use custom IP instead of default validator
Examples:
make light-arabica-up
make light-arabica-up COMMAND=again
make light-arabica-up CORE_IP=custom.ip.address
make light-arabica-up COMMAND=again CORE_IP=custom.ip.address
```
> chore/make: add celestia-node make file for arabica testnet

- share/eds/rsmt2d.go
- share/shwap/row.go
- share/shwap/row_test.go
Adds new `Both` `RowSide` indicating that Row is "complete"  and keeps both the `Left` and the `Ride` sides. The `Shares` method now caches the decoded share and automatically converts `Row` to `Both`
It should be merged before #4002 so that JSON serialization contains the entire row and avoids _expensive_ compute duplicatation.
Closes #3984
> perf(shwap): cache Both Row sides

- nodebuilder/da/service.go
> fix(nodebuilder/da): remove random print

- nodebuilder/share/mocks/api.go
- nodebuilder/share/share.go
- share/availability/light/availability_test.go
- share/shwap/getter.go
- share/shwap/getters/cascade.go
- share/shwap/getters/mock/getter.go
- share/shwap/getters/testing.go
- share/shwap/p2p/bitswap/getter.go
- share/shwap/p2p/shrex/shrex_getter/shrex.go
- share/shwap/row.go
- share/shwap/row_test.go
- store/getter.go
- store/getter_test.go
- xtoken.json
closes https://github.com/celestiaorg/celestia-node/issues/3981
> feat(modshare): implement GetRow

- nodebuilder/p2p/addrs.go
- nodebuilder/p2p/host.go
This reverts commit e6dbb54dd28462c2820ae455295acc856af92b64 as https://github.com/quic-go/quic-go/issues/4712 is solved and fixed. It's not yet released, but the bug is not critical to block on it.
> Revert "fix(p2p): disable quic (#3937)"

- nodebuilder/p2p/cmd/p2p.go
- nodebuilder/p2p/mocks/api.go
- nodebuilder/p2p/p2p.go
- nodebuilder/p2p/p2p_test.go
Yet another helpful p2p debugging endpoints with respective commands:
* Ping tries to reach a peer by its peer id
* ConnectionState provides information about active connection for a peer by its ID
> feat(modp2p): Ping and ConnectionState APIs

- share/shwap/p2p/bitswap/getter.go
`archivalPool` ctx for bitswap session was never set, leading to a panic when tracing begins inside the bitswap session that is created for archival requests.
```
panic: cannot create context from nil parent
goroutine 3130 [running]:
context.WithValue({0x0?, 0x0?}, {0x103cbe2e0?, 0x103ad0f20?}, {0x1041e48a0?, 0x14004d89a40?})
/opt/homebrew/opt/go/libexec/src/context/context.go:715 +0x140
go.opentelemetry.io/otel/trace.ContextWithSpan(...)
/Users/rene/go/pkg/mod/go.opentelemetry.io/otel/trace@v1.31.0/context.go:14
go.opentelemetry.io/otel/internal/global.(*tracer).Start(0x14006998cd0, {0x0, 0x0}, {0x14004f9a558?, 0x102e7c26d?}, {0x0?, 0x102e7febf?, 0xa?})
/Users/rene/go/pkg/mod/go.opentelemetry.io/otel@v1.31.0/internal/global/trace.go:143 +0x148 …
```
> fix(share/shwap/p2p/bitswap): set archivalPool ctx

- nodebuilder/core/flags.go
- nodebuilder/core/flags_test.go
> misc!(flags): rename core.grpc.port to core.port

- go.mod
- go.sum
Fix nil panic https://github.com/celestiaorg/go-header/releases/tag/v0.6.4
> deps(go.mod): bump go-header v0.6.4

- nodebuilder/pruner/flags.go
Change archival mode warning message.
> fix(nodebuilder/pruner): Change archival mode warning message

- core/fetcher.go
- core/fetcher_test.go
> fix(core/fetcher): resubscribe if consensus node goes offline

- nodebuilder/blob/cmd/blob.go
Resolves #4106 
Tested with:
```
celestia version
Semantic version: v0.11.0-rc9-738-g1e51c5f4
Commit: 1e51c5f45afd9487270600bc0a215e00b4d72e6b
Build Date: Tue Feb 11 16:54:41 EST 2025
System version: arm64/darwin
Golang version: go1.23.5
```
get:
```
celestia blob get 3980857 0xa2a78ada26ac2cbf1e86 0xeb01be57cb96f99b03e49c599e0d9f2fc08b389f49e4e8a4a273ef8a7ceb14b4
{
"result": {
"namespace": "0xa2a78ada26ac2cbf1e86",
"data": "\u001bj\u000f\u0000d\<redacted-for-brevity>",
"share_version": 0,
"commitment": "0xeb01be57cb96f99b03e49c599e0d9f2fc08b389f49e4e8a4a273ef8a7ceb14b4",
"index": 16
}
}
```
get-proof:
```
celestia blob get-proof 3980857 0xa2a78ada26ac2cbf1e86 0xeb01be57cb96f99b03e49c599e0d9f2fc08b389f49e4e8a4a273ef8a7ceb14b4
{
"result": [
{
"end": 4,
"nodes": [ …
```
> fix: cli with malformed height

- share/shwap/p2p/shrex/peers/manager.go
If pool was removed during request it could lead to unexpected panic in client.
> fix(share/peer-manager): fix potential nil dereference in peer manager

- nodebuilder/core/constructors.go
Increase message size to 64Mb for the grpc client
Tested on mainnet light node. 
square size = 128(8mb block)
Actual response size = 10,85mb
> improvement(core): increase message size to 64Mb

- nodebuilder/p2p/cmd/p2p.go
The new [time.DateTime]((https://pkg.go.dev/time@go1.20#pkg-constants) ) constant added in Go 1.20 can improve code readability.
> refactor: use `time.DateTime` constant from standard library

- go.mod
- go.sum
To pick up this fix: https://github.com/celestiaorg/go-square/pull/141
> chore(deps): upgrade to go-square v2.2.0

- Makefile
- nodebuilder/tests/blob_test.go
I noticed that some files are not formatted with `make fmt`.
> chore: fix formatting

- nodebuilder/p2p/bootstrap.go
Now, all Bootstrappers are bridge nodes. Doing that we renamed the domains of the Boostrappers.
(Note: Bootstrappers will be reachable via the old domain until this PR is part of a release.)
> chore(bootstrappers): rename bootstrappers

- store/cache/metrics.go
> fix!(store/metrics): fix metrics prefix

- core/listener.go
- share/shwap/p2p/discovery/discovery.go
**Go 1.23 Timer Behavior Change**
Go 1.23 introduced changes to the behavior of `Timer` that affect how channels should be handled:
1. **No need to drain the channel before `Reset`**  
```go
// For a chan-based timer created with NewTimer, as of Go 1.23,
// any receive from t.C after Reset has returned is guaranteed not
// to receive a time value corresponding to the previous timer settings;
// if the program has not received from t.C already and the timer is
// running, Reset is guaranteed to return true.
// Before Go 1.23, the only safe way to use Reset was to [Stop] and
// explicitly drain the timer first.
```
2. **Draining after `Stop` will never read a value**  
```go
// For a chan-based timer created with NewTimer(d), as of Go 1.23,
// any receive from t.C after Stop has returned is …
```
> fix(p2p/discovery,core/listener): fix timer deadlock

- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/nd_test.go
- nodebuilder/tests/prune_test.go
- nodebuilder/tests/reconstruct_test.go
- nodebuilder/tests/swamp/swamp_tx.go
- nodebuilder/tests/sync_test.go
Collect and return all submitted heights. 
Some tests were broken at all, so I had to refactor them to make them work. `TestArchivalBlobSync` is still flakey(stuck on `ln.HeaderServ.WaitForHeight` step) and the root cause is not clear rn.
> fix(swamp): collect submitted heights in FillBlocks

- cmd/node.go
This PR introduces a deprecation notice for Full Nodes.  
Full Nodes are no longer actively supported and will be deprecated in upcoming releases. Testing and maintenance of Full Nodes will cease in future updates.
Since the storage backend for Full Nodes and Bridge Nodes is the same, migrating from a Full Node to a Bridge Node is straightforward:
1. **Initialize a New Bridge Node**  
Run `celestia bridge init` (or equivalent) to create a new bridge node directory.
2. **Copy Existing Data from Full Node**  
- Replace the `blocks/`, `data/`, and `keys/` directories/files in the newly created Bridge Node folder with the corresponding ones from your Full Node setup.
- Ensure permissions and ownership remain correct after copying.
This method preserves your existing blockchain data and keys, …
> refactor(nodebuilder): Deprecation of Full Node Support

- Makefile
Closes #4171 
Related https://github.com/celestiaorg/celestia-node/issues/3820#issue-2569998484
This PR fixes the long-standing issue where the `celestia version` command would report an incorrect semantic version when building from certain branches or lightweight tags — such as `v0.21.7-mocha` or `v0.22.1-arabica`.
The problem originated from the use of `git describe`, which only returns annotated tags. As a result, lightweight tags or branch names would fall back to unrelated previous tags (e.g., `v0.21.7-arabica`) or even commit hashes, leading to confusion in development and CI environments.
```make
$ git checkout v0.21.7-mocha
$ make install
$ celestia version
Semantic version: v0.21.7-arabica
Commit: 9c1d27a9c41cf16f7b20e96a556d9601b29b5b3a
Build Date: Thu Mar 13 14:22:07 EDT 2025 …
```
> fix(makefile): ensure correct semantic version is shown for branches

- nodebuilder/p2p/bootstrap.go
Hello team!
In order to release some resources, I removed the bootstrappers 3 & 4. 
We'll add them again if we need them in the future.
Best!
> chore: removing the bootstrapper 3 and 4 from lunar

- .golangci.yml
- nodebuilder/tests/api_test.go
- nodebuilder/tests/blob_test.go
- nodebuilder/tests/da_test.go
- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/helpers_test.go
- nodebuilder/tests/nd_test.go
- nodebuilder/tests/p2p_test.go
- nodebuilder/tests/prune_test.go
- nodebuilder/tests/reconstruct_test.go
- nodebuilder/tests/share_test.go
- nodebuilder/tests/swamp/swamp.go
- nodebuilder/tests/sync_test.go
- share/shwap/p2p/shrex/shrex_getter/shrex.go
While working on #4330, I had to fix swamp tests s.t. I know pruning doesn't break anything. While diving again into swamp, I realized we have a bunch of garbage and unnecessary code that I removed + unified node setup and connections for all the tests. Also, now the integration tests should be **GREEN**.
Also runs these tests in parallel. On my machine, time goes from 122s -> 86s. There is one more test time optimization in #4330 that reduces the number to ~60s
> chore(node/tests): fix and cleanup swamp tests

- go.mod
- go.sum
Bump tendermint replace in node. New core version fixes serialisation issues in tx client and more.
https://github.com/celestiaorg/celestia-core/releases/tag/v1.55.0-tm-v0.34.35
> deps(go.mod): bump tendermint replace

- nodebuilder/blobstream/blobstream.go
- nodebuilder/blobstream/mocks/api.go
- nodebuilder/blobstream/service.go
- nodebuilder/blobstream/service_test.go
Change the return type of the GetDataRootTupleRoot in blobstream service. 
Changed the return type from *DataRootTupleRoot to DataRootTupleRoot, because DataRootTupleRoot is a type alias of byte.HexBytes(which is a type definition for `[]byte`). Since []byte is a reference type, there is no need to return a pointer.
> fix!(blobstream): change GetDataRootTupleRoot return type

- cmd/auth.go
- cmd/config.go
- cmd/init.go
- cmd/node.go
- cmd/reset_store.go
- cmd/start.go
- cmd/util.go
_Please review this PR carefuly_
---------------------------------
I've wanted to do this for a while - we do not need to parse the entire set of flags available for `Init` and `Start` for all other auxiliary commands as they're irrelevant.
This PR decouples this parsing logic into 
`ParseStoreDeterminationFlags` and `ParseAllFlags`
Now, all subcommands will run their own necessary parsing logic. 
This PR fixes a bug found by @vgonkivs where a LN would fatal out on `config-update` subcommand due to unrelated: 
```
celestia light config-update --p2p.network=mocha
2025-08-07T16:23:27.396+0300	FATAL	module/pruner	pruner/flags.go:43	ARCHIVAL MODE ENABLED BY ACCIDENT!!! Please explicitly pass `--archival` to enable archival mode!
```
This PR also only parses pruning flags for the `Bridge` node …
> fix(cmd/celestia): parse only store determination flags for auxiliary commands

- cmd/cel-shed/header.go
`init()` was trying to add commands before variables were ready - Go didn’t like that.
moved `headerStoreReset`/`Recover` earlier, combined the three `init()`s into one, and removed repeated flag setups. 
initialization order is solid now and code reads better.
> chore: fix Go init order + tidy up flags
