- .github/CODEOWNERS
Require @liamsi @Wondertan @renaynay as reviewers for all PRs on this repo until we have package-specific owners.
> .github: add codeowners file

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/vet_fmt_test.yml
- .golangci.yml
Basic go vet/fmt/lint/test jobs
Splitted to 2 files:
- lint only (using golangci-lint)
- vet/fmt/test
> [Issue-31] Setup CI automation through GH actions

- Makefile
The initial version contains such commands:
- help
- format
- lint
- test
> [Issue-37] makefile: creating a Makefile

- docs/adr/adr-001-predevnet-celestia-node.md
After reading through the adr, I've found the small detail to add to complete this wonderful description
> Tiny typo fix for ADR-001

- docs/adr/adr-001-predevnet-celestia-node.md
- docs/adr/adr-002-predevnet-core-to-full-communication.md
According to our adr-templates.md, we should have an id for each of the ADRs.
> Docs: Fix ADRs titles

- go.mod
- go.sum
- node/node.go
- node/p2p/bitswap.go
- node/p2p/ipld.go
- node/p2p/p2p.go
For BlockFetching and DASing to work we need a DAGService from IPFS. This small PR provides it to the Node.
Based on #94 and requires it merged into main together with #86.
> node: provide DAGService

- service/block/fraud_test.go
This PR adds test to check `validateEncoding`.
> service/block: Add table tests to check `validateEncoding`

- node/services/service.go
This PR removes an unused components constructor.
> node/services: remove unused components constructor

- service/block/event_test.go
- service/header/subscription_test.go
> fix flaky TestEventLoop and TestSubscriber

- das/daser.go
- das/daser_test.go
> das: add test for DASer

- node/p2p/p2p.go
A quick fix that I accidentally caught.
> fix(node/p2p): fix MutualPeers reading from Config

- go.mod
- service/header/header.go
- service/header/interface.go
- service/header/store.go
- service/header/store_test.go
- service/header/testing.go
- service/header/verify.go
- service/header/verify_test.go
* Adjacent Headers verification logic
* Basic Validation for ExtendedHeaders
* Updated and simplified Store interface.
* Actual Store implementation
* Height indexer
Closes #150
> service/header: Store implementation 

- node/node.go
during startup of the node, we log the p2p multiaddr of it
Closes #200
> node: add p2p multiaddr log

- das/daser.go
- service/header/subscription.go
> Mainly remove misleading error on node stop

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/change-request.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
> templates: remove Bidon15 as automatic assignee

- CHANGELOG.md
Adds changelog of features and quick description of the first-ever release of celestia-node.
> changelog: add v0.1.0

- README.md
We need this little update for the networks repo readme file
> docs: update readme with installation chapter

- .github/dependabot.yml
Resolves https://github.com/celestiaorg/celestia-node/issues/64
> Copy dependabot.yml from celestiaorg/celestia-core

- CHANGELOG-PENDING.md
- Makefile
- cmd/cel-shed/main.go
- cmd/cel-shed/p2p.go
Start of #276
Tested manually.
> feat(cmd): give a birth to cel-shed and p2p key utilities

- CHANGELOG-PENDING.md
- cmd/flags.go
- cmd/init.go
- cmd/start.go
- node/options.go
Quick PR to add configurability for mutual peers from CLI
> feat(cmd|node): MutualPeers Node option and CLI flag

- .golangci.yml
- CHANGELOG-PENDING.md
- node/store_test.go
In addition, removing nolint in tests
> ci: increase tokens ratio for dupl to fix false positive scenarios

- CHANGELOG-PENDING.md
- service/header/core_listener.go
Quick fix for race
Closes https://github.com/celestiaorg/celestia-node/issues/339
> fix(header/service): #339 race

- CHANGELOG-PENDING.md
- das/daser_test.go
- node/components.go
- node/services/service.go
- service/share/full_availability.go
- service/share/full_availability_test.go
- service/share/light_availability.go
- service/share/share.go
- service/share/share_test.go
- service/share/testing.go
Resolves #179 and https://github.com/celestiaorg/celestia-node/issues/23
> service/share: Implement `FullAvailability`

- CHANGELOG-PENDING.md
> CHANGELOG-PENDING.md: Add `misc` category

- core/client.go
- core/client_test.go
- go.mod
- go.sum
Resolves https://github.com/celestiaorg/celestia-node/pull/289.
> core: Retry remote core client three times before failing out

- das/daser.go
- service/header/core_listener.go
- service/header/core_listener_test.go
> header: fix race in core listener

- CONTRIBUTING.md
Add current contributing guidelines (these will need updating later in the development process)
> CONTRIBUTING.md: Add contributing.md file

- docs/adr/adr-004-state-interaction.md
This PR introduces a new ADR detailing celestia-node's state interaction with celestia-core/app for the March 2022 testnet.
> docs/adr: State Interaction

- core/client_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/400
> core: Remove client retry test

- CHANGELOG-PENDING.md
- service/header/store.go
- service/header/store_heightsub.go
- service/header/store_heightsub_test.go
- service/header/store_test.go
- service/header/sync_test.go
Improved version of HeightSub adapted from https://github.com/celestiaorg/celestia-node/pull/397 and integrated into the Store, instead of Syncer.
Review commit by commit
Closes: https://github.com/celestiaorg/celestia-node/issues/444
> feat(service/header): HeightSub

- service/header/service.go
- service/header/store.go
- service/header/sync.go
Last cleanups before the release, also include cache size changes, again.
Review commit by commit.
> chore(service/header): minor code cleanups

- CHANGELOG-PENDING.md
- CHANGELOG.md
Pay attention to `Highlights` section while reviewing.
> changelog: release notes for v0.2.0

- service/header/core_listener_test.go
- service/header/p2p_subscriber.go
One more attempt to close #453
> tests(service/header): fix flakey TestCoreListener

- CHANGELOG-PENDING.md
- service/header/core_listener.go
- service/header/header.go
- service/header/header_test.go
> header: skip empty blocks

- node/tests/swamp/swamp.go
- node/tests/sync_test.go
- service/header/service.go
- service/header/store_heightsub.go
Depends on #397, #428
Resolves #351 #370
> swamp: Sync sub test with state sync

- cmd/flags_header.go
This was introduced in https://github.com/celestiaorg/celestia-node/pull/455 and was broken in https://github.com/celestiaorg/celestia-node/pull/390. Thanks @Bidon15 for finding this and credits to @vgonkivs for original implementation.
> fix(cmd): return back sliced trusted peers flags and fix usage string

- node/node_bridge_test.go
- node/node_full_test.go
- node/node_light_test.go
- node/testing.go
Just took my broom and put on my cleaning hat.
> refactor|chore(node): new TestNode testing utility and node tests cleanup

- core/client_test.go
- core/fetcher_test.go
- core/testing.go
- go.mod
- node/node_bridge_test.go
- node/node_test.go
- node/testing.go
- node/tests/swamp/config.go
- node/tests/swamp/swamp.go
- service/header/core_exchange_test.go
Just a bunch of cleanups and some of them should fix some core-related flakeyness. More description in comments
> chore(core): cleanup testing utilities

- docs/adr/adr-004-state-interaction.md
> docs/adr: Update state access ADR to include balance verification

- docs/adr/adr-003-march2022-testnet.md
> docs/adr: Update March 2022 testnet ADR to clarify bridge node

- README.md
- Add spacing before/after code blocks and lists
- Use single increment for headers
- Remove manual line breaks
- Fix install code block
> chore: misc readme cleanups

- .github/workflows/labels.yml
> ci: add job to check for required labels

- README.md
> README.md: Add minimum system requirements

- ipld/read.go
* explicit `nil` in last return statement seems more idiomatic (actually, just `return` would work in original implementation)
* removed named return values for consistency with other functions, and to make code more explicit
> refactor(ipld): nit-picks in GetLeavesByNamespace

- cmd/celestia/bridge.go
- cmd/celestia/full.go
- cmd/celestia/light.go
> fix(cmd): use ~ instead of $HOME in paths

- service/rpc/header.go
- service/rpc/share.go
- service/rpc/state.go
- service/rpc/util.go
* error handling is unified for all error types and endpoints
* duplicated code is extracted into function
* errors are returned as valid JSON, not plain text
Co-authored-by: rene <41963722+renaynay@users.noreply.github.com>
> feat(service/rpc): unified error handling

- ipld/retriever.go
> fix(ipld): fix race in rare case when Retriver fetches a share from both Row and Col

- node/tests/swamp/config.go
- node/tests/swamp/swamp.go
- node/tests/sync_test.go
> swamp: add options to swamp config

- node/state/keyring.go
This PR is based on #742 and I will rebase it once #742 is merged. It ensures that the keyring signer actually uses the correct key that is either mounted into the correct keystore path and specified via the `--keyring.accname` flag or generated on construction (if no key is present). Prior, the keyring signer was just generating the keys and not actually using the correct one as its default account.
> node/state: Ensures that keyring signer uses the correct key passed/generated during construction

- das/daser.go
- header/interface.go
* Store checkpoint in catchUpManager even if error occurs;
* fix logging in daser;
* fix errors in header;
> das: fix checkpoint in catch up manager

- README.md
Adaptt the main ReadMe to Mamaki testnet
> readme: add full node to the readme with links

- README.md
Node description link needs to be updated
> fix: node link expired

- cmd/flags_core.go
> cmd: Trim `--core.grpc` flag value

- cmd/flags_misc.go
- logs/logs.go
No issue here, just as simple flag and lowering verbosity of some annoying logs in our deps
> feat(cmd): add new flag to allow granular control over level of each logging module

- node/components.go
- node/node.go
- node/p2p/misc.go
- node/p2p/routing.go
- node/services/config.go
- node/services/service.go
- node/settings.go
- node/tests/p2p.go
- node/tests/sync_test.go
- params/bootstrap.go
- params/network.go
> params: add WithBootstrappers option

- node/store_test.go
> node: Some cleanup for a test in pkg node

- docs/adr/adr-006-fraud-service.md
- fraud/interface.go
* added Fraud service interface
> fraud: introduce fraud service interface

- node/rpc/component.go
- service/rpc/middleware.go
- service/rpc/server.go
* moved middleware creation as it will be needed in further PR with Fraud Service integrating.
> rpc: move middleware creation into separate file

- ipld/nmt_adder.go
- ipld/plugin/nmt.go
- ipld/retriever.go
- node/services/service.go
- service/share/light_availability.go
Multiple independent commits that just fix minor things. Happy to answer any questions about each, if any.
> fix(all): multiple findings and fixes

- service/rpc/endpoints.go
- service/rpc/state.go
- service/state/core_access.go
- service/state/interface.go
- service/state/service.go
- service/state/state.go
Resolves https://github.com/celestiaorg/celestia-node/issues/664
Manually test `/transfer` endpoint:
`curl -X POST -d '{"to": "celestia1vgq980fwpmmjutsfesvdrc9ykyamnycy92hugs", "amount": 100, "gas_limit": 100000}' http://localhost:26658/transfer`
TxResponse:
```
{
"height":68650,
"txhash":"1F1DF5B33024659FEB50DFB00A4F080DED6484E54BE2C679E25C656BD0579F2F",
"data":"12260A242F636F736D6F732E62616E6B2E763162657461312E4D736753656E64526573706F6E7365",
"raw_log":"[{\"msg_index\":0,\"events\":[{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"celestia1vgq980fwpmmjutsfesvdrc9ykyamnycy92hugs\"},{\"key\":\"amount\",\"value\":\"100utia\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"celestia1hu4hh8vdxeak3cjdqaq6dgwvan9w7hc9p5agkl\"},{\"key\":\" …
```
> state: add transfer endpoint

- ipld/plugin/nmt.go
Extracted from and should be merged before https://github.com/celestiaorg/celestia-node/pull/862. Some of these changes are required for libp2p to be updated, but logically a separate concern, for which we decided with @vgonkivs to make a separate PR
Closes https://github.com/celestiaorg/celestia-node/issues/656 completely
> chore(ipld/plugin): drop custom CID codec pluggability

- das/daser.go
Would close #801 . @renaynay Is this what you meant, or did you have something else in mind?
When I read the issue I assumed it was about the entire loop logic, but it seems that abstracting it would complicate both routines instead of making it more readable.
> das: unify logic in catchUp and sample

- das/daser.go
- das/daser_test.go
- fraud/bad_encoding.go
- fraud/proof.go
- fraud/service.go
- fraud/service_test.go
- fraud/testing.go
- header/interface.go
- header/sync/sync.go
- header/testing.go
- node/components.go
- node/node.go
- node/services/service.go
- node/state/state.go
- node/tests/fraud_test.go
- service/rpc/middleware.go
- service/state/service.go
> node: integrate fraud service

- node/tests/reconstruct_test.go
- node/tests/swamp/config.go
- node/tests/swamp/swamp.go
- node/tests/swamp/swamp_tx.go
1. Full node block reconstruction from bridge node only 
2. Full node block reconstruction from ligts (s=20;k=16;c=69)
> tests(node/swamp): block reconstruction

- docs/adr/adr-006-fraud-service.md
- fraud/bad_encoding.go
- fraud/bad_encoding_test.go
- fraud/proof.go
- ipld/retriever_byzantine.go
Current PR added all non-functional suggestions from #674 .
> fraud: fix findings in fraud package

- .github/workflows/go-mod-tidy.yml
- go.sum
> Add CI check for go mod tidy.

- node/p2p/p2p.go
- node/p2p/routing.go
> fix: add condition to restore routing table refresh period

- node/config.go
Self explanatory, found while refactoring core flags.
> node: Fix godoc for two methods on Config

- das/daser.go
- das/daser_test.go
- das/state.go
- header/sync/sync.go
- node/components.go
- node/rpc/component.go
- node/rpc_test.go
- service/rpc/das.go
- service/rpc/endpoints.go
- service/rpc/handler.go
- service/share/testing.go
Resolves #427 and https://github.com/celestiaorg/celestia-node/issues/869
TODO: 
---------------------------------------------------------------------------------------------------------------------------
Request
```
curl -X GET http://<ip>:26658/daser/state
```
Response
```
{"sample_routine":{"error":null,"is_running":true,"latest_sampled_height":104143,"latest_sampled_square_width":16},"catch_up_routine":{"start":"2022-07-07T15:01:25.747118+02:00","end":"0001-01-01T00:00:00Z","error":null,"id":1,"height":96247,"from":96162,"to":104142}}
```
> das: Implement `DASState`

- cmd/flags_core.go
> cmd: Trim trailing slash on given `--core.ip` addr

- go.mod
- go.sum
- header/p2p/subscriber.go
- node/p2p/pubsub.go
> deps: replacing blake2b implementation with native /x/crypto

- service/state/core_access.go
> chore(state): don't import sdk types twice

- .github/CODEOWNERS
> CODEOWNERS: Add vgonkivs and distractedm1nd to code reviewers

- das/daser_test.go
Resolves #921
The main reason in flakiness is that BEFP was broadcasted before daser was subscribed to it.
> test: fix daser test

- fraud/service_test.go
- node/tests/p2p_test.go
- node/tests/swamp/swamp.go
- service/share/testing.go
This PR aims to fix potential flakinesses in networking tests.
> testing: fix flakiness

- cmd/cel-key/node_types.go
> chore (cmd/cel-key): add closing bracket to description in cel-key

- cmd/cel-key/main.go
- cmd/cel-shed/main.go
- cmd/celestia/bridge.go
- cmd/celestia/cmd_test.go
- cmd/celestia/full.go
- cmd/celestia/light.go
- cmd/celestia/main.go
- cmd/env.go
- cmd/flags_core.go
- cmd/flags_header.go
- cmd/flags_key.go
- cmd/flags_misc.go
- cmd/flags_node.go
- cmd/flags_p2p.go
- cmd/flags_rpc.go
- cmd/init.go
- cmd/start.go
> cmd: Drop Env in favour of vanilla context.WithValue wrappers

- node/tests/fraud_test.go
- node/tests/reconstruct_test.go
- node/tests/swamp/swamp_tx.go
Resolves https://github.com/celestiaorg/celestia-node/issues/985
and this one https://github.com/celestiaorg/celestia-node/issues/943
> swamp: rework fill blocks

- go.mod
- go.sum
- header/testing.go
> go.mod: Upgrade ibc-go to v4.0.0

- go.mod
- go.sum
Upgraded Celestia-core to the latest version
> dep: bump celestia-core version

- .github/workflows/docker-build.yml
- .github/workflows/go-ci.yml
- .github/workflows/labels.yml
> Add `concurrency` block to cancel previous CI runs

- ipld/get_namespaced_shares.go
- ipld/get_shares.go
- ipld/helpers.go
This PR adds traces to `get_shares.go`, similar to the namespaced shares tracing
> tracing: Adding traces to `get_shares.go`

- .githooks/pre-commit
- Makefile
Adds a pre-commit git hook that runs the linter and `go mod tidy`
> feat: adding pre-commit hook and makefile installation script

- params/bootstrap.go
- params/default.go
- params/genesis.go
- params/network.go
In preparation for new devnet launch.
> params: Switch default network to `arabica`

- cmd/cel-key/node_types.go
> cmd/cel-key: Return err if no node type provided

- service/state/core_access.go
> refactor(service/state): Fix log to return correct height of balance request

- .github/CODEOWNERS
Follows recent discussions and https://github.com/celestiaorg/celestia-core/pull/858
> Remove @liamsi from global CODEOWNERS

- header/store/store.go
The verification of the headers can be done with only a RLock. By doing so, we provide a "very minor optimization" that can avoid the Lock to wait for processIncoming to finish (as he can take the lock).
Moving the verification to a separate function so that the deref for the RLock is scoped only to the needed part.
An alternative to this would be to get rid of the `defer s.writeLk.RUnlock()` and add a `s.writeLk.RUnlock()` at each return/exit of the function manually (but this wouldn't handle panic!() cases), so might be a no-go.
Close #864
> header/store: use an atomic.Pointer instead of Lock

- CONTRIBUTING.md
There is no `CHANGELOG_PENDING.md` file in this repo
> Remove Changelog section from CONTRIBUTING.md

- fraud/sync.go
> bugfix(fraud): close stream properly

- header/interface.go
- header/sync/sync_head.go
- header/verify.go
resolves https://github.com/celestiaorg/celestia-node/issues/1077
> log(header): Add detailed error for non-adjacent header attempt

- das/coordinator.go
- das/daser.go
- das/metrics.go
- das/worker.go
- nodebuilder/daser/opts.go
- nodebuilder/settings.go
~~Creating PR based on DASer PR. Most of the changes are in `metrics.go` and there are few additional lines in `das.go`, `coordinator.go`, `worker.go`.~~
Metrics preview:
Resolves 
https://github.com/celestiaorg/celestia-node/issues/1064
> das: add metrics to DASer

- logs/logs.go
I set log level in log module.
close #1154
> Disable verbose log on Debug Level for badger, watchdog, and basichost.

- share/get.go
- share/get_test.go
- share/ipld/get.go
- share/ipld/namespace_hasher.go
- share/ipld/namespace_hasher_test.go
- share/ipld/nmt.go
- share/ipld/nmt_adder.go
Closes https://github.com/celestiaorg/celestia-node/issues/183
> refactor(share): IPLD/NMT improvements

- nodebuilder/daser/module.go
- nodebuilder/header/module.go
- nodebuilder/module.go
- nodebuilder/p2p/bitswap.go
- nodebuilder/p2p/pubsub.go
- nodebuilder/p2p/routing.go
- nodebuilder/state/module.go
- nodebuilder/tests/fraud_test.go
- state/core_access.go
> fix: broken shutdown for services on fraud proofs receival 

- share/ipld/get.go
Self explanatory and found by @walldiss
> chore(share/ipld): remove dead code

- nodebuilder/header/header.go
> refactor(nodebuilder/header): Clarify error for init store failure

- .github/workflows/docker-build.yml
This should add semver tags to docker image builds on releases
> add semver tags to docker image builds

- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
This PR updates the chain id for and genesis hash for arabica after the recent hardfork
> chore(nodebuilder/p2p): Update to new arabica chain-id

- das/worker.go
> fix(das): Only debug log sampled header if it was actually successful

- share/availability/light/availability.go
Need further insight into debugging #1290
> feat(share/availability/light): Add some debug logs for sampling

- api/gateway/middleware.go
- api/gateway/server.go
- api/gateway/server_test.go
> feat(api/gateway): Implement context cancellation middleware

- .github/workflows/issue-labels.yml
> feat(.github): add labels on issues workflow

- .github/workflows/issue-labels.yml
Sorry, I forgot to add the import :(
> fix(.github): Point at correct action

- header/p2p/server.go
- header/p2p/server_test.go
Closes https://github.com/celestiaorg/celestia-node/issues/1316
> improvement(header/server): implement timeout for GetRangeByHeight request

- share/get_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1333
> fix(share): incorrect TestGetSharesByNamespace test

- header/p2p/exchange.go
Closes https://github.com/celestiaorg/celestia-node/issues/1309
> improvement(header/p2p): get bestHead if timeout is reached

- core/testing.go
- header/core/exchange_test.go
- header/core/listener_test.go
- header/header.go
- header/header_test.go
- header/testing.go
> fix(header): Extend `ValidateBasic` on `ExtendedHeader` to include data root check

- nodebuilder/p2p/genesis.go
After the hard-fork of `arabica-2` network, we need to reset the genesis hash
Ref: #1370
> chore!(nodebuilder/p2p): change genesis hash for upgraded arabica-2

- nodebuilder/tests/sync_test.go
Assert with swamp integration tests that Light and Full Node can sync and das over non-empty blocks
> tests(nodebuilder): sync and das over non-empty blocks

- go.mod
- go.sum
- nodebuilder/config.go
- nodebuilder/config_test.go
- nodebuilder/das/module.go
> fix(nodebuilder/das): Skip config validation for bridge node

- .github/workflows/labels.yml
> Add `kind:docs` as an oprtion for required labels

- .golangci.yml
- header/p2p/exchange.go
- header/p2p/helpers.go
- header/p2p/session.go
> improvement(header/p2p): unify sendMessage method to request headers

- header/p2p/exchange.go
- header/p2p/exchange_test.go
- header/p2p/options.go
- header/p2p/peer_stats.go
- header/p2p/peer_tracker.go
- header/p2p/peer_tracker_test.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1411, https://github.com/celestiaorg/celestia-node/issues/1317
> feat(header/p2p): implement gcing for peerTracker

- share/eds/pubsub.go
- share/eds/pubsub_test.go
- share/eds/subscription.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1432
> feat(share/blocksync): implementation of ShrEx/Sub

- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
Upgrades `mamaki` to `mocha`
TODO
> chore!(nodebuilder/p2p): Upgrade `mamaki` to `mocha`

- nodebuilder/p2p/config.go
- nodebuilder/p2p/module.go
> feat(nodebuilder/p2p): Enable `InfiniteLimits` for resource manager if bootstrapper

- nodebuilder/p2p/bootstrap.go
Nodekey for limani has changed.
> chore(nodebuilder/p2p): Update limani nodekey for arabica

- header/p2p/peer_tracker.go
- header/p2p/peer_tracker_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1533
> improvement(header|p2p): log the reason on blocking

- share/eds/store_test.go
> refactor(eds/store): store_test.go cleanup

- share/eds/adapters.go
- share/eds/adapters_test.go
Create a  `blockservice.BlockGetter` adapter for `eds.Store`, that could be used for share pkg.
Resolves https://github.com/celestiaorg/celestia-node/issues/1563
> feat(share/eds): Create a `blockservice.BlockGetter` adapter for `eds.Store`

- nodebuilder/p2p/host.go
- nodebuilder/p2p/mocks/api.go
- nodebuilder/p2p/module.go
- nodebuilder/p2p/p2p.go
- nodebuilder/p2p/p2p_test.go
> Revert "fix(node/p2p)!: remove resource manager and it's API (#1500)" 

- nodebuilder/tests/swamp/swamp.go
Fixes `no trusted peers` failure on main in Swamp tests
HeaderEx recently has started to sync from any peers, and the only place where trusted peers are required now is initialization. This change does initialization for nodes during instantiation in swap completely avoiding the requirement for trusted peers in the node's config.
As a side effect, we won't cover initialization anymore in swamp tests, so we should write some single test to specifically this.
Keeping it in draft until PRs below are merged, as they fix them: 
* https://github.com/celestiaorg/celestia-node/pull/1552
* https://github.com/celestiaorg/celestia-node/pull/1555
* https://github.com/celestiaorg/celestia-node/pull/1554
> feat(swamp): preinit all swamp nodes with genesis header

- nodebuilder/das/mocks/api.go
- nodebuilder/fraud/mocks/api.go
- nodebuilder/header/mocks/api.go
- nodebuilder/share/mocks/api.go
- nodebuilder/state/mocks/api.go
- share/getters/getter_test.go
- share/getters/ipld.go
- share/getters/store.go
- share/getters/utils.go
> feat(share): `getters.StoreGetter`

- api/rpc_test.go
- go.mod
- go.sum
> chore: updating rsmt2d to v0.8.0 and removing test skip

- header/p2p/exchange.go
We should stop waiting for headers and return an error In case of Exchange service context will be canceled.
> bugfix(header/p2p): handle long live context in head request

- cmd/cel-key/node_types.go
Update the flag name in `cel-key` from `--node.network` to `--p2p.network`.
> fix(cel-key): update flag name to --p2p.network

- share/getters/getter_test.go
- share/getters/tee.go
Closes #1535 . Based on #1528 .
> feat(share): `getters.TeeGetter`

- header/p2p/exchange.go
- header/p2p/helpers.go
> chore(header/p2p): improve logging and error wrapping

- header/p2p/server.go
Added traces to the headerEx.Server
> feat(header/p2p): add traces to server

- header/p2p/options.go
> fix(header/p2p): fix error string

- api/gateway/endpoints.go
- api/gateway/state.go
- docs/adr/adr-009-public-api.md
- nodebuilder/state/mocks/api.go
- nodebuilder/state/state.go
- state/core_access.go
- state/metrics.go
Closes #1447 
The call to app will be updated in a separate upgrade PR, this PR only changes our own API and types/docs.
Breaking because it changes an api endpoint
> refactor!: naming PFD/PayForData to PayForBlob

- libs/utils/traces.go
- share/eds/eds.go
- share/eds/store.go
- share/getters/ipld.go
- share/getters/store.go
- share/getters/tee.go
- share/getters/utils.go
> feat(share/eds): adding traces to edsstore, write/read eds, and getters

- docs/adr/adr-001-predevnet-celestia-node.md
- docs/adr/adr-005-plugins.md
- docs/adr/adr-template.md
> docs: fix minor typos

- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
> feat: bump arabica chain-id and genesis hash

- nodebuilder/p2p/bootstrap.go
> chore(nodebuilder/p2p): Update Arabica kaarina peerID

- header/header.go
Closes #1476.
We now also use tendermint's custom json encoding for `core.Header`. @preston-evans98 can you verify this PR achieves what you were looking for?
> feat: using tmjson encoding on `core.Header`

- go.mod
- go.sum
> dep(pubsub): upgrade pubsub version

- core/listener_test.go
- das/daser_test.go
- fraud/helpers.go
- fraud/requester.go
- fraud/service.go
- fraud/service_test.go
- fraud/sync.go
- fraud/testing.go
- libs/header/p2p/exchange.go
- libs/header/p2p/exchange_test.go
- libs/header/p2p/helpers.go
- libs/header/p2p/options.go
- libs/header/p2p/server.go
- libs/header/p2p/server_test.go
- libs/header/p2p/subscriber.go
- libs/header/p2p/subscription_test.go
- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
- share/p2p/shrexsub/pubsub.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1455, https://github.com/celestiaorg/celestia-node/issues/1454, https://github.com/celestiaorg/celestia-node/issues/1453
PLEASE NOTE: this PR is a protocol breaking since it introduces changes in protocol namings.
> feat!: add versioning for pubsub topics in fraud, header packages

- nodebuilder/p2p/network.go
> chore(nodebuilder/p2p)!: Upgrade arabica chain ID to `arabica-4`

- nodebuilder/p2p/genesis.go
Ref: https://github.com/celestiaorg/devops/issues/51
> chore!: bump arabica-4 genesis hash

- fraud/service_test.go
- fraud/testing.go
- nodebuilder/p2p/bitswap.go
- nodebuilder/p2p/module.go
- nodebuilder/share/module.go
> feat(nodebuilder/p2p): migrate to EDSStore Blockstore for Bitswap for FNs/BNs

- das/coordinator.go
- das/coordinator_test.go
- das/daser.go
- das/daser_test.go
- das/doc.go
- das/options.go
- das/state.go
- das/worker.go
- nodebuilder/das/constructors.go
- nodebuilder/das/module.go
- nodebuilder/share/module.go
Besides integrations, it allows recent headers to be sampled right away, without need to wait next available worker to process the job. This way recent headers are not restricted by concurrency limit and it should reduce sampling latency to allow Broadcast happen faster.
Closes https://github.com/celestiaorg/celestia-node/issues/1466
Closes https://github.com/celestiaorg/celestia-node/issues/1718
TODO:
> feat(das) add shrex.Sub integration into DASer

- nodebuilder/p2p/network.go
Upgrades chain ID to arabica 5 and updates genesis hash.
TODO:
> chore(nodebuidler/p2p)!: Upgrade arabica to `arabica-5`

- share/getters/shrex.go
- share/p2p/shrexeds/client.go
- share/p2p/shrexnd/client.go
Will eventually close #1489.
Does not do anything for integration, does not even include a constructor - this PR is purely for the retry logic
> feat(share/getters): ShrexGetter retry logic

- nodebuilder/p2p/genesis.go
> chore!: bump arabica-5 genesis-hash

- libs/header/sync/sync.go
- libs/header/sync/sync_head.go
- libs/header/sync/sync_test.go
Closes https://github.com/celestiaorg/celestia-node/issues/1728
> bugfix(libs/header): store incoming head in syncer

- das/daser_test.go
- headertest/testing.go
- nodebuilder/tests/fraud_test.go
- nodebuilder/tests/swamp/swamp_tx.go
- share/eds/retriever_test.go
Blocks were empty, which is why fraud edses were not broadcasted via shrex-sub and were not stored in the store.
> bugfix(swamp): fix fraud tests

- libs/header/p2p/exchange.go
- libs/header/p2p/session.go
> chore(libs/header/p2p): Fixing some debug logs

- share/p2p/peers/manager.go
Add extensive debug logging to peer manager
> feat(share/shrex/peer_manager): add debug logs to peer manager

- go.mod
- go.sum
- share/getters/shrex.go
- share/p2p/peers/manager.go
- share/p2p/peers/manager_test.go
- share/p2p/peers/pool.go
- share/p2p/peers/pool_test.go
- share/p2p/peers/timedqueue.go
- share/p2p/peers/timedqueue_test.go
Closes https://github.com/celestiaorg/celestia-node/issues/1731
> feat(share/shrex/peer_manager): add backoff in peer manager

- share/getters/shrex.go
Prevents infinite processing during availability calls
> fix(getters/shrex): removing implicit context assumption

- libs/header/interface.go
- libs/header/mocks/store.go
- libs/header/p2p/exchange_test.go
- libs/header/p2p/server.go
- libs/header/store/store.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1697
> improvement(libs/header): Check for requested height before fetching it from the store

- nodebuilder/share/constructors.go
- nodebuilder/share/module.go
- share/getters/shrex.go
- share/getters/shrex_test.go
- share/p2p/shrexnd/server.go
This PR puts the implemented puzzle pieces of the rearchitectured blocksync together, and integrates them into our app.
Closes #1492
Closes #1433 
Closes #1421
Closes #1464
> feat(share): Integrate rearchitectured blocksync into fx

- nodebuilder/share/config.go
- nodebuilder/share/constructors.go
- nodebuilder/share/module.go
- share/p2p/peers/manager.go
- share/p2p/peers/manager_test.go
- share/p2p/peers/options.go
> feat!(share): adding config variables for blocksync

- nodebuilder/p2p/network.go
Upgrades to `arabica-6` in preparation for shrex 🚀
> chore(nodebuilder/p2p)!: Upgrade arabica chainID for shrex upgrade

- nodebuilder/p2p/genesis.go
> chore(nodebuilder/p2p)!: Update genesis hash

- header/metrics.go
A few nodes stop submitting head metrics after some time in ITN dry-run. This might be a problem on the node side or OTEL collector. We add a timeout to see if this is a node issue, which can be only a deadlock there, and timeout would avoid it.
> fix(header): add timeout for the head retrieval

- fraud/helpers.go
- fraud/proof.go
> feat(fraud): String for FraudType

- das/options.go
- nodebuilder/das/config.go
- nodebuilder/share/constructors.go
- share/availability.go
- share/availability/full/availability.go
- share/availability/light/availability.go
- share/getters/cascade.go
- share/getters/cascade_test.go
- share/getters/shrex.go
- share/getters/utils.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1790 and closes https://github.com/celestiaorg/celestia-node/issues/10
> refactor(das|share): Cleanup timeouts through sampling stack

- nodebuilder/p2p/module.go
We don't want to ever have our trusted peers and mutual/reciprocal peers blocked by the resource manager. If it's blocked the LN can be easily eclipsed. 
Closes #1637
> feat(modp2p): add whitelist for ResourceManager, as eclipse protection

- nodebuilder/p2p/pubsub.go
- share/empty.go
- share/p2p/peers/manager.go
- share/p2p/shrexsub/pubsub.go
- share/share.go
> perf(share): don't broadcast datahash of empty EDS

- cmd/auth.go
This means that users will no longer have to run `celestia <node_type> start` in order to be able to use `auth` cmd. 
Results in better UX :)
> improvement(cmd): Auth cmd generates new priv key for jwt if not yet found in node store

- share/p2p/shrexeds/options.go
- share/p2p/shrexeds/server.go
Increases ODS write deadline to block time and adds the hash to failure log
> refactor(share/p2p/shrexeds): Increase ODS write deadline to block time and add hash to log

- nodebuilder/p2p/config.go
- nodebuilder/p2p/pubsub.go
> feat(modp2p): Make IP Colocation configurable for pubsub parameters

- share/availability/full/reconstruction_test.go
> fix(share/test): TestShareAvailable_DisconnectedFullNodes wait before exit

- .github/workflows/labels.yml
Add a `kind:refactoring` label to the GitHub workflows
> misc(github/workflows): add refactoring label and remove improvement

- libs/header/sync/sync_head.go
Because syncedHead and writeHead inside of Store are not synchronized, we can have a case we set a sync head as an old header. Happens when we received an old header from the network.
This is only fixing PR that has some ugliness on it. The refactoring PR is to follow.
> fix(libs/header/sync): resolve head synchronization issue

- libs/header/local/exchange.go
- libs/header/p2p/exchange.go
- libs/header/p2p/session.go
- libs/header/sync/ranges.go
- libs/header/sync/sync.go
- libs/header/sync/sync_test.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1567
> refactoring(header/syncer): request verified range of headers

- libs/header/interface.go
- libs/header/mocks/store.go
- libs/header/store/init_test.go
- libs/header/store/store.go
- libs/header/store/store_test.go
- libs/header/sync/sync.go
- libs/header/sync/sync_head.go
- libs/header/sync/sync_test.go
Amount of added headers to the store is redundant information, IMO. The only thing that we should know is whether `Append` was successful or not
> refactoring!(libs/header): simplify return params in store.Append

- NOTICE
~~Our licenses didn't include a year or owner~~. Updating based on conversations with @jeremysklaroff offline. 
**EDIT**
We don't edit the License file actually, what we wanted was a `NOTICE` file which indicates how the license is applied. This PR adds the minimal `NOTICE` file that was agreed upon offline.
> LICENSE: update copyright year and owner

- libs/header/sync/ranges.go
- libs/header/sync/ranges_test.go
- libs/header/sync/sync.go
Also renames Before to Truncate.
> fix(header/sync): fix possible out of bounds panic

- Makefile
> chore(Makefile): shush sort-imports

- libs/header/interface.go
- libs/header/p2p/exchange.go
- libs/header/p2p/exchange_test.go
- libs/header/p2p/options.go
- libs/header/p2p/peer_tracker.go
- libs/header/p2p/peer_tracker_test.go
- libs/header/p2p/server.go
- libs/header/sync/options.go
- libs/header/sync/sync.go
- libs/header/sync/sync_test.go
- nodebuilder/header/module.go
- nodebuilder/header/module_test.go
> refactoring(libs/header): cleanup config params

- core/listener.go
> misc(core): Add debug log to `CoreListener`

- libs/header/p2p/session.go
> refactor(libs/header/p2p): extend logging in session

- nodebuilder/gateway/flags.go
> fix: only use gateway flag value when the value is changed

- libs/header/p2p/session.go
As ErrNotFound is an expected and "valid" error, we should not print it as an error in logs.
> chore(libs/header/p2p): change log level in case of ErrNotFound

- core/client_test.go
- core/exchange.go
- core/fetcher.go
- core/fetcher_test.go
- core/header_test.go
- core/listener.go
- header/header.go
- header/headertest/testing.go
- nodebuilder/fraud/mocks/api.go
Resolves https://github.com/celestiaorg/celestia-node/issues/1640
> feat(core/listener): listen for EventDataSignedBlock

- docs/adr/adr-009-public-api.md
- nodebuilder/header/header.go
- nodebuilder/header/mocks/api.go
- nodebuilder/header/service.go
Blocked on method collision (cc @distractedm1nd )
Resolves https://github.com/celestiaorg/celestia-node/issues/1942
> feat(nodebuilder/header): Add `Subscribe` method implementation

- core/exchange.go
- core/listener.go
- header/header.go
> chore(core): Add logging

- nodebuilder/share/module.go
> fix(nodebuilder/share): Invoke pubsub for shrex

- share/p2p/peers/manager.go
- share/p2p/peers/manager_test.go
- share/p2p/peers/options.go
Temporarily disable blacklisting in peer manager until all related issues are fixed
> fix(shrex/peer-manager): Temporarily disable blacklisting in peer manager

- share/p2p/peers/manager.go
In case for given datahash there is no shrex peers, peer is be obtained from discovery pool. Before the fix, If such peer was put on cooldown, it would only be put on cooldown for corresponding to datahash pool. It would mean, that same peer could be obtained for same datahash from discovery pool without cooldown. It could resulting in unrestricted retries to the same peer from discovery and would lead to increased network strain for that peer .
This fix is incomplete and ugly. But it will target and fix the problem, just a bit harder, than it needs to be. Proper fix will take some time to implement and will me done following PR. 
Biggest issue with given solution is that if peer from discovery has ben put on cooldown for one hash, it will be not available for `Peer` method for another …
> fix(shrex/peer-manager): put on peer cooldown for peers from discovery

- share/eds/store.go
> fix(edsstore): close files after Put and Get

- README.md
> fix: updating broken link in README.md

- share/eds/store.go
- share/eds/store_test.go
- share/p2p/shrexnd/server.go
If item doesn't exist in store, return explicit error `ErrNotFound`.
> refactor(share/eds): add ErrNotFound to eds store and shrex server

- share/availability/light/availability_test.go
- share/eds/adapters_test.go
- share/eds/blockstore.go
- share/eds/blockstore_test.go
- share/getter.go
- share/getters/getter_test.go
- share/getters/ipld.go
- share/getters/store.go
- share/getters/utils.go
- share/ipld/get.go
- share/ipld/nmt.go
- introduce ErrNotFound to getter interface
- add support in ipld getter
- add support in store getter
Resolves https://github.com/celestiaorg/celestia-node/issues/2036
> feat(share/getter): add support for ErrNotFound in IPLD/Store getters

- go.mod
- go.sum
Tested multiple times on high latency connections, and it fixes #2006 and fixes #2032
> deps: bump go-header

- share/eds/store.go
> fix(share/eds): pass correct context to DagStore

- core/testing.go
- go.mod
- go.sum
> deps: Bump celestia-app version to 0.13.0

- nodebuilder/header/service.go
Related to https://github.com/celestiaorg/celestia-node/pull/2052#discussion_r1187252215
> refactor(header/service): ensure that the requested height is less or equal than the network head

- blob/blob.go
- blob/blob_test.go
- blob/helper.go
- blob/service.go
- blob/service_test.go
- header/headertest/testing.go
- share/get.go
Implemented blob service and covered it with UTs
> feat(blob): add blob service

- Makefile
> Makefile: fix docstring for cel-key target.

- blob/blob.go
- blob/blob_test.go
- blob/helper.go
- blob/service.go
- blob/service_test.go
Fixed all findings in https://github.com/celestiaorg/celestia-node/pull/2052:
* rework Proof creation(removed unneeded proofs from previous rows);
* Added a condition that verifies passed proof inside `Included`
* extended tests
> bugfix(blob/service): fix issues found during reviewing  the blob service

- blob/blob.go
- blob/blob_test.go
- blob/blobtest/testing.go
- blob/helper.go
- blob/service.go
- blob/service_test.go
- nodebuilder/tests/blob_test.go
- share/nid.go
> chore(blob): adapt changes

- Makefile
- api/rpc/client/client.go
- api/rpc_test.go
- nodebuilder/default_services.go
- nodebuilder/rpc/constructors.go
> feat(blob): register on the client and doc gen

- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
> chore!: bump arabica testnet params

- share/ipld/namespace_data.go
> chore(share/ipld): pretify error

- api/gateway/state.go
- blob/service.go
- blob/service_test.go
- nodebuilder/blob/blob.go
- nodebuilder/blob/mocks/api.go
- nodebuilder/state/mocks/api.go
- nodebuilder/state/state.go
- nodebuilder/tests/api_test.go
- nodebuilder/tests/blob_test.go
- state/core_access.go
> fix!(blob/module): fix api by changing variadic params to a slice

- nodebuilder/core/flags.go
Resolves https://github.com/celestiaorg/celestia-node/issues/2311
> fix(nodebuilder): fix parsing url for core.ip 

- openrpc.json
> chore(docs): update open rpc with blob module

- .github/workflows/labels.yml
Add testing tag for pure testing PRs
> add kind:testing label

- go.mod
- go.sum
- nodebuilder/blob/mocks/api.go
- nodebuilder/das/mocks/api.go
- nodebuilder/fraud/mocks/api.go
- nodebuilder/header/mocks/api.go
- nodebuilder/node/mocks/api.go
- nodebuilder/share/mocks/api.go
- nodebuilder/state/mocks/api.go
- share/mocks/getter.go
Change logs https://github.com/libp2p/go-libp2p/releases/tag/v0.28.1
> deps: bump libp2p

- share/getters/testing.go
> fix(lint): fix importing

- share/eds/retriever.go
- share/eds/store.go
- share/getters/cascade.go
- share/getters/ipld.go
- share/getters/shrex.go
- share/getters/store.go
- share/getters/tee.go
- share/getters/utils.go
- share/ipld/namespace_data.go
> fix: remove root from traces

- go.mod
- go.sum
> dep: update nmt version

- go.mod
- go.sum
- nodebuilder/store.go
Upgrades badger to latest version (v4). Also update badger config to the one shown no hangups.
> feat(share/eds)!: upgrade badger to v4

- cmd/cel-shed/eds_store_stress.go
- libs/edssser/edssser.go
- add pyroscope
- add put timeout 
- add badger log level flag
- log errors
Note: It is PR to feature branch.
> feat:(cmd/cel-shed): add few features to store stessser

- cmd/celestia/das.go
- cmd/celestia/rpc.go
Added `sampling-stats` cmd that allows to get current das status
> feat(rpc): add daser cmd

- cmd/celestia/header.go
- cmd/celestia/rpc.go
> cmd(rpc): add header cmd

- nodebuilder/p2p/bootstrap.go
- nodebuilder/p2p/genesis.go
- nodebuilder/p2p/network.go
> chore!: bump mocha chain with new bootstrappers and genesis hash

- openrpc.json
> chore(docs): add submit options for blob.Submit

- Dockerfile
> chore: fix unknown in ghcr registry

- .github/workflows/docker-build-publish.yml
> chore: bump docker ci to v0.2.3

- cmd/celestia/rpc.go
- cmd/celestia/state.go
> feat(rpc): add state cmd

- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- Makefile
- openrpc.json
closes: #2672 
Adds a simple ci check to generate openrpc.json file, and fail if it believes there are updates that are not present in the current openrpc.json file.
comments:
- should we simply add to `go-ci.yml`? I decided not to as it felt like different work that deserved it's own workflow
- possible we could add the `git diff` verify commands to the Makefile, yet this all felt ci specific and not worth polluting Makefile for, leaving the yml ugly vs the Makefile bloated.
- the target branch is hella out of date (go 1.19) we should think about getting main rebased in pretty soon @vgonkivs @distractedm1nd 
- [n/a] New and updated code has appropriate documentation
- [n/a] New and updated code has new and/or updated testing
> openrpc.json: Detect drift in openrpc spec

- .github/dependabot.yml
Adds dependabot rule, to reduce amount of otel dependancies PRs
> chore(dependabot): add otel group to dependabot

- cmd/rpc.go
> refactoring(rpc): remove authEnvKey

- openrpc.json
> fix: openrpc.json remove output line from generation of json

- nodebuilder/default_services.go
> fix(docgen): fix das naming for the openrpc spec

- nodebuilder/das/module.go
Change `daser` module name to `das`
> chore(nodebuilder/das): change daser module name to das

- nodebuilder/p2p/bootstrap.go
> feat: celestia mainnet bootstrappers

- nodebuilder/p2p/genesis.go
> feat(nodebuilder/p2p): Add mainnet genesis hash

- README.md
> chore: update link to node rpc docs

- nodebuilder/settings.go
* Increases UploadRate to 15 secs.
* Send goroutines profiles additionally 
Extracted from #2960
> chore(node): tweak pyroscope options

- nodebuilder/header/config.go
Part of an effort to decrease the memory footprint for LNs. Headers are pretty beefy.
Extracted from #2960
> chore(modheader): lower store cache size for LN

- .github/CODEOWNERS
> misc(config): add @ramin to codeowners

- share/getters/getter_test.go
- share/p2p/params.go
- share/p2p/shrexsub/pubsub_test.go
> share: typos fix

- go.mod
- go.sum
https://github.com/celestiaorg/go-header/releases/tag/v0.5.3
> chore: bump go-header

- share/share.go
- share/store/eds_file.go
- share/store/mem_file.go
- share/store/mem_file_test.go
Reworks `Share` method of `Store` to return shareWithProof containing axis field.
> feat(share/store): Allow Store implementation to choose proof axis for Share

- .github/workflows/create_release_tracking_epic.yml
This PR makes use of the reusable workflow that creates an EPIC in the devops repo and notifies the devops team on slack to help with tracking release deployments on our testnets and mainnet infrastructure.
> feat(ci): call reusable workflow to track the release deployments and notify devops

- .github/workflows/create_release_tracking_epic.yml
Bump fixes variable name for slack notifications.
> chore(deps): bump .github version for release tracking epic

- share/p2p/shrexsub/pubsub.go
Add recovery for message validation within shrexSub
> feat(share/p2p/shrexsub): add recovery to shrexSub

- das/daser_test.go
- go.mod
- go.sum
- nodebuilder/fraud/constructors.go
- nodebuilder/header/constructors.go
- nodebuilder/header/module.go
- nodebuilder/header/service.go
> deps: bump go-header and go-fraud

- go.mod
- go.sum
> deps: bump celestia-app

- share/eds/store.go
> refactor: add missing stop ticker

- .github/CODEOWNERS
- Expand individual members of CODEOWNERS
- (we should consider there being a @node GitHub team for this eventually)
> add @cristaloleg to .github/CODEOWNERS

- .github/workflows/go-ci.yml
- nodebuilder/fraud/lifecycle.go
- share/eds/cache/noop.go
Upgrade golangci-lint version in ci to 1.59
> chore(deps): upgrade golangci-lint in ci to 1.59

- store/file/header_test.go
> test(store): add header de/serialization fuzzing

- nodebuilder/pruner/constructors.go
- pruner/service.go
> refactor: use libhead alias consistently

- nodebuilder/p2p/bootstrap.go
Arabica Bootstrappers now follow the `dnsaddr` of `multiaddr`.
https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md
> feat: arabica bootstrappers now dnsaddr multiaddr

- share/shwap/p2p/bitswap/block_fetch_test.go
- share/shwap/p2p/bitswap/block_store.go
Blockstore must cleanup the accesor
> fix(shwap/bitswap): close acccessor in Blockstore

- share/shwap/namespace_data_id.go
- share/shwap/namespace_data_id_test.go
Add namespaced data shwap id message
> feat(shwap): Add namespace data shwap id

- share/new_eds/validation_test.go
- share/shwap/eds.go
- share/shwap/eds_id.go
- share/shwap/getter.go
- share/shwap/namespace_data.go
- share/shwap/namespace_data_id.go
- share/shwap/p2p/shrex/shrexeds/exchange_test.go
- share/shwap/row_id.go
- share/shwap/row_namespace_data.go
- share/shwap/row_namespace_data_id.go
- share/shwap/sample_id.go
* Fixes ErrInvalidID
* Comment
* Name
* Location
* Adds notes for EDS and NamespaceData containers
* Adds Read/Write methods on RowNamespaceData to be used by NamespaceData
> chore(shwap): various improvements

- blob/service.go
- blob/service_test.go
Integrate shwap to the blob module
> feat(shwap): add shwap to blob module

- Makefile
Closes https://github.com/celestiaorg/celestia-node/issues/3639
> chore: improve Make help command

- share/new_eds/proofs_cache.go
This PR fixes usage of local copy of cached axis
> fix(shwap/cahce): use local copy of axis in  proofs cache

- .github/CODEOWNERS
> ci(CODEOWNERS): remove @ramin

- store/file/ods_q4.go
Fixes two issues:
* incorrect error check
* Close to wait for the Q4 being opened
> fix(store/files): ODSQ4 Closing audit

- store/file/file.go
- store/file/header.go
- store/file/header_test.go
- store/file/ods.go
- store/file/ods_q4.go
- store/file/ods_q4_test.go
- store/file/ods_test.go
- store/file/q4.go
- store/store.go
- store/store_cache.go
Contains five commits with various bug fixes and improvements.
The PR is meant to be merged as 5 separate commits grouped under a common theme.
> misc(shwap/store): miscelaneous improvements 

- share/shwap/namespace_data_id.go
Addition to https://github.com/celestiaorg/celestia-node/pull/3696
> fix(shwap):  io.ReadFull for NamespaceDataID

- go.mod
- go.sum
> chore(deps): bump go-libp2p-kad-dht to v0.26.1

- nodebuilder/p2p/bootstrap.go
> feat: mocha bootstrapper now with dnsaddr

- nodebuilder/p2p/bootstrap.go
Added a community run bootstrapper node for mocha.
> feat(chore): Add the Pops.one bootstrapper to the Mocha test network

- nodebuilder/p2p/bootstrap.go
> Add Qubelabs Bootstrapper for Mocha

- store/file/ods.go
There was a race condition for reseting the offset in file. This change fixes the race and removes the need for global offset by making it local to SectionReader
> fix(store/ods): fix full ods caching

- nodebuilder/share/bitswap.go
- nodebuilder/share/config.go
- nodebuilder/share/module.go
- store/store_cache.go
Expose Blockstore cache size to nodebuilder config.
> feat(nodebuilder): Blockstore cache params

- core/exchange_test.go
Skip empty blocks in generateNonEmptyBlocks
> fix(core): fix flaky generateNonEmptyBlocks

- share/shwap/p2p/bitswap/block_store.go
There were two error logs per every Bitswap request for a not synced EDS. Not anymore.
> chore(shwap/bitswap): prevent not found error logging

- share/shwap/p2p/bitswap/getter.go
> chore(shwap/bitswap): add getter tracing

- nodebuilder/p2p/bootstrap.go
> Add bootsrapper for mainnet by Qubelabs

- nodebuilder/p2p/bootstrap.go
> Add bootstrapper mainnet P-OPS

- nodebuilder/blob/mocks/api.go
- nodebuilder/node/mocks/api.go
- nodebuilder/share/mocks/api.go
- nodebuilder/state/mocks/api.go
Some mocks are outdated, this PR updates all generated mocks to latest version.
> chore(mocks): update generated mocks

- core/listener.go
- go.mod
- go.sum
- header/header.go
Updates v16 release branch with recent man changes
> chore(backport): backport changes from main to v0.16.1 release branch

- nodebuilder/share/p2p_constructors.go
- share/shwap/p2p/discovery/discovery.go
> chore(shwap/discovery): prefix -> suffix

- go.mod
Go timer issue is fixed in 1.23.2 https://github.com/golang/go/issues/69333
> fix: remove godebug asynctimerchan=1

- blob/service_test.go
> ci: fix linter

- share/shwap/p2p/bitswap/block_fetch.go
Lower severity of non-critical log
> fix(share/p2p/bitswap): lower bitswap log severity

- store/store.go
Resolves https://github.com/celestiaorg/celestia-node/issues/3853
> feat(store): use use relative path for empty blocks symlinks

- nodebuilder/p2p/misc.go
> fix(nodebuilder/p2p): lint

- .github/workflows/ci_release.yml
Based on failure from https://github.com/celestiaorg/celestia-node/actions/runs/11477726500/job/31941228959
> fix(ci): GH_TOKEN for upload-docs

- Makefile
- core/exchange_test.go
> fix(core): change fill block mode

- api/docgen/examples.go
> fix(openrpc-gen): add go-square blob to examples

- go.mod
- go.sum
> deps(go.mod): bump app

- api/docgen/examples.go
> fix(api): add time.Duration and rsmt2d.Axis types

- api/docgen/examples.go
- api/docgen/openrpc.go
Adding `add(v any)` and `must` that simplifies life.
> refactor(docgen): simplify init

- go.mod
- go.sum
bumping node out of good habit, although there are no changes that could have an effect on node
> chore: bump app to v3.3.1-arabica

- nodebuilder/tests/prune_test.go
> fix(test/swamp): fix TestConvertFromArchivalToPruned

- api/docgen/examples.go
> fix(docgen): add network.Direction

- .github/workflows/ci_release.yml
> chore(ci): fail openrpc-gen if error

- share/shwap/p2p/discovery/dht.go
> fix(shwap/discovery): increase DHT refresh interval to default 10mins

- api/gateway/bindings_test.go
- das/state.go
- nodebuilder/node/type.go
- nodebuilder/store.go
- nodebuilder/tests/swamp/swamp.go
> refactor(all): modernized code with built-in func

- nodebuilder/p2p/bootstrap.go
Add 01node bootstrap node for testnet - mocha-4
> chore(nodebuilder): add 01node bootstrap testnet node

- nodebuilder/p2p/bootstrap.go
Add ZKV mocha testnet bootstrap node
> chore(nodebuilder): add ZKV mocha bootstrap node

- share/shwap/p2p/bitswap/getter.go
This is allows us to test the theory behind #4199.
We can merge it to the main s.t. we can also ask our partners to toggle it and see results for them.
> feat(shwap/bitswap): disable session pruning with env var

- .gitignore
> misc(.gitignore): ignore go.work.sum

- README.md
> docs(README): add supported archs

- .github/CODEOWNERS
> chore(CODEOWNERS): remove @cristaloleg

- .github/CODEOWNERS
Welcome to Ganesh! 🎉
This PR adds Ganesh as a code owner to the repository. Looking forward to your contributions and collaboration on the project!
> Add Ganesh to CODEOWNERS

- go.mod
- go.sum
rolls back accidental go-header bump
> deps(go.mod): roll back go-header release

- go.mod
- go.sum
> deps(go.mod): Bump app mocha

- go.mod
- go.sum
> deps(go.mod): Bump app --> `mocha`

- .golangci.yml
> fix: fix lint

- blob/service_test.go
> fix(test/blob): fix flaky blob test

- api/docgen/openrpc.go
- api/rpc_test.go
- nodebuilder/da/da.go
- nodebuilder/da/service.go
- nodebuilder/default_services.go
- nodebuilder/node.go
- nodebuilder/rpc/constructors.go
This PR adds doc for deprecated DA API
> docs(api/da): doc and deprecate DA API

- nodebuilder/share/share.go
PR removes the need to pass ExtendedHeader to Samples method of share module API, making it consistent with other methods of the module
> !fix(api/share) use height in Samples method

- nodebuilder/config_test.go
- nodebuilder/share/config.go
- nodebuilder/share/constructors.go
Adding a bool flag that allows for manually turning off the bitswap, since we are going to remove it soon.
> feat(config): adding a bool flag to enable/disable bitswap

- nodebuilder/das/config.go
- nodebuilder/das/module.go
Resolves https://github.com/celestiaorg/celestia-node/issues/4510
> feat(nodebuilder): Allow disabling DASer

- share/shwap/namespace_data_id.go
> fix(share/shwap): parallelise namespace data collection

- go.mod
- go.sum
- nodebuilder/tests/tastora/go.mod
- nodebuilder/tests/tastora/go.sum
> chore: use arabica tag

- nodebuilder/tests/tastora/go.mod
- nodebuilder/tests/tastora/go.sum
> chore: bump go-header for tastora
